### ISSUE TITLE
Add ANSI colors support in plugin output

### ISSUE THREAD

**Issue by melonamin** [swiftbar/SwiftBar#1]

**Comment by yanzhang0219** [comment]
Please support this. Please!!
Thank you.

**Comment by yanzhang0219** [comment]
When will ANSI colors be supported approximately? 
I am writing a plugin to show the workspaces on the menu bar, cooperating with window manager yabai. 
It shows like `1 2 | 3 | 4`, three monitors delimited by `|`. And now I want to highlight (i.e., using the color red) the currently focused workspace, however, SwiftBar doesn't support ANSI color code yet. This is really a must-have feature. 
Thank you very much for your hardworking.

**Comment by SxC97** [comment]
> I am writing a plugin to show the desktops (i.e., workspaces) on the menu bar, cooperating with the macOS tiling window manager yabai.
> It shows like `1 2 | 3 | 4` which means I am using three monitors, desktop 1 and 2 are on the left monitor, desktop 3 is on the middle monitor and desktop 4 is on the right monitor. And now I want to highlight (i.e., using the color red) the currently focused desktop, however, SwiftBar doesn't support ANSI color code yet. I believe this is really a **must-have** feature for most of us.

I have written a very similar app for BitBar and am waiting for SwiftBar to get this feature too.

https://github.com/SxC97/Yabai-Spaces

**Comment by yanzhang0219** [comment]
@SxC97 Thank you. 
I want to write my own to fit my specific requirement like multiple monitors support, showing window status, and workspace type. I will persist on BitBar until SwiftBar supports ANSI.

**Comment by melonamin** [comment]
I was hoping some one will take over this one... I guess I'll do it myself this weekend ¯\_(ツ)_/¯
Stay tuned.

**Comment by yanzhang0219** [comment]
Cannot wait!!! Thank you!!

**Comment by SxC97** [comment]
@yanzhang0219 I believe there has been a misunderstanding. My comment was directed to the maintainer of this repo to show an example of an existing plugin that would benefit from the addition of ANSI color support.

But since you brought it up...

> I'll write my own plugin ... with elegant and concise code.

I wish you the best of luck with your project but I do not appreciate you casting aspersions on my work.

**Comment by yanzhang0219** [comment]
@SxC97 Hi, sorry about that. And you misunderstood me as well. I said "write my own plugin with elegant and concise code" which means that I will write a plugin to precisely fit my own requirement so that the code will be short, i.e., it will be perfectly customized for myself and I don't have to put some other general code to cater most others. Please forgive me and my misunderstanding words. 

Thank you.

**Comment by yanzhang0219** [comment]
I didn't see this in the milestone 1.1.0, will this be released in 1.1.0? Thank you.

**Comment by melonamin** [comment]
Made some progress, looks like a good enough first version:

```
#!/bin/bash
echo -e "\033[38;5;82mHello \033[38;5;198mWorld | ansi=true"
echo "---"
echo -e "\033[40;38;5;82m Hello \033[30;48;5;82m World \033[0m | ansi=true"
```
<img width="206" alt="Screen Shot 2020-12-13 at 11 49 42 AM" src="https://user-images.githubusercontent.com/222100/102018133-4b425280-3d39-11eb-8105-6323571ceb3e.png">


```
#!/bin/bash

free=`top -l 2 | grep "CPU usage" | tail -1 | awk '{printf "%.0f", $7+0}'`
let used=100-$free

printf "CPU "
printf "%2d%% " $used
#printf "["
let count=0;
BAR='▮'
while [ $count -le 100 ]
do
        if [ $used -ge $count ]
        then
            if [ $used -le 50 ]
            then
                    printf "\e[32m$BAR" # green
            elif [ $used -le 80 ]
            then
                    printf "\e[33m$BAR" # yellow
            elif [ $used -le 100 ]
            then
                    printf "\e[31m$BAR" # red
            fi
        else
            #printf "\e[37m$BAR"
            printf "\e[1;30m$BAR"
            #printf " "
        fi
        let count=${count}+10
done
#printf "]"
printf "| ansi=true"

echo ''

ps xro %cpu=,comm= | while read cpu comm; ((i++<5)); do
    int=$cpu
    int="${int%%.*}"

    echo "$color$cpu% $(basename "$comm")"$'\e[0m'"";
done
```

<img width="337" alt="Screen Shot 2020-12-13 at 11 50 21 AM" src="https://user-images.githubusercontent.com/222100/102018151-6319d680-3d39-11eb-888b-3936233ea527.png">

**Comment by yanzhang0219** [comment]
Looks awesome. Are you planning to release a Beta 2 for us to test this ANSI feature? Thanks.
