### ISSUE TITLE
Support dropping stuff on menu bar

### ISSUE THREAD

**Issue by melonamin** [swiftbar/SwiftBar#104]
Dropped files, URL, etc. should be processed and passed to the plugin script

**Comment by yanzhang0219** [comment]
This is what I want to open an issue to request. Really a nice feature. 🤗

**Comment by andyconlin** [comment]
Thank you for adding this!

Can you give a barebones example of how to access dropped items in the plugin script?

I'm not super familiar with Swift,  but I've looked through:
d2b555ebf08aae3f40512ab896b29221cdb34961
be543b3cc16077da92ef763494191dccf8863f8d
to get a sense of what might be happening.

I'd like a script to be able to access a URL dropped onto the menu item. This sort of thing hasn't worked yet:
```
...
# <bitbar.droptypes>URL</bitbar.droptypes>

echo "hello"
echo "world"
echo "$1" | pbcopy
```

I also tried other items in `# <bitbar.droptypes>`, like `string` and `fileURL`.
I was able to get the standard dropzone cursor (green plus sign) when dragging a file over the menu item, but it wouldn't show up when dragging a link. And even when dropping a file on it, I wasn't able to see how to access the dropped item from the script anyway.

I'm not sure what to try next to access the  going to keep trying things, but was hoping someone else may be able to whip out a few lines of code to demonstrate this in their sleep.

If someone can share some starater code to access dropped items, I'd be happy to write up basic documentation for [README.md](https://github.com/swiftbar/SwiftBar/blob/main/README.md) (or wherever else it'd be helpful).

Thanks!

P.S. The gist of the script I'd like to write is to be able to quickly save/process URLs, depending on the type, e.g. youtube --> [Play app](https://apps.apple.com/us/app/id1596506190), others --> Pocket or Things, etc.

**Comment by melonamin** [comment]
Yeah, it is clear that an example is needed. Let me work on that, I'll get back to you

**Comment by michkozak** [comment]
Hey @melonamin, at the risk of being a PIA: any ETA on that example 😃 ? I've been banging my head at this for an hour and can't get it to work.

I've quickly looked through the two commits mentioned by @andyconlin and from what I understand, once you define [supported droptypes](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html#//apple_ref/doc/uid/TP40009259-SW1) (I tried a bunch) you can drop a URL or a file(s) on the plugin's menubar item (you'll see the standard dropzone cursor, a white plus sign in a green bubble right next to your cursor) and SwiftBar will execute that plugin in the Terminal, at which point the plugin should have access to the `DROPPED_FILES` variable containing comma-separated file paths or a URL.

My plugin gets executed, but the `DROPPED_FILES` variable is always empty. The regular positional arguments (`$1`, `$2`, …, `$9`) are also empty and `$#` always says `0`.

What am I missing here? Can you point me in the right direction?  Also, is there a way to tell SwiftBar to execute the plugin in the background, without launching the Terminal?

Any advice would be greatly appreciated!

**Comment by melonamin** [comment]
@michkozak yeah, the reason why it takes so long for me to give you an example is a bug I’ve found. I don’t think it works right now at all, I’ll try to get around to fix it this week. Sorry, been a bit busy lately.

**Comment by michkozak** [comment]
@melonamin Understood, no worries. Patiently waiting then 😃.

P.S. Have you thought about introducing a convenient way of recognizing the dropped item type, so there's no need to do that manually in the script? Maybe a ` DROPPED_URL` variable? If would simplify things. When a URL is dropped, `DROPPED_URL` is populated and `DROPPED_FILES` is empty. When a file or files are dropped, `DROPPED_FILES` is populated and `DROPPED_URL` is empty. Just a thought.

**Comment by melonamin** [comment]
Try [beta](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.4-beta-3) build.

Three env variables:
- `LAUNCHED_FROM_DROP_ACTION` equals `TRUE` when plugin script launched from drop action, doesn't exist otherwise
- `DROPPED_URL` contains URL on non-file(http, ftp, etc.) URL drop. Single value.
- `DROPPED_FILES` contains files URLs, array of values.

Dropping file will launch plugin script in background, this will not refresh your plugin!

This sample plugin will open dropped URL in your default browser and do nothing for file drops:

```bash
#!/bin/bash
#<bitbar.droptypes>public.url</bitbar.droptypes>

echo "|sfimage=cloud"
echo "---"

if [[ -z "${DROPPED_URL}" ]]; then
  echo
else
  open "${DROPPED_URL}"
fi
```

**Comment by michkozak** [comment]
@melonamin Thanks!

Dropping URLs and files on the menubar item is now working correctly and populates `$DROPPED_URL` and `$DROPPED_FILES` respectively, as expected.

However, working with `$DROPPED_FILES` in its current form is problematic. Given that `$DROPPED_FILES` is not an actual array of file path strings, but rather a string containing comma-separated file paths - you can't easily split it to work with individual paths if any of the paths contain a comma (`,`). 

Seems like only spaces in file paths are encoded, so `My super, super secret document.pdf` becomes `My%20super,%20super%20secret%20document.pdf`. Maybe encode commas as well, so that `My super, super secret document.pdf` becomes `My%20super%2C%20super%20secret%20document.pdf`? That way we could easily split `$DROPPED_FILES` by a comma and deal with individual file paths.

**Comment by melonamin** [comment]
@michkozak good point, fixed
