### ISSUE TITLE
Plugin metadata support for binary plugins

### ISSUE THREAD

**Issue by melonamin** [swiftbar/SwiftBar#105]
### Current

Plugins can opt-in to support [metadata](https://github.com/swiftbar/SwiftBar#script-metadata) in script header, including [special flags](https://github.com/swiftbar/SwiftBar#hiding-default-items) to configure SwiftBar.

### Problem

There is no way to provide metadata for binary plugins.

### Proposal

Store plugin metadata in files extended attribute `com.ameba.SwiftBar`

### Example

Take metadata as it is in non binary plugin(in this case I've created `metadata.txt` file):
```
# <bitbar.title>Dark Mode Toggle</bitbar.title>
# <bitbar.version>v1.0</bitbar.version>
# <bitbar.author>huhu</bitbar.author>
# <bitbar.author.github>Phlooo</bitbar.author.github>
# <bitbar.desc>Simple toggle for macOS Dark Mode</bitbar.desc>
# <bitbar.image>https://i.imgur.com/khIIfMg.png</bitbar.image>
# <bitbar.dependencies>bash</bitbar.dependencies>
# <bitbar.abouturl>https://github.com/Phlooo/</bitbar.abouturl>
# <swiftbar.hideAbout>true</swiftbar.hideAbout>
# <swiftbar.hideRunInTerminal>true</swiftbar.hideRunInTerminal>
# <swiftbar.hideLastUpdated>true</swiftbar.hideLastUpdated>
# <swiftbar.hideDisablePlugin>true</swiftbar.hideDisablePlugin>
# <swiftbar.hideSwiftBar>true</swiftbar.hideSwiftBar>
```

Write it to an extended file attribute as base64:
`xattr -w "com.ameba.SwiftBar" "$(cat metadata.txt | base64)" <plugin_file>`

**Comment by yanzhang0219** [comment]
I really appreciate how you organize, develop, and manage a project. 👍
You open issues like this to describe the new features you are going to implement, mark each issue an appropriate label for better tracking afterward, attach the issue number to the commit showing which issue it solves, use the milestone as a roadmap to list what features we're expecting will be implemented in the next release. All of these make users know well the growth process of this repo.
I learn a lot. Thank you. ❤️

**Comment by bilal-fazlani** [comment]
[myplugin.5s.zip](https://github.com/swiftbar/SwiftBar/files/5742948/myplugin.5s.zip)

Attached is a zip file containing my a sample plugin. (It requires JAVA to run)
I have added the attributes under `com.ameba.SwiftBar` name. 

![image](https://user-images.githubusercontent.com/3396271/103149863-beb17e80-4793-11eb-98af-c93890af9b47.png)

As seen in the screenshot above, I can read the metadata using CLI.

But for some reason, SwiftBar doesn't seem to be read or understand any of the information present in metadata.

It does not hide SwiftBar related menu items even when it is configured in the metadata.

**Comment by bilal-fazlani** [comment]
[hello.5s.sh.zip](https://github.com/swiftbar/SwiftBar/files/5742966/hello.5s.sh.zip)

The functionality however is working for a bash plugin when I use xattr with it.

**Comment by bilal-fazlani** [comment]
![image](https://user-images.githubusercontent.com/3396271/103150070-35e81200-4796-11eb-8ba2-2207a70ce3ad.png)

both plugins have same xattr, but the unable to see author info for the binary plugin

**Comment by bilal-fazlani** [comment]
hideAbout, hideSwiftBar working for bash plugin with xattr, but not for binary

![image](https://user-images.githubusercontent.com/3396271/103150145-359c4680-4797-11eb-8cc1-15e52fed6886.png)
![image](https://user-images.githubusercontent.com/3396271/103150146-39c86400-4797-11eb-9bf1-781b07f86c12.png)

**Comment by melonamin** [comment]
Thank you for an example, fixed in [Beta 2](https://github.com/swiftbar/SwiftBar/releases/tag/v1.2.0-beta-2)

**Comment by bilal-fazlani** [comment]
Thanks! I will test and let you know. 

Btw, I changed the name of a scala framework I was building to SwiftBar4s from BitBar4s. Thanks for providing binary compatibility. 

It's here https://swiftbar4s.bilal-fazlani.com/ if you want to take a look. Still a work in progress. 
Planning to pick up work to make it easy to embed images. Will try to keep up with all the new features you keep adding :D

**Comment by bilal-fazlani** [comment]
Working as expected for binary plugin now. Thanks!
