### ISSUE TITLE
echo bell symbol? (audible signal)

### ISSUE THREAD

**Issue by bjinse** [swiftbar/SwiftBar#106]
I created a plug-in to monitor our systems. Lots of checks are performed periodically. When one of the checks fails, I change the plugin title to red instead of green, and in the drop-down menu I show all failing checks. Works great so far.

It would be nice if I could incorporate an audible signal when the state switches from green to red.
I tried: echo "\a" but that does not work, (like it does work in a terminal).
Is there a workaround? Or is it possible to create a parameter "|bell=true" for this?
Even if this is executed on every update, it would be ok for me.

**Comment by melonamin** [comment]
>I tried: echo "\a" but that does not work, (like it does work in a terminal).

Yeah, this wouldn't work, but something like this will `afplay /System/Library/Sounds/Funk.aiff` 

I've been thinking about a "notification system" in SwiftBar for sometime, but don't have a fully baked design as of now

**Comment by bjinse** [comment]
Thanks, This indeed works! Using Python here, so I use:
os.system('afplay /System/Library/Sounds/Sosumi.aiff') 
BTW, are you interested in a Dutch Localization for Swiftbar? I would be happy to translate.

**Comment by melonamin** [comment]
> BTW, are you interested in a Dutch Localization for Swiftbar? I would be happy to translate.

Yes, please! I've added [a file](https://github.com/swiftbar/SwiftBar/blob/main/SwiftBar/Resources/Localization/nl.lproj/Localizable.strings) for you to edit.
