### ISSUE TITLE
SwiftBar 1.1.1 no longer recognises my GitHub style emojis

### ISSUE THREAD

**Issue by arohl** [swiftbar/SwiftBar#108]
Just upgraded from 1.1.0 to 1.1.1 and my menubar now has the text _:sunflower:_ at the start rather than the sunflower emoji. I also tried :mushroom: but it didn't work either

**Comment by arohl** [comment]
Arghhh - it looks like GitHub is recognising them, even if I put them in quotes... So rather than having the emoji in my menubar I have the text - in my case sunflower with a : at either end

**Comment by melonamin** [comment]
Yep, this is new, a have a note about it in the release notes:
`Improved: SF Symbols have priority, emoji will work only if SF Symbols explicitly disabled. #46 `

So you need to add `symbolize=false` and it should work.

**Comment by jasonsnell** [comment]
I will also add that if you actually place the sunflower emoji in your plug it _should_ work...

**Comment by arohl** [comment]
@melonamin, yes that does work - I only looked at the README file, not the release notes :-)

@jasonsnell, embedding emojis directly worked too

Last question and then I'll close the issue - SF Symbols don't seem to work on Catalina - is this expected?

Merry Christmas!

**Comment by melonamin** [comment]
>@melonamin, yes that does work - I only looked at the README file, not the release notes :-)

Fair, edited README  https://github.com/swiftbar/SwiftBar/commit/

>Last question and then I'll close the issue - SF Symbols don't seem to work on Catalina

Yes, Big Sur only, macOS limitation.

**Comment by arohl** [comment]
Thanks for all the help
