### ISSUE TITLE
General bug: default menu font size is too small

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#11]
I have noticed this in all of my plugins, but I'm using a simple one as an example.

The menu font size (not in the menu bar itself, but in the menu incl. submenus) is smaller than the default size, ca. 1 or 2 points smaller. See screenshot and the script used below.

![snap](https://i.imgur.com/czS53qY.png)

```
#!/bin/zsh

# <bitbar.title>Thing Ping</bitbar.title>
# <bitbar.version>v1.3</bitbar.version>
# <bitbar.author>Joss Brown</bitbar.author>
# <bitbar.author.github>JayBrown</bitbar.author.github>
# <bitbar.desc>Runs a ping to determine network latency</bitbar.desc>
# <bitbar.image>undef</bitbar.image>

# Thing Ping BitBar plugin
# https://github.com/matryer/bitbar

version="1.3"

allfontfamilies=$(osascript 2>/dev/null << EOF
use framework "AppKit"
set fontFamilyNames to (current application's NSFontManager's sharedFontManager's availableFontFamilies) as list
return fontFamilyNames
EOF
)
if echo "$allfontfamilies" | grep -q "SF Mono" &>/dev/null ; then
	menufont="font=SFMono-Regular size=11"
else
	menufont="font=Menlo-Regular size=11"
fi

millisecs=$(ping -c 2 -n -q 1.1.1.1 2>/dev/null | tail -n 1 | awk -F/ '{print $5}')
secs=$(echo "scale=3 ; x=${millisecs}/1000 ; if(x<1) print 0 ; x" | bc 2>/dev/null)

if ! [[ $secs ]] ; then
	if [[ $(route get 0.0.0.0 2>&1) == "route: writing to routing socket: not in table" ]] ; then
		echo "route | color=red $menufont dropdown=false"
	else
		echo "-.--- | color=red $menufont dropdown=false"
	fi
else
	if (( $(bc <<< "$secs < 0.100") )) ; then
		echo "$secs | $menufont dropdown=false"
	else
		if (( $(bc <<< "$secs < 1") )) ; then
			echo "$secs | color=blue $menufont dropdown=false"
		else
			echo "$secs | color=red $menufont dropdown=false"
		fi
	fi
fi

echo "---"

echo "Thing Ping"
echo "v$version | alternate=true"

echo "---"

scriptpath="$0"

echo "Open in Editor… | terminal=false bash=/usr/bin/open param1=\"$scriptpath\""

exit

```

**Comment by melonamin** [comment]
Note looks like doesn't apply to Big Sur, only Catalina:

<img width="239" alt="SwiftBar Invert Colors" src="https://user-images.githubusercontent.com/222100/100104497-440fdf00-2e34-11eb-8418-d35a581818cd.png">

**Comment by melonamin** [comment]
What are you using as a reference for "default size"?

I haven't found anything about recommended font size in [HIG](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/), so currently I'm just using `NSFont.systemFontSize`

**Comment by JayBrown** [comment]
Tinker Tool is giving me these settings, which are the system defaults except for the monospaced font:

![snap](https://i.imgur.com/N8DKuXt.jpg)

…so I assume that the font size in menu bar menus is 13 points, which seems correct because the small font size in the below screenshot is 11 points, menu entries coming from the script are about 1 point bigger (12 pt), and the fixed menu entries coming from SwiftBar proper are at standard size, which would be 13 pt.

![snap](https://i.imgur.com/pOiZa9H.png)
