### ISSUE TITLE
Menu bar item should support actions (href, bash, refresh)

### ISSUE THREAD

**Issue by bilal-fazlani** [swiftbar/SwiftBar#110]
This is my example plugin  

```bash
#!/bin/bash

echo "hi | href=https://google.com"
```

In BitBar the behaviour is when I click on "hi", it opens the link. 
In SwiftBar, it doesn't.

Same of `bash` param.

`href` and `bash` both work only when they are in dropdown.

I think the BitBar behaviour is correct because it allows creating plugins which don't need a dropdown.

**Comment by melonamin** [comment]
Been mentioned here as well #101

**Comment by bilal-fazlani** [comment]
Ooops, sorry for the duplicate

**Comment by melonamin** [comment]
No worries, I needed an issue anyway.
