### ISSUE TITLE
Top level menu item vertical position (custom font size)

### ISSUE THREAD

**Issue by bilal-fazlani** [swiftbar/SwiftBar#111]
I have BitBar and SwiftBar both installed and running on my machine. I have one plugin installed.
Here is a screenshot

![image](https://user-images.githubusercontent.com/3396271/103155174-2206d500-47c3-11eb-83c5-fd2e75bb8f3f.png)

```bash
#!/bin/bash

echo "hi | href=https://google.com size=20"
```

The first "hi" is rendered by BitBar and 2nd one is Swiftbar

One is sticking to top and another one to bottom. Would it be better if it was vertically centered?

**Comment by bilal-fazlani** [comment]
Apologies.
Looks like this is also a duplicate of #85

**Comment by melonamin** [comment]
Are you in Catalina? It seems to work fine on Big Sur

**Comment by bilal-fazlani** [comment]
Yes catalina

**Comment by nickjvturner** [comment]
Would it be possible to add a vertical adjustment parameter into SwiftBar?

**Comment by bilal-fazlani** [comment]
I think an automatic solution would be better rather than giving control to devs.

**Comment by melonamin** [comment]
>Would it be possible to add a vertical adjustment parameter into SwiftBar?

We've discussed it in #85 and decided that automatic is better. It was implemented in #90, but per @bilal-fazlani it doesn't  work on Catalina.

I didn't had a chance to check it myself yet.
