### ISSUE TITLE
SF Symbol not parsed when followed immediately by non-whitespace

### ISSUE THREAD

**Issue by zkarj735** [swiftbar/SwiftBar#116]
In BitBar the output `:battery:100%` would render the battery emoji followed by the text `100%`.

In SwiftBar the output `:battery.100:100%` renders only the same text `:battery.100:100%`.

Interposing a space as `:battery.100: 100%` renders the SF Symbol followed by the ` 100%` text. At least, I believe the space is rendered. It's a little hard to tell.

**Comment by melonamin** [comment]
>Interposing a space as :battery.100: 100% renders the SF Symbol followed by the 100% text.

Yes, this is exactly how it works. Current parsing is pretty naive and just splits the string by word using space.

**Comment by melonamin** [comment]
I've played a bit with it and from my point of view the current behavior and end result looks good. Space is in its place, leaving it out will lead to a worse result.

So based on that I don't want to invest my time into implementing this at this time, but I'll welcome a pull request.
