### ISSUE TITLE
Emoize by default

### ISSUE THREAD

**Issue by matopeto** [swiftbar/SwiftBar#117]
With bitbar is emoize true by default, but swiftbar (1.1.1 (195) do not emoize in my plugin

Wrong behaviour: 

See screenshot:

![image](https://user-images.githubusercontent.com/2447996/103284876-c31ca800-49dc-11eb-98c8-797cc8f8f7bd.png)

Expected behaviour: 

`:heavy_check_mark:` sould be emoized

**Comment by yanzhang0219** [comment]
See https://github.com/swiftbar/SwiftBar/discussions/113

**Comment by matopeto** [comment]
Ok, this is my plugin i can explicitly set symbolize to false, but for other plugins (not update) this is breaking change with bitbar, hm....

**Comment by melonamin** [comment]
Closing as duplicate #108

>Ok, this is my plugin i can explicitly set symbolize to false, but for other plugins (not update) this is breaking change with bitbar, hm....

On Catalina this will work as expected, on Big Sur and up SF Symbols are preferred, if a plugin developer wants to have emoji consistently between BitBar and SwiftBar - they should explicitly use emoji, not GitHub style shortcut.
