### ISSUE TITLE
General bug: invert font or icon in menu bar when selected

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#12]
Screenshot below:

Here it's just the SF Mono font (standard color black) in normal system mode ("light mode"). When selected, the menulet padding is colored, as it should be—in my case grey—, but the font should be inverted from black to white. (The same should be applied to icons: black to white when selected in "light" mode, and white to black when selected in system dark mode.)

![snap](https://i.imgur.com/czS53qY.png)

**Comment by melonamin** [comment]
Note looks like doesn't apply to Big Sur, only Catalina:

<img width="239" alt="SwiftBar Invert Colors" src="https://user-images.githubusercontent.com/222100/100104743-905b1f00-2e34-11eb-900c-c069a6305fd3.png">

**Comment by JayBrown** [comment]
This seems to be fixed now. Thank you.
