### ISSUE TITLE
Different behavior <> Bitbar

### ISSUE THREAD

**Issue by warmup72** [swiftbar/SwiftBar#120]
Thanks für swiftbar!
it's great to have a alternative to it.
Today Ive tried to use my old bitbar-plugins and yes they work!
But I find one think different!
I´ve a Log-Folder in my Plugin-Folder. Bitbar doesn´t browse this .... swiftbar browses all this folders and for every log I will get error-Plugin

**Comment by melonamin** [comment]
Hi there, 

Yes, this is by design, you can see the description here - https://github.com/swiftbar/SwiftBar#plugin-folder
