### ISSUE TITLE
Extra "(B[m" showing in menu title

### ISSUE THREAD

**Issue by lksoft** [swiftbar/SwiftBar#121]
Hello I am seeing this in all of my plugins (I use three, which all come from different language scripts).

<img width="336" alt="Screen Shot 2020-12-31 at 11 38 32" src="https://user-images.githubusercontent.com/133880/103406961-ea01e800-4b5c-11eb-8ee7-5e7222724623.png">

I don't believe that it is related to ansi colors, since I don't use them and for the middle plugin here is the text generated:

`:9.square.fill: | sfcolor=green ansi=false symbolize=true dropdown=false`

I checked to make sure I am not inserting anything else - that text is the output written to a file and checked in BBEdit for invisibles (there were none). As you can see the sf symbols is not being interpreted either because of the extra characters (I guess).

Forgot to mention, this is with the new version 1.2.0

Did a bit more testing: it turns out that I was using version 1.1.0 before. I tested 1.1.1, 1.2.0beta1, 1.2.0beta2 & 1.2.0 and they all do this without any changes to my scripts, but 1.1.0 does not.

I see this even with a single plugin installed (I used the one from the **Dev** section called **Xcode Version**)

**Comment by melonamin** [comment]
@jmjordan experienced the same in #94

Honestly, I forgot to dig deeper, but maybe it can give you a starting point.

**Comment by lksoft** [comment]
Yes, I had a very similar problem and it was solved by removing this line in my bash profile:

`export TERM=xterm-256color`

Hopefully this will help somebody else.

**Comment by jgclark** [comment]
Just wanted to leave a comment that I had this issue as well, and @lksoft's fix solved it for me as well.
Perhaps add a note next time you update the README?
