### ISSUE TITLE
SwiftBar doesn't ask for Calendar/Reminders permission when needed

### ISSUE THREAD

**Issue by mdbraber** [swiftbar/SwiftBar#127]
I'm using a custom plugin that uses `icalBuddy` to query my calendars. For this it needs calendar/reminders permissions. E.g. when running the plugin from iTerm it wil first pop up the permissions dialog. Unfortunately it doesn't work with SwiftBar. It worked in the previous (notarized) version of BitBar, but also not in the latest versions there. I'm guessing it has to do with whether or not it has been signed/notarized but not sure. Tried resetting permissions with `tccutil` but to no avail so far.

**Comment by mdbraber** [comment]
Looked around a bit and found this issue with Uebersicht mentioned here: https://github.com/felixhageloh/uebersicht/issues/383. I can't find the fix mentioned in 1.4.61 there, but I think it might have to do with a change in entitlements: https://github.com/felixhageloh/uebersicht/commit/63dc94c553a2737b518cdade7d51dde5b396401d

**Comment by mdbraber** [comment]
I've been able to fix this by implementing the entitlements for accessing the calendar and a "Privacy - Calendars Usage Description" in the Info tab for the Xcode project. Also this seems to be coinciding with a specific `icalBuddy` issue which has been fixed here: https://github.com/DavidKaluta/icalBuddy64/commit/e10ddf01143323cad642ed38e1c2f8de8041aadc

**Comment by melonamin** [comment]
> I've been able to fix this by implementing the entitlements for accessing the calendar and a "Privacy - Calendars Usage Description" in the Info tab for the Xcode project

Awesome! I was just about to write that this is what is missing. Do you mind creating a pull request for this?

**Comment by mdbraber** [comment]
Thanks for adding this @melonamin !
