### ISSUE TITLE
Nested symlinked directories not traversed

### ISSUE THREAD

**Issue by crcastle** [swiftbar/SwiftBar#129]
I have a symlinked directory inside my SwiftBar (er, bitbar) plugin directory. Inside that symlinked directory, I have a few bitbar plugins. SwiftBar doesn't see these plugins. Is that expected?

My use case is that I have a Mac for work and a personal Mac. Some plugins I want to use on both machines, some I only want to use on one of the machines. I want the shared ones to stay in sync when I edit them on either machine. My `/Users/crcastle/Synced/` folder is synchronized between the two machines using [Syncthing](https://syncthing.net).

This seems related to but not the exact same issue as #76.

```term
~
❯ defaults read com.ameba.SwiftBar
{
    HideSwiftBarIcon = 0;
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~/bitbar";
    NSNavPanelExpandedSizeForOpenMode = "{716, 400}";
    "NSStatusItem Preferred Position Item-0" = 450;
    "NSStatusItem Visible Item-0" = 1;
    "NSWindow Frame NSNavPanelAutosaveName" = "362 356 716 400 0 0 1440 875 ";
    "NSWindow Frame SUUpdateAlert" = "410 357 620 398 0 0 1440 875 ";
    PluginDirectory = "/Users/crcastle/bitbar";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-01-05 19:11:14 +0000";
    SUSendProfileInfo = 0;
}

~
❯ cd /Users/crcastle/bitbar

~/bitbar
❯ ls -la
total 520
drwxr-xr-x   4 crcastle  staff     128 Jan  5 14:22 ./
drwxr-xr-x+ 81 crcastle  staff    2592 Jan  5 13:59 ../
-rw-------   1 crcastle  staff  265089 Dec 10 19:48 .repository.json
lrwxr-xr-x   1 crcastle  staff      45 Jan  5 14:21 Shared Bitbar Plugins@ -> /Users/crcastle/Synced/Shared Bitbar Plugins/

~/bitbar
❯ ls -la "Shared Bitbar Plugins/"
total 32
drwxr-xr-x  5 crcastle  staff   160 Jan  5 14:22 ./
drwxr-xr-x  5 crcastle  staff   160 Jan  5 14:26 ../
-rwxr--r--@ 1 crcastle  staff   925 Dec 10 19:49 brew-updates.1h.sh*
-rwxr--r--  1 crcastle  staff  5852 Jan  5 00:22 cryptocurrencies.5m.sh*
-rwxr--r--@ 1 crcastle  staff  2092 Dec 10 19:51 pomodoro4.10s.pl*

~/bitbar
❯ open -a SwiftBar
```

Note that `/Users/crcastle/bitbar/Shared Bitbar Plugins` was created like this:

```term
ln -s /Users/crcastle/Synced/Shared\ Bitbar\ Plugins/ /Users/crcastle/bitbar/Shared\ Bitbar\ Plugins
```

![CleanShot 2021-01-05 at 14 32 53@2x](https://user-images.githubusercontent.com/275734/103690613-fcb45c80-4f62-11eb-8e90-f35d60772115.png)

![CleanShot 2021-01-05 at 14 28 27@2x](https://user-images.githubusercontent.com/275734/103690163-4d778580-4f62-11eb-85d9-11aee42d27db.png)

![CleanShot 2021-01-05 at 14 28 45@2x](https://user-images.githubusercontent.com/275734/103690181-5405fd00-4f62-11eb-92de-ccddd0e6d8a2.png)

![CleanShot 2021-01-05 at 14 29 02@2x](https://user-images.githubusercontent.com/275734/103690212-5ec09200-4f62-11eb-9fec-604ed02886ac.png)

Also, thanks for resurrecting BitBar. I was just thinking about how I might help resurrect it myself when I found SwiftBar.

**Comment by melonamin** [comment]
Perfect issue, thank you for taking the time.

You're right, nested symlinks are not supported and I didn't know about that, but it is right there in the API docs [enumerator(atPath:)](https://developer.apple.com/documentation/foundation/filemanager/1408726-enumerator)
 
> This method does not resolve symbolic links encountered in the traversal process, nor does it recurse through them if they point to a directory.

AFAIK there is no API to do what we need here, so hacked together a [quick&dirty fix](https://github.com/swiftbar/SwiftBar/commit/a4cadc03fe4cac3adae7a593f21ecb6823f45d73) which seems to be working. Let's hope I didn't break something... 🤞
