### ISSUE TITLE
Plug-In Repository Improvements

### ISSUE THREAD

**Issue by warmup72** [swiftbar/SwiftBar#130]
- [x] Search for plugins
- [ ] User favorites, i.e. star a plugin and a separate view for favorites
- [ ] Section for newly added plugins and "Staff Favorites"
- [ ] Uninstall plugin
- [x] PageUp PageDown to scroll the list

**Comment by melonamin** [comment]
I'm usually have a "designer's block" with this kind of things, so don't hesitate to share your design ideas, mockups or examples of other apps
