### ISSUE TITLE
Feature request: Refresh time in metadata

### ISSUE THREAD

**Issue by jasonsnell** [swiftbar/SwiftBar#131]
Would be nice (forgive me if this is already possible) to allow the refresh time to be embedded in metadata inside the plugins rather than the inelegant approach of embedding it in the filename? Obviously filename needs to be there for backward compatibility. But it would be nice to not require it. Also eventually refresh should probably be settable within the UI of the app.

**Comment by melonamin** [comment]
Hi Jason,

we have the [schedule tag](https://github.com/swiftbar/SwiftBar#refresh-schedule). If you’re not familiar with cron syntax you can use this handy [online tool](https://www.freeformatter.com/cron-expression-generator-quartz.html)

In addition to cron syntax I’m planning to add support for refresh time in the same format as in the file name.

> Also eventually refresh should probably be settable within the UI of the app.

This is in progress in #119

**Comment by jasonsnell** [comment]
Oh nice! Didn't realize that. Thank you.
