### ISSUE TITLE
SwiftBar should show "⚠️"  after streaming plugin has crashed

### ISSUE THREAD

**Issue by bilal-fazlani** [swiftbar/SwiftBar#132]
refer #118 for discussions

**Comment by melonamin** [comment]
Thanks, fixed.

**Comment by xilopaint** [comment]
> Thanks, fixed.

Is there a beta build with the fix?

**Comment by melonamin** [comment]
No, but I'm planning to release 1.2.2 this week

**Comment by xilopaint** [comment]
> No, but I'm planning to release 1.2.2 this week

Thanks!

**Comment by xilopaint** [comment]
Hey @melonamin, the "⚠️" emoji seems not to be properly centered.
