### ISSUE TITLE
UserKeyMapping in Menubar

### ISSUE THREAD

**Issue by wayneforrest** [swiftbar/SwiftBar#133]
I have the text "UserKeyMapping:(" showing in the menubar.
Using version Version 1.2.1 (237) installed using HomeBrew, using Big Sur.

Any Ideas how to fix this?

**Comment by wayneforrest** [comment]
I did some debugging, and the problem seems to originate from [ShellOut](https://github.com/JohnSundell/ShellOut)

Here is the partial value of the "s" variable:

`
UserKeyMapping:(\n        {\n        HIDKeyboardModifierMappingDst = 30064771300;\n        HIDKeyboardModifierMappingSrc = 30064771302;\n    }\n)\n
`

`
@discardableResult func runScript(to command: String,
                                  process: Process = Process(),
                                  onOutputUpdate: @escaping (String?) -> Void = { _ in },
                                  env: [String: String] = [:]) throws -> String
{
    let swiftbarEnv = systemEnvStr.merging(env) { current, _ in current }
    process.environment = swiftbarEnv.merging(ProcessInfo.processInfo.environment) { current, _ in current }
    let s = try shellOut(to: command, process: process, onOutputUpdate: onOutputUpdate)
    return s
}

`

**Comment by wayneforrest** [comment]
Problem resolved! 

The problem was within my `bash_profile` which called another shell script, to map keys, Right OPTION becomes CTRL if recall correct.

When I executed the PlugIn script from `zsh `as follows: `bash -c -l plugin_script_name`
it became clear why the text was sent back as part of the output from the plugin script.

**Comment by melonamin** [comment]
Glad you've figure it out, I thing I'll add a recommendation to README to test plugins with `bash -c -l plugin_script_name`
