### ISSUE TITLE
Terminal below menubar - Swiftbar not usable

### ISSUE THREAD

**Issue by warmup72** [swiftbar/SwiftBar#140]
Ihm using macOS 10.15.7 with swiftbar 1.2.1.

I noticed that when the menu of a Swiftbar script opens in an underling terminal window, it is no longer operable.
 When scrolling down the menu, the menu window closes after reaching the 2 or 3 entry.

Steps to reproduce:
1. Create a plugin with 3 or 4 action field entries
2. Open the terminal window and zoom it to screen size
3. Try to scroll down the menu items in the plugin

**Comment by melonamin** [comment]
Can you please attach a screen recording? I can't reproduce it based on your description.

**Comment by warmup72** [comment]
Sorry - I´ve found the problem.
I´ve used tinker tool to set "Application/Terminal/Focus Windows automatical on mouseover

If I didn't use this setting swift view works fine

**Comment by melonamin** [comment]
Glad you've figure it out!
