### ISSUE TITLE
How to handle Node.js script with `node_modules` folder in plugin folder?

### ISSUE THREAD

**Issue by crcastle** [swiftbar/SwiftBar#141]
I'm using a [google calendar bitbar plugin](https://github.com/kodie/bitbar-googlecal) written in Node. During its setup, it [runs `npm install`](https://github.com/kodie/bitbar-googlecal/blob/master/googlecal.30m.js#L143) which creates a `node_modules` folder beside it in the plugin directory. `node_modules` directories are notoriously large and deep. This one is 57MB and (looks to) max out at about 8 or 9 directories deep.

This seems to cause SwiftBar to repeatedly display the file selector dialog asking me to select the plugin directory. When I click Open, the same dialog is shown again. When I click Cancel, SwiftBar shows nothing in the menubar, but `ps` shows that the process is still running.

I'm guessing this is because SwiftBar is having problems (or gives up) traversing the `node_modules` folder. When I remove this plugin and the `node_modules` folder from the plugin folder, my other plugins show up in the menubar.

```term
~
❯ defaults read com.ameba.SwiftBar
{
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~/bitbar";
    NSNavPanelExpandedSizeForOpenMode = "{799, 448}";
    "NSStatusItem Preferred Position Item-1" = 1000;
    "NSStatusItem Preferred Position Item-2" = 1000;
    "NSStatusItem Preferred Position Item-3" = 1000;
    "NSStatusItem Preferred Position Item-4" = 1000;
    "NSStatusItem Preferred Position Item-5" = 1000;
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-6" = 0;
    "NSWindow Frame NSNavPanelAutosaveName" = "320 321 799 448 0 0 1440 877 ";
    PluginDirectory = "/Users/chris.castle/bitbar";
    SUHasLaunchedBefore = 1;
}

~
❯ cd /Users/chris.castle/bitbar

~/bitbar
❯ ls -la
total 200
drwxr-xr-x  10 chris.castle  staff    320 Jan 12 13:32 ./
drwxr-xr-x+ 96 chris.castle  staff   3072 Jan 12 13:24 ../
-rw-r--r--@  1 chris.castle  staff    432 Jan 12 13:16 .googlecal.json
-rw-r--r--@  1 chris.castle  staff      6 Jan 12 13:16 .ruby-version
lrwxr-xr-x   1 chris.castle  staff     48 Jan 12 13:13 Shared Bitbar Plugins@ -> /Users/chris.castle/Synced/Shared Bitbar Plugins
-rwxr--r--@  1 chris.castle  staff  11886 Jan 12 13:15 github_notifications.5m.py*
-rwxr--r--@  1 chris.castle  staff  36576 Jan 12 13:32 googlecal.30m.js*
-rwxr-xr-x@  1 chris.castle  staff   5005 Jan 12 13:14 heroku.1m.rb*
drwxr-xr-x@ 44 chris.castle  staff   1408 Jan 12 13:32 node_modules/
-rwxr-xr--@  1 chris.castle  staff  33990 Jan 12 13:14 trello_notifications.5m.sh*

~/bitbar
❯ open -a SwiftBar
```

https://user-images.githubusercontent.com/275734/104358574-a2744800-54dc-11eb-9394-9121846dc853.mp4

This is with v1.2.1

![CleanShot 2021-01-12 at 13 42 18@2x](https://user-images.githubusercontent.com/275734/104358202-195d1100-54dc-11eb-8dbc-8896daf87c7e.png)

**Comment by melonamin** [comment]
> This seems to cause SwiftBar to repeatedly display the file selector dialog asking me to select the plugin directory.

Yeah, this is a dumb protection mechanism(TM) working. SwiftBar supports subfolders and tries to load everything it finds, recursively going through the folder tree. Dumb protection mechanism sees that you have "too many files" and asks for another folder.

I see a couple ways to dress this issue:L]
* SwiftBar ignores hidden folders, so if you can make the plugin use hidden folder this might be an option
* I can add a preference to disallow SwiftBar go deeper than 1 level into the plugin folder.

**Comment by crcastle** [comment]
Oh, the hidden folder idea works!

I mistakenly thought a hidden folder had to begin with a `.`, but some googling led me to `chflags hidden node_modules`. That command will make `node_modules` hidden without prepending it with a `.`. Tested it, and SwiftBar's loading all my plugins now!

Thanks!
