### ISSUE TITLE
Refresh intervals in symlink names get ignored

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#142]
I have a plugin that's supposed to update once per minute. According to SwiftBar, it was “Updated 1 Hour Ago”. `htop` shows that the plugin is not currently running. This is not just the one plugin either, almost every plugin (most of which have update intervals between 30 seconds and 5 minutes) shows “Updated 1 Hour Ago”.

**Comment by melonamin** [comment]
Can you please provide more info:
* Can you reproduce this behavior?
* How long SwiftBar was running before this happened?
* Was you computer in a sleep mode before this happened?
* Anything else worth mentioning?

Console log would help as well.

**Comment by fenhl** [comment]
* I relaunched SwiftBar and it immediately happened again (after initially loading the plugins successfully).
* I don't know. Possibly less than 2 hours.
* No, but the behavior seems to persist through sleep mode.
* Not that I can think of.

How do I get a console log?

**Comment by fenhl** [comment]
I am currently running the following plugins:

* [bitbar-version](https://github.com/fenhl/bitbar-version)
* [bitbar-diskspace](https://github.com/fenhl/diskspace)
* [bitbar-mediawiki-watchlist](https://github.com/fenhl/bitbar-mediawiki-watchlist)
* [bitbar-twitch](https://github.com/fenhl/bitbar-twitch)
* [Wurstmineberg's bitbar-server-status](https://github.com/wurstmineberg/bitbar-server-status)
* [ambient](https://github.com/liclac/ambient)
* `volume.5s.py` and `discord.15s.py` from [my syncbin](https://github.com/fenhl/syncbin/tree/main/bitbar)
* a simple shell script as a placeholder for a plugin I need to fix
* and 5 closed-source plugins, 3 of which are written using the Rust [bitbar](https://crates.io/crates/bitbar) crate and the other 2 in Python.

Here's a log: [swiftbar.log](https://github.com/swiftbar/SwiftBar/files/5836543/swiftbar.log)

**Comment by melonamin** [comment]
> I relaunched SwiftBar and it immediately happened again (after initially loading the plugins successfully).

As per log you've attached plugins update successfully, can you capture a log when plugins are broken?

By the way, what happens if you force refresh plugins?

**Comment by melonamin** [comment]
Ok, this is a fun one, I think I know what is going wrong here.

I've decided to test [bitbar-twitch](https://github.com/fenhl/bitbar-twitch), this is from install instructions:

>Create a symlink to ~/.cargo/bin/bitbar-twitch into your BitBar plugin folder. Call it something like bitbar-twitch.1m.o, where 1m is the rate at which the list of streams will be refreshed.

And this is from log you provided:
>id: bitbar-twitch
type: Executable
name: bitbar-twitch
path: /Users/fenhl/.cargo/bin/bitbar-twitch

When loading plugins, SwiftBar follows symlinks (see #129), which in this case results in plugin named "bitbar-twitch", which is totally fine for the first run, but not OK if you want it to refresh automatically...

Maybe there is a way to support this, I'll need to look at the code closer. As a work around you can use binary metadata #105

**Comment by fenhl** [comment]
Perhaps the symlink's filename could be used in addition to the target's, to allow customizing the refresh rate while still letting Cargo handle the plugin installation. Obviously it would also help with BitBar compatibility.
