### ISSUE TITLE
Refresh is kinda sluggish via URL scheme 

### ISSUE THREAD

**Issue by yanzhang0219** [swiftbar/SwiftBar#145]
Hi,

I am not sure whether this is a bug or not. I use URL scheme to refresh my plugin like `open -g 'swiftbar://refreshplugin?name=xxx'` but I noticed that the refresh is delayed. Probably this is not caused by SwiftBar itself. I am just wondering whether SwiftBar has such a potential issue, i.e., refreshing may be delayed if using URL scheme? 

Thank you. 

Update:
This URL scheme is executed by another program, i.e., I use a shortcut to run a certain program, and this program will execute the URL scheme to refresh my plugin. Just now I disabled that program, and I tried to execute the URL scheme directly in the terminal. The delay was still there. After I press ENTER key to run the URL scheme in my terminal, it will take about 2 seconds to make the plugin being refreshed.

**Comment by melonamin** [comment]
There is no artificial delay in refresh through URL scheme, to debug you see logs in Console.app.

Line which starts with "Requesting manual refresh" is the result of refresh triggered through URL, you can test and see how it works on your end.

<img width="1008" alt="Screen Shot 2021-01-23 at 7 53 46 PM" src="https://user-images.githubusercontent.com/222100/105618406-b78e8800-5db4-11eb-81ef-bbc85f12928b.png">

**Comment by yanzhang0219** [comment]
Okay, I got it. Thank you. Probably the delay is caused by my script itself. I will try to test it more. Closing this for now.
