### ISSUE TITLE
SwiftBar dose not access my calendar using icalBuddy

### ISSUE THREAD

**Issue by dondoko-susumu** [swiftbar/SwiftBar#146]
I'm using a custom plugin that uses icalBuddy to query my calendars.
Unfortunately it doesn't work with SwiftBar.
![スクリーンショット 2021-01-24 8 53 44](https://user-images.githubusercontent.com/7107423/105617769-543c3e80-5e24-11eb-975b-72cac205745a.png)

It work well when run in terminal.
![Screen Shot 2021-01-24 at 9 00 40](https://user-images.githubusercontent.com/7107423/105617816-abdaaa00-5e24-11eb-9952-99f7ca71069e.png)

Permission settings
![Screen Shot 2021-01-24 at 8 57 58](https://user-images.githubusercontent.com/7107423/105617827-c745b500-5e24-11eb-8848-e7636ab99f1d.png)

Swift Bar: 1.2.1 (237)
Mac OS: 11.1 (Big Sur)

**Comment by melonamin** [comment]
Can you attach the plugin?

**Comment by dondoko-susumu** [comment]
Thanks for the reply.

upcoming.10m.sh

```
icalBuddy -b '' -ea -n -npn -nc -iep "title,datetime" -ps "| : |" -eed eventsToday
```

Preferences
![Screen Shot 2021-01-24 at 10 58 35](https://user-images.githubusercontent.com/7107423/105619172-5ce84100-5e33-11eb-8b7e-b038b0259816.png)

Plugin folder
![Screen Shot 2021-01-24 at 10 58 09](https://user-images.githubusercontent.com/7107423/105619228-b8b2ca00-5e33-11eb-8b7e-936c67889635.png)

**Comment by melonamin** [comment]
Thanks!

Ok, this is not an issue in SwiftBar, but in icalBuddy, specifically the version you're using. We actually discussed it [here](https://github.com/swiftbar/SwiftBar/issues/127#issuecomment-754022401)

I'm not sure where to get the official "fixed" version, but I've found a working build on[ Keyboard Maestro forum](https://forum.keyboardmaestro.com/t/icalbuddy-doesnt-work-within-keyboard-maestro-mojave-calendar-permissions/15446/6)

I hope it helps.

**Comment by dondoko-susumu** [comment]
Thanks! 

The following steps worked.
- Download the patched version from [forum](https://forum.keyboardmaestro.com/t/icalbuddy-doesnt-work-within-keyboard-maestro-mojave-calendar-permissions/15446/16)
- The executable file moved to /usr/local/bin/
- ↓ Modify permission

```
$ xattr -d com.apple.metadata:kMDItemWhereFroms icalBuddy
$ xattr -d com.apple.quarantine icalBuddy
```
