### ISSUE TITLE
Swiftbar not updating

### ISSUE THREAD

**Issue by mdbraber** [swiftbar/SwiftBar#147]
Sometimes (I think after opening my Macbook again after a night e.g.) SwiftBar doesn't update. It seems completely stuck as also "Refresh all" doesn't work. Only thing that seems to work is to quit and relaunch Swiftbar. Any ideas how to diagnose this?

**Comment by melonamin** [comment]
Do you have a reliable way to reproduce it?

At this moment I don't think we have enough details in logs to debug this kind of thing, I'll add more loggings points in the next update and we can start from there.

It sound to me like a thread pool exhaustion, but I'm not sure why it happens and how it relates to sleep\wake cycle on macbook

**Comment by mdbraber** [comment]
I'll take  a look if I can reliably reproduce it - haven't found a pattern yet. Any places I can look at current debugging output currently or do I have to wait for the next update?

**Comment by melonamin** [comment]
Go to Console.app, filter by process name Swiftbar and you'll see the logs. Each plugin refresh should generate a line in log, including manual refresh.

**Comment by kossmoboleat** [comment]
I've seen this also today and I'll try to check for logs too.

**Comment by fenhl** [comment]
I had this issue as well today, and after a manual refresh, Console is showing messages like this one:

```
Failed to schedule refresh of script
/Users/fenhl/.local/share/bitbar/plugins-default/07-mediawiki-watchlist.30s.o
(null). Execution queue is full!
```

There was a single plugin that was still running due to #163. After killing it and manually refreshing again, plugins are updating normally again.

**Comment by phaistonian** [comment]
It seems to me that this is the case when you put the system to sleep — or if somehow processes got stuck in ..limbo.

I had the same issue in the past with Bitbar and I ended up crafting a keyboard shortcut to restart Bitbar.

I did the same with Swiftbar and, of course, it works.

My guess is that a simple solution would have been to _kill_ processes running for, say, more than a couple of minutes.

**Comment by melonamin** [comment]
> I had this issue as well today, and after a manual refresh, Console is showing messages like this one

This is actually great, now I have a confirmation of what happens.

> It seems to me that this is the case when you put the system to sleep — or if somehow processes got stuck in ..limbo.

This is a good theory, I was under impression that the system should handle it... I'm adding some hooks to handle this in the next build

**Comment by melonamin** [comment]
If you have time, play with the [beta](https://github.com/swiftbar/SwiftBar/releases/tag/v1.2.3) please

**Comment by phaistonian** [comment]
This is what I get on Air (M1) — the beta won't start.

`
Feb 12 09:02:57 dhcp com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.ameba.SwiftBar.7171304.7171316(501)> [30403]
Feb 12 09:02:57 dhcp com.apple.xpc.launchd[1] (application.com.ameba.SwiftBar.7171304.7171316[42660]): Service exited due to SIGBUS | sent by exc handler[42660]
`

**Comment by kossmoboleat** [comment]
For me it works on my Intel MBPro, on a quick sleep/wakeup the plugins show updated information 😀. I'll report back after using it more.

**Comment by melonamin** [comment]
> This is what I get on Air (M1) — the beta won't start.

@phaistonian works on my M1, [quick googling](https://www.google.com/search?q=can%27t+start+an+app+Coalition+Cache+Hit&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari) suggests that this is somewhat widespread issue for different apps on BigSur. I couldn’t find a quick fix thou... 🤔

**Comment by phaistonian** [comment]
@melonamin  what's sort of strange is that the stable version works just fine.

Perhaps when you push it to be the stable version it will work just fine ;)

**Comment by melonamin** [comment]
I agree, it is strange. Anything different about how you launching Beta vs Release version? Maybe you have Beta in Downloads folder or smth like that. I’m just trying to guess.

My concern is that there is nothing different in how Beta version is build and packaged vs Stable one

**Comment by phaistonian** [comment]
Nope. Downloaded it and replaced the app in Applications.

Tried launching it a number of times, failed all those.

Downloaded the stable ones, replace the beta, worked like charm.

Perhaps some kind of signature issue?

**Comment by melonamin** [comment]
Try the [latest build](https://github.com/swiftbar/SwiftBar/releases/tag/1.2.3-beta-2) please

**Comment by phaistonian** [comment]
@melonamin  worked :)
