### ISSUE TITLE
Feature request: Support two-lines title

### ISSUE THREAD

**Issue by minamotorin** [swiftbar/SwiftBar#149]
Some application menu is too long and hide items in the menubar. I want to make the output more compact with the feature such as following:

```sh
echo "This is first line of menu title"
echo "This is second line of menu title | multiple=true"
echo "---"
```

I found [this article](https://stackoverflow.com/questions/41189763/how-to-show-two-row-of-text-in-a-menu-bar-app-in-mac-os) may help with implementation.

**Comment by melonamin** [comment]
We already have a poor man's support for two-lines title, I've added description to [README](https://github.com/swiftbar/SwiftBar#two-lines-title) 

Example:
```bash
echo "Line 1 \\n Line2 | size=8"
```

It looks OK on Catalina, but on Big Sur line spacing is all wrong and I don't know how to fix it

**Comment by minamotorin** [comment]
Great! Thank you for description! It work for me (Catalina). But I think gap between lines is too big and lines will be cut off with large size letters (small size is hard to see). This is a picture of image:

![sample](https://user-images.githubusercontent.com/76122224/106543908-8de50780-64fe-11eb-9744-2693396aaf4b.jpeg)

Right item (good example) is [MenuMeters](https://github.com/yujitach/MenuMeters).

Source code of center one:
```sh
#!/usr/bin/env sh
echo 'Line \\n Line2 \\n Line2 | size=6'
echo '---'
```

Source code of leftt one:
```sh
#!/usr/bin/env sh
echo 'Line \\n Line2 | size=11'
echo '---'
```

**Comment by melonamin** [comment]
Yeah, this is what I'm talking about. I'm either have to figure out how to make the line spacing smaller or switch to a custom view like the apps you showcase as an example

**Comment by rarango9** [comment]
So throwing something like this into the atributedTitle function in MenuBarItem.swift ~L:533 

```swift
var lineHeight = fontSize
if title.contains("\n") {
    lineHeight = fontSize * 3
}

let offset = CGFloat((13 - lineHeight) / 4.5)
```

Gives me something like this in Big Sur

![image](https://user-images.githubusercontent.com/732882/135692562-9579f096-7be6-429c-bf78-24ac8f7d87a4.png)

**Comment by ericboehs** [comment]
I would love to see this supported.

Currently this code:

```bash
echo "$PING_MS ms\\n$LOSS_PERCENT%"
```

yields an incorrect line height.

![Screenshot 2024-01-08 at 12 27 19@2x](https://github.com/swiftbar/SwiftBar/assets/28198/eee69019-bd60-4e64-820e-ed1fbb125fdb)

Even if I set the size smaller it just seems to top align instead of vertically centering.
