### ISSUE TITLE
Plugin Repo Never Loads

### ISSUE THREAD

**Issue by krubenok** [swiftbar/SwiftBar#15]
When trying to browse available plugins, Swiftbar stays stuck on "Refreshing repository data..."
<img width="512" alt="image" src="https://user-images.githubusercontent.com/2529120/100158026-66b7ed00-2e60-11eb-8f69-b5f303613171.png">

*Systems Details:*
- Intel CPU
- macOS Big Sur 11.1 Beta
- SwiftBar 1.0.1

**Comment by melonamin** [comment]
Can you please attach logs from Console.app?

- Open Console.app
- Press Start
- Filter by Process == SwiftBar
- Open Plugin Repository
- Export collected logs

**Comment by krubenok** [comment]
```
default	15:02:48.973181-0800	SwiftBar	SetFrontProcess: asn=0x0-0x8b58b5 options=1
```

**Comment by krubenok** [comment]
On a related note, when the Plugin Repository loading window is open, clicking get Plugins in the Menu Bar spawns a second window, expected behavior would be to bring the existing window in focus.

**Comment by melonamin** [comment]
This does't look right, make sure you are not blocking internet connection for SwiftBar, on a first launch repository data is downloaded from GitHub. And logs should look more like this:

![SwiftBar Plugin Repository](https://user-images.githubusercontent.com/222100/100163964-d8a22d80-2e84-11eb-8384-9617f741162d.gif)

**Comment by krubenok** [comment]
Then we've got something weird going on... 

Based on a quick glance at the underlying code for the Repository view, curling `https://raw.githubusercontent.com/swiftbar/swiftbar-plugins/main/repository.json` should get me the list of plugins to show in the UI. 

Running this in my terminal gets me that json as expected. I've disabled all AdBlockers, Proxies and everything else I can think of that might affect SwiftBar's ability to connect to Github and still no dice. FWIW, other Apps are able to connect to Github without issue, including the Github Desktop app I used to clone the project.

**Comment by krubenok** [comment]
Aha! Figured it out with a little debugging in Xcode. If I haven't yet set a Plugins folder, it will never load the repository since it has no place to put the json file and fails silently. Going to try my hand at opening a PR to address this now.
