### ISSUE TITLE
Some plugins not showing from BitBar repository?

### ISSUE THREAD

**Issue by jgclark** [swiftbar/SwiftBar#152]
I've now checked as thoroughly as I can (without #150), and I don't think the plugins in the sub-directory under `Lifestyle` called `ToDo` (https://github.com/matryer/bitbar-plugins/tree/master/Lifestyle/ToDo) are showing up in the Plugin Directory. I noticed this because I authored one of them, [NotePlan3.15m.rb](https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/ToDo/NotePlan3.15m.rb).

**Comment by melonamin** [comment]
Please refer [here](https://github.com/swiftbar/swiftbar-plugins/issues/1)

**Comment by jgclark** [comment]
Thanks. I will try to raise a suitable PR for you.
Note: I can't find that link, or the details in contains, in the README here.

**Comment by melonamin** [comment]
Fair, I've added a note to README https://github.com/swiftbar/SwiftBar/commit/81291933e9e46f3bb5ed1337c228194e1bddb9a2
