### ISSUE TITLE
[Request] Make shortcuts appear on menu items

### ISSUE THREAD

**Issue by xilopaint** [swiftbar/SwiftBar#154]
Would it be possible to make the shortcuts added with the SwiftBar syntax to be displayed on the menu items?

Also, please, change back the example value in README from the fancy <kbd style="font-size:medium"><kbd style="font-size:medium">⌘</kbd>+<kbd style="font-size:medium">⌥</kbd>+<kbd style="font-size:medium">T</kbd></kbd> to `CMD+OPT+T`. It's more clear and enables people to know that they need to use `OPT` instead of `OPTION` and `CMD` instead of `COMMAND` or anything else.

**Comment by melonamin** [comment]
> Would it be possible to make the shortcuts added with the SwiftBar syntax to be displayed on the menu items?

Do you have a good example of this?

>Also, please, change back the example value in README from the fancy <kbd style="font-size:medium"><kbd style="font-size:medium">⌘</kbd>+<kbd style="font-size:medium">⌥</kbd>+<kbd style="font-size:medium">T</kbd></kbd> to `CMD+OPT+T`

Yes, thank you, honestly I just missed this change in one of the pull requests

**Comment by xilopaint** [comment]
> Do you have a good example of this?

I mean this:

![Screen Shot 2021-02-01 at 01 04 04](https://user-images.githubusercontent.com/11052366/106414015-53aa3600-642a-11eb-8007-16ba9f93c73a.png)

**Comment by melonamin** [comment]
Ok, got it.

We can add this, but behavior will be a little bit off. When you set `shortcut=` it is global, meaning you can trigger it from anywhere in the system. But it will not work when you have the menu bar menu open which is quite bad.

I'll see if I can hack around it.

**Comment by xilopaint** [comment]
Hey @melonamin. There's a typo in README ("conttent") and the sentence lacks the period:

`If you want to add\remove plugin or have other questions about repository conttent please refer to this issue`
