### ISSUE TITLE
Bug: Inconsistent menu title colour when using 'reduce transparency' on Big Sur

### ISSUE THREAD

**Issue by samnunn** [swiftbar/SwiftBar#156]
Hi All.

Wow, my first proper bug report! Here goes…

---

**Summary**
The menu title colour switches from black to white when a SwiftBar menu is opened while using the 'Reduce Transparency' accessibility feature in Big Sur.

**Steps to Reproduce**
Click on the menu title of a SwiftBar plugin on a Mac with this configuration…
- Running macOS Big Sur (tested on 11.1)
- 'Reduce Transparency' enabled under System Preferences > Accessibility > Display > Reduce Transparency
- Dark mode turned off

**Expected Behaviour**
Menu title colour will remain black against the white background of the menu bar.

**Actual Behaviour**
Menu title colour turns white against the white background, and returns to black when the menu is deselected. See [attached screenshot](https://user-images.githubusercontent.com/2610191/106567842-6aa57100-656d-11eb-8fe8-222a5ba82209.png).

**Notes**
Expected behaviour is restored by switching to dark mode, or by turning off 'Reduce Transparency'.

---

This is a delightful project. Many thanks to everyone who has contributed for their great work.

Sam

**Comment by melonamin** [comment]
Hi @samnunn,

> Wow, my first proper bug report!

I wish every issue was formatted as good as yours, it is a blessing for any OSS maintainer. Thanks!
