### ISSUE TITLE
Add support for a slider

### ISSUE THREAD

**Issue by galak** [swiftbar/SwiftBar#158]
Would be nice if there was a way to specify a slider something similar to what one gets with the sound slider in the menu bar.

**Comment by melonamin** [comment]
I’m wary about adding interactive elements:
- Swiftbar is stateless and can’t communicate value changes back to script
- Currently we’re not creating custom UI, only using a built-in Image, Text and Checkmark. Adding custom UI significantly increases the support burden, so we need a good reason

Can you share a couple of examples of how you’d like to use it?

**Comment by galak** [comment]
The case I had was to write a script that could control a dimmable light or fan speed.  So the script could report a value for the slide as something like 'x' out of 100.  Than based if the user adjusted the slider figured the script could get a param set with the slider value.

**Comment by melonamin** [comment]
I'm closing this:
* no interest from other SwiftBar users
* I couldn't figure a clean way to implement it
