### ISSUE TITLE
SwiftBar does not reveal if pointer-tip is at very top of menu bar

### ISSUE THREAD

**Issue by tjluoma** [swiftbar/SwiftBar#159]
If I put my mouse pointer to the top of the menu bar and click, SwiftBar flickers but does not show me the dropdown.

This is unlike other apps that respond to the top-clicks just fine.

I took a little screencast to show what I am describing. You can see it below. There are two SwiftBar menu bar items and the rest are “regular” menu bar apps.

```
/Applications/SwiftBar.app:
	CFBundleShortVersionString: 1.2.2
	CFBundleVersion: 252
```

https://user-images.githubusercontent.com/26965/106945172-7b80ee80-66f5-11eb-8a3d-b430a91ef97c.mp4

**Comment by melonamin** [comment]
Hi @tjluoma, can you check #128 and see if it’s the same? i.e. click vs tap?

**Comment by tjluoma** [comment]
Wow, you're right. If you had asked me, I would have 100% said that I was tapping, not actually clicking, but I would have been 100% wrong. It works with tap, does not work with click.

Closing as duplicate.
