### ISSUE TITLE
Option to not run plugins in bash

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#163]
It appears that each time a plugin is refreshed (whether automatically or manually), SwiftBar spawns a full `bash` session that runs all of my shell startup scripts. Skipping bash and instead running the plugin directly would be more reasonable.

**Comment by melonamin** [comment]
Can you please elaborate what you suggest?

At this moment for each plugin run we spawn `/bin/bash -l -c` and than run the plugin code inside it. 

We need plugin runtime to be exactly the same as the "Run In Terminal" action, which means:
- we need user defined env
- we need to be able to   set custom Swiftbar env

**Comment by fenhl** [comment]
> We need plugin runtime to be exactly the same as the "Run In Terminal" action

> we need user defined env

Why is this a goal?

> we need to be able to set custom Swiftbar env

This can be done without spawning a shell.

**Comment by melonamin** [comment]
> Why is this a goal?

Because most people write and debug their scripts in Terminal, and then don't understand why plugin doesn't work in Swiftbar, just browse around issues in this repository or in BitBar. 

> This can be done without spawning a shell.

Tell me how.

**Comment by fenhl** [comment]
Perhaps there could be a plugin metadata field for disabling the bash wrapper. A sort of “no, really, my plugin doesn't need the shell env” toggle.

I don't know Swift, but I'd be surprised if it weren't possible. Languages I do know (Python, Rust, Zsh) let you override the environment for a subprocess.

**Comment by fenhl** [comment]
A quick search gave me <https://developer.apple.com/documentation/foundation/process/1409412-environment>.

**Comment by melonamin** [comment]
> Perhaps there could be a plugin metadata field for disabling the bash wrapper. A sort of “no, really, my plugin doesn't need the shell env” toggle.

We can do that

**Comment by melonamin** [comment]
Added two toggles:
- Global `defaults write com.ameba.SwiftBar DisableBashWrapper -bool YES`
- On plugin basis `<swiftbar.runInBash>false</swiftbar.runInBash>`

**Comment by bilal-fazlani** [comment]
Hi,
Which one takes precedence?

**Comment by melonamin** [comment]
Global one
