### ISSUE TITLE
Choose plugin folder dialog keeps popping up indefinitely after selecting plugins folder

### ISSUE THREAD

**Issue by Cygnusfear** [swiftbar/SwiftBar#165]
Super happy to discover swiftbar due to Bitbar issues with Big Sur, so hoping to switch from bitbar to swiftbar. Annoyingly, when selecting my old plugin folder the 'choose plugin folder' dialog keeps popping up. 

I'm working with javascript based plugins. My setup with bitbar was to symlink my node_modules and other folders to avoid Bitbar from attempting to run scripts in them.

As far as I understand Swiftbar runs all scripts in subfolders as plugins and it seems that adding a symlinked folder causes the 'choose plugin folder' dialog to repeatedly pop up. Copying my node_modules without ended up also popping up the dialog, I suppose due to symlinks all the way down.

Expecter behaviour would be for Swiftbar to ignore symlinked folders as Bitbar did and for the dialog to just work.

Cheers, very happy to have discovered swiftbar!

**Comment by melonamin** [comment]
Hi Alexander!

> Expecter behaviour would be for Swiftbar to ignore symlinked folders as Bitbar did and for the dialog to just work.

This is a feature, not a bug (TM). 😇

Please take a look at [this](https://github.com/swiftbar/SwiftBar/issues/141#issuecomment-759092357), we already discussed how to deal with node_modules

**Comment by Cygnusfear** [comment]
Thanks for the quick response 😊

Having read the other issue, I understand. From a UX point of view: popping a dialog back up without a warning message is terrible for a user because there is no feedback as to what is wrong. A little warning dialog would help.

In terms of recursion, if the consideration for allowing subfolders has to do with plugins, then a default depth of 1 folder might make sense. Which means the fix would be putting your scripts into a subfolder and the node_modules inside it.

The new warning dialog could even explain this beautiful solution, imagine that.

Alternatively a .swiftbarignore file 🤣

**Comment by melonamin** [comment]
Oh, I'm not arguing that the current UX is terrible, it is just a quick hotfix until I or someone else finds time to make it better
