### ISSUE TITLE
Parsing subsecond values from filename such as 5e-1s

### ISSUE THREAD

**Issue by Cygnusfear** [swiftbar/SwiftBar#166]
Bitbar didn't 'officially' (in `.XXXs.` naming) support subsecond refreshes, but these are incredibly useful for realtime monitoring. The workaround was to have `file.5e-1s.js` filenames which would make it correctly parse it as subsecond values. Perhaps it's possible to do similar evaluation?

**Comment by melonamin** [comment]
I would rather add `ms` for millisecond, don' you think it would be nicer?

**Comment by Cygnusfear** [comment]
Sure thing, sgtm 😊

**Comment by Cygnusfear** [comment]
Awesome! Thanks a great deal for this 🥳
