### ISSUE TITLE
terminal=false won't execute script in latest betas

### ISSUE THREAD

**Issue by phaistonian** [swiftbar/SwiftBar#170]
Well, the issue title pretty much tells the story:)

It works fine on the stable release, btw.

**Comment by xilopaint** [comment]
The script is executed, the issue is related to the bash parameters not being passed as described in this comment: https://github.com/swiftbar/SwiftBar/issues/161#issuecomment-778649467

**Comment by phaistonian** [comment]
@xilopaint Actually, the latest beta I tried did pass the parameters so that's not the issue.

Removing the `terminal=false` enabled running the command.

**Comment by xilopaint** [comment]
```python3
#!/usr/bin/env python3
import os
import sys

print('test')
print('---')
print(f"play | refresh=true terminal=false bash=\'{__file__}\' param0=arg")

if 'arg' not in sys.argv:
    os.system('afplay /System/Library/Sounds/Frog.aiff')
```

This plugin plays a sound on item click, but the condition to play the sound is that the parameter `arg` is not passed. You will hear the sound twice, the first on the normal execution of the script and the second on the execution of the bash command that reruns the same script.

**Comment by xilopaint** [comment]
```python3
#!/usr/bin/env python3
import os
import sys

print('test')
print('---')
print(f"play | refresh=true terminal=false bash=\'{__file__}\' param0=arg")

if 'arg' not in sys.argv:
    os.system('afplay /System/Library/Sounds/Frog.aiff')
```
This plugin with terminal=false plays a sound on item click, but the condition to play the sound is that the parameter arg is not passed. You will hear the sound twice, the first on the normal execution of the script and the second on the execution of the bash command that reruns the same script.

**Comment by xilopaint** [comment]
Now I see that if I add the new metadata `<swiftbar.runInBash>false</swiftbar.runInBash>` my plugin back to work. This new behavior is confusing to me. Is this expected @melonamin? A lot of plugins will broke if we have to add this new metadata.

**Comment by xilopaint** [comment]
Now I see that if I add the new metadata `<swiftbar.runInBash>false</swiftbar.runInBash>` my plugin back to work and the parameters are properly passed. This new behavior is confusing to me. Is this expected @melonamin? A lot of plugins will break if we have to add this new metadata.

**Comment by xilopaint** [comment]
Hey @melonamin, considering that my script works in v1.2.3 beta 2 with `<swiftbar.runInBash>false</swiftbar.runInBash>` is 8ccfc86b5687ef303ad62735b32a273acb294f55 added to beta 3 an unnecessary commit?

**Comment by melonamin** [comment]
Hey, can you please check this build? It works on my end. [SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/5983508/SwiftBar.app.zip)

@xilopaint [this test](https://github.com/swiftbar/SwiftBar/issues/170#issuecomment-779038096) is good if you remove `refresh=true`

**Comment by xilopaint** [comment]
> Hey, can you please check this build? It works on my end. [SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/5983508/SwiftBar.app.zip)

This build has fixed the issue with the missing parameters to me and I don't need to use <swiftbar.runInBash>false</swiftbar.runInBash> anymore. Thanks!

**Comment by xilopaint** [comment]
> Hey, can you please check this build? It works on my end. [SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/5983508/SwiftBar.app.zip)

This build has fixed the issue with the missing parameters to me and I don't need to use `<swiftbar.runInBash>false</swiftbar.runInBash>` anymore. Thanks!
