### ISSUE TITLE
ENV variables not passed to plugins when "Run in Terminal" is used with Fish Shell

### ISSUE THREAD

**Issue by bilal-fazlani** [swiftbar/SwiftBar#171]
this is my scala code

```scala
  val appMenu = menu("my-plugin") {
    sys.env.get("SWIFTBAR") match {
        case None => text("SWIFTBAR env value not found")
        case Some(v) => text(s"SWIFTBAR env = $v")
    }
  }
```

It will print "SWIFTBAR env = 1" when it being run via swiftbar and "SWIFTBAR env value not found" when it's not.

It seems to work correctly when swiftbar calls it

![image](https://user-images.githubusercontent.com/3396271/108622390-80b49c00-745e-11eb-9e56-4bae4df95ed5.png)

When I click on Run in Terminal, I see the following result.

![image](https://user-images.githubusercontent.com/3396271/108622441-e0ab4280-745e-11eb-9502-fed172428c17.png)

Setting different values in `# <swiftbar.runInBash>false</swiftbar.runInBash>` has not helped.

Not sure what is the issue.

Is it because I am using "iterm" with Fish shell?

I am using Swiftbar latest beta version 1.2.3 (271)

**Comment by bilal-fazlani** [comment]
When I use bash explicitly, in the swiftbar generated command, I get the env variable

![image](https://user-images.githubusercontent.com/3396271/108623396-e7d54f00-7464-11eb-955d-191b02f74706.png)

**Comment by bilal-fazlani** [comment]
Also, when I use the `env` syntax of Fish Shell, I get the env variable without wrapping everything in bash

![image](https://user-images.githubusercontent.com/3396271/108623634-f8d29000-7465-11eb-82d8-528c3c2d23a9.png)

**Comment by bilal-fazlani** [comment]
I did some more exploring I found that this is not limited to compiled plugins but only specific to fish shell.

The same problem happens with a script plugin as well


```bash
#!/bin/bash

echo "script-plugin
---
SWIFTBAR env=$SWIFTBAR"
```

![Uploading image.png…]()

**Comment by melonamin** [comment]
Great write up, thanks.

Fish shell doesn't support `export` command, they have `set -x` instead. I don't think it is reasonable to support this on SwiftBar side, but I think you should be able to easily fix it on your end with an alias? i.e. `alias export = "set -x"` or something like that

**Comment by bilal-fazlani** [comment]
> I don't think it is reasonable to support this on SwiftBar side

Ok 

> but I think you should be able to easily fix it on your end with an alias

Alias will probably not help. `set -x SWIFTBAR '1'` does not require an equals sign.

`export  -x SWIFTBAR='1'`  does require that.

I can manually edit the command from the fish history though.

**Comment by melonamin** [comment]
Found [this](https://github.com/edc/bass) after some Googling, maybe `alias export = “bass export”`?

**Comment by melonamin** [comment]
@bilal-fazlani do you think I can do anything else for you here or can we close this?

**Comment by bilal-fazlani** [comment]
This can be closed 🙂

**Comment by bilal-fazlani** [comment]
Thanks for the reference to bass. That helps a lot 👍
