### ISSUE TITLE
ANSI no white/black color

### ISSUE THREAD

**Issue by tsurezuregusa** [swiftbar/SwiftBar#172]
First, thank you for making this! I have found it just today. It is wonderful!

Running the BitBar ANSI test script:

https://github.com/matryer/bitbar-plugins/blob/master/Tutorial/ansi.sh

There are some differences. Maybe BitBar is not correct either, but many combinations are not readable in SwiftBar.

- `37m` is not white
- `30m` is not black
- in dark mode maybe `40m` should be white
- no bold; same as regular #168 (in BitBar bold colors are different; hard to see in dark)

BitBar
![bitbar](https://user-images.githubusercontent.com/589440/108790597-04f94300-7575-11eb-8eb7-72e1b2aea8f4.png)
SwiftBar
![swiftbar](https://user-images.githubusercontent.com/589440/108790599-06c30680-7575-11eb-8533-53ac33a3ef1d.png)

BitBar
![bitbar-](https://user-images.githubusercontent.com/589440/108790876-a8e2ee80-7575-11eb-9336-21be858d7257.png)
SwiftBar
![swiftbar-](https://user-images.githubusercontent.com/589440/108790884-af716600-7575-11eb-98e4-f5c4b8721728.png)

Also, maybe reset should use `color=` setting?

**Comment by melonamin** [comment]
> 37m is not white

it should be gray, fixed

>30m is not black

It is black. It looks a little weird in dark mode due to transparency

> in dark mode maybe 40m should be white

I don't think that adaptive colors is a good idea for ANSI colors, at least not by default

> no bold; same as regular #168 (in BitBar bold colors are different; hard to see in dark)

Thanks, you're right.

In general I've tried to follow [this](https://misc.flogisoft.com/bash/tip_colors_and_formatting#colors) and mapped colors to standard macOS colors. Maybe  it is better to map codes to hex color codes, if you have a mapping I can do it.

**Comment by tsurezuregusa** [comment]
Thank you for the response.

Why is ANSI `37m` not white if `color=white ansi=false` is white with no transparency? I understand if `39m` is gray with transparency, but white should be white. As you wrote, adaptive colors is not a good default. To me, it seems intuitive for ANSI colors to match `color=` setting. So `31m` is same as `color=red`.

If transparency makes `30m` look not black, then transparency is a problem. It is not intuitive. Normal menus for selection indicate no selection with transparency, but I think we use these menus for display. This is strange in OS menus also, like in Time Machine menu, latest backup time is gray and hard to read because there is no selection.

So maybe `transparency=false` is good to have. I think it is a problem for images also. `refresh=true` removes transparency but highlight color for selection is not necessary only for display.

With `\033[30m | color=red ansi=true` changing the default color maybe is confusing even if it is intuitive. Instead maybe a setting like `colors=white,red,green,`... could be added to change all ANSI default colors?

**Comment by melonamin** [comment]
I slightly modified the test plugin, by adding `refresh=true` which makes the item active(not dimmed), looks better(?)...

```bash
#!/bin/bash

echo -e "\033[34mA\033[32mN\033[31mS\033[33mI\033[0m | ansi=true"
echo "---"

T='gYw'   # The test text
echo -e "                 40m     41m     42m     43m\
     44m     45m     46m     47m | ansi=true font=courier trim=false";

for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
           '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
           '  36m' '1;36m' '  37m' '1;37m';
  do FG=${FGs// /}
  echo -en " $FGs \033[$FG  $T  "
  for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
    do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
  done
  echo " | ansi=true font=courier trim=false refresh=true";
done
echo "---"
echo "Open color codes in browser… | href=http://misc.flogisoft.com/bash/tip_colors_and_formatting#colors"
echo "Refresh | refresh=true"

```
<img width="632" alt="CleanShot 2021-12-18 at 14 25 11@2x" src="https://user-images.githubusercontent.com/222100/146653405-4706b997-d40a-4d66-9691-53e5428bc440.png">
<img width="635" alt="CleanShot 2021-12-18 at 14 24 59@2x" src="https://user-images.githubusercontent.com/222100/146653408-27c80ee6-d6ff-4a05-96bb-f0f0d66c085f.png">
