### ISSUE TITLE
[Request] Do not ignore leading space

### ISSUE THREAD

**Issue by tsurezuregusa** [swiftbar/SwiftBar#173]
I like to be able to align text nicely with monospaced font.

BitBar also ignores leading space, but it would be nice to have it not ignore.

ASCII `20` and Unicode `U+00A0`, `U+2002` to `U+200B`, `U+202F`, `U+205F` ignored.

```print '         1'```
```print '10'```

I learn now that Github Markdown also ignores leading space after more than one!

**Comment by tsurezuregusa** [comment]
To work around, ANSI escape sequence is recognized as character so leading space is not ignored.

**Comment by melonamin** [comment]
Probably not a bug, but a feature :) Look at `trim` [parameter](https://github.com/swiftbar/SwiftBar#parameters) and see if it works for you

**Comment by tsurezuregusa** [comment]
Thank you! I did not know that was in BitBar too. But maybe it is good in the README to mark features that are not in BitBar, for people like me that cannot read carefully.
