### ISSUE TITLE
Cannot get a divider line in a submenu

### ISSUE THREAD

**Issue by bjinse** [swiftbar/SwiftBar#174]
In the menu I can create a divider line by outputting "---"
I am not sure how to create a divider in a submenu. 
I tried "-- ---" but that gives me 3 dashes in the submenu.
Is this a (known?) issue or should I output something else?

**Comment by melonamin** [comment]
> I tried "-- ---" but that gives me 3 dashes in the submenu.

Tre removing  the space, like this one:

``` bash
#!/bin/bash

echo "Menu"
echo -n "MS " ; TZ=":Europe/Moscow" date +'%l:%M %p'
echo "---"
echo "Other"
echo -n "--SF " ; TZ=":US/Pacific" date +'%l:%M %p'
echo "-----"
echo -n "--LN " ; TZ=":Europe/London" date +'%l:%M %p'
echo -n "HK " ; TZ="Asia/Hong_Kong" date +'%l:%M %p'
```

**Comment by bjinse** [comment]
Thanks, This works. In my memory, I had also tried that. But maybe I was wrong.
