### ISSUE TITLE
Bash plugins are showing .bashrc, etc output

### ISSUE THREAD

**Issue by kevinwaddle** [swiftbar/SwiftBar#176]
I have output in my .bashrc, .bash_profile, etc and these are showing up in the Menubar when SwiftBar runs them.

This was not the case with BitBar. How can I prevent these from being sourced, or suppressing their output in SwiftBar?

**Comment by melonamin** [comment]
This was discussed in #163 and here is [the solution](https://github.com/swiftbar/SwiftBar/issues/163#issuecomment-777872381)

Available in the next release.

**Comment by kevinwaddle** [comment]
Thank you. I had found that issue, and tried the global option, but I hadn't noticed it wasn't yet in the current release.
