### ISSUE TITLE
Mac App Store Version

### ISSUE THREAD

**Issue by melonamin** [swiftbar/SwiftBar#177]
- [x] Configure new Xcode build
   - [x] Exclude Sparkle binaries
   - [x] Add conditional compilation flag `MAC_APP_STORE`
   - [x] Enable Sandbox support
- [ ] Code adjustments
   - [x] Exclude Sparkle code
   - [ ] Change file access APIs to Bookmark based ones
   - [x] Exclude `DispatchSourceProtocol` APIs
- [ ] Metadata
   - [ ] Screenshots
   - [ ] Description

**Comment by melonamin** [comment]
Having problems with launching processes outside app sandbox, and [this doesn't look good](https://developer.apple.com/forums/thread/28336)

**Comment by melonamin** [comment]
Figured out most of it, have a version that is submittable to the App Store.
Current blocker - plugins downloaded from the Repository marked with `com.apple.quarantine` and can't be launched.

**Comment by xilopaint** [comment]
Is this still a goal?

**Comment by melonamin** [comment]
Someday, maybe. It’s still open for a reason

**Comment by dnicolson** [comment]
Is this maybe still a goal? `SwiftBar MAS` is still in the project as a target.

**Comment by melonamin** [comment]
@dnicolson any specific reason why you want a MAS version?

**Comment by dnicolson** [comment]
Not really, the MAS has its issues, but it can be convenient at times. I was just wondering why the target is still in the project and whether there are any roadblocks.

**Comment by melonamin** [comment]
> why the target is still in the project

Forgot to delete it; nothing more.

> whether there are any roadblocks

Sandboxing, which is required by MAS, will basically make running arbitrary binaries in plugins impossible or impractical. I was even considering limiting the MAS version only to the Shortcuts plugin, but ultimately decided that the support burden is not worth it.

My initial idea was to make MAS version payed, like I did it fro my other project [TRex](http://trex.ameba.co/)
