### ISSUE TITLE
Multiple SF Symbols with different colours

### ISSUE THREAD

**Issue by MaxGiting** [swiftbar/SwiftBar#180]
Firstly, thank you for this project! It's made a project I have been working on so much easier.

I have especially liked that I can use SF Symbols to make my script feel much more integrated with Macs.

Currently I output either
`:checkmark.circle.fill: |  sfcolor=green`
or 
`:cross.circle.fill: |  sfcolor=red`

I would like to be able to combine both the green and red icons as one output. I don't think this is currently possible so this is a feature request.

**Comment by melonamin** [comment]
> Firstly, thank you for this project! It's made a project I have been working on so much easier.

:) Thanks, always great to hear that you helped someone

> I would like to be able to combine both the green and red icons as one output. 

Just to double check - you want to have more than one **colored** SF Symbol in one menu item, right?

**Comment by MaxGiting** [comment]
Yes please. I would like to be able to have a green and a red SF Symbol at the same time.

**Comment by melonamin** [comment]
Available in [beta](https://github.com/swiftbar/SwiftBar/releases/tag/v1.3.0-beta-1) 

```bash
#!/bin/bash

echo "Test :house: :smoke:  :circle: :square: | sfcolor=red,blue sfcolor2=yellow,green sfcolor3=red,white sfcolor4=green,yellow"
echo "---"
echo "Test :circle: :square: | sfcolor=red"
```
