### ISSUE TITLE
Plugin Debug View

### ISSUE THREAD

**Issue by melonamin** [swiftbar/SwiftBar#182]
To enable Plugin Debug menu: `defaults write com.ameba.Swiftbar PluginDebugMode -bool YES`

![CleanShot 2021-03-27 at 14 36 27@2x](https://user-images.githubusercontent.com/222100/112730793-d242c180-8f09-11eb-9a20-17e2ca7578e0.png)

![CleanShot 2021-03-27 at 12 38 29@2x](https://user-images.githubusercontent.com/222100/112727546-593b6e00-8ef9-11eb-9458-b17ba67f75e0.png)

**Comment by xilopaint** [comment]
This is a great improvement! Looking forward to test.

**Comment by xilopaint** [comment]
> To enable Plugin Debug menu: `defaults write com.ameba.Swiftbar PluginDebugMode -bool YES`

The debug menu is not appearing to me.

**Comment by xilopaint** [comment]
> To enable Plugin Debug menu: `defaults write com.ameba.Swiftbar PluginDebugMode -bool YES`

The debug menu is not appearing to me on v1.3.0.

**Comment by melonamin** [comment]
Show me

**Comment by xilopaint** [comment]
> Show me

![Screen Shot 2021-04-02 at 11 54 18](https://user-images.githubusercontent.com/11052366/113426818-639eb180-93aa-11eb-8369-717b1389dca1.png)

**Comment by melonamin** [comment]
Show me your defaults - `defaults read com.ameba.SwiftBar`
Did you relaunch the app after setting the defaults?

**Comment by xilopaint** [comment]
> Show me your defaults - `defaults read com.ameba.SwiftBar`
> Did you relaunch the app after setting the defaults?

Yes, but it doesn't work.

```
$ defaults read com.ameba.SwiftBar
{
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~/Developer/SwiftBar Plugins";
    NSNavPanelExpandedSizeForOpenMode = "{800, 450}";
    "NSStatusItem Preferred Position binance_balance.1m.py" = 614;
    "NSStatusItem Preferred Position binance_orders.py" = "649.5";
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-4" = 0;
    "NSStatusItem Visible binance_positions.py" = 0;
    "NSStatusItem Visible notifications.1m.py" = 0;
    "NSWindow Frame NSNavPanelAutosaveName" = "320 331 800 450 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "345 274 750 428 0 0 1440 875 ";
    PluginDebugMode = 1;
    PluginDirectory = "/Users/arthur/Developer/SwiftBar Plugins";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-04-02 15:13:30 +0000";
    SUSendProfileInfo = 0;
}
```

**Comment by xilopaint** [comment]
> Show me your defaults - `defaults read com.ameba.SwiftBar`
> Did you relaunch the app after setting the defaults?

Yes, but it doesn't work:

```
 $ defaults read com.ameba.SwiftBar
{
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~/Developer/SwiftBar Plugins";
    NSNavPanelExpandedSizeForOpenMode = "{800, 450}";
    "NSStatusItem Preferred Position binance_balance.1m.py" = 614;
    "NSStatusItem Preferred Position binance_orders.py" = "649.5";
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-4" = 0;
    "NSStatusItem Visible binance_positions.py" = 0;
    "NSStatusItem Visible notifications.1m.py" = 0;
    "NSWindow Frame NSNavPanelAutosaveName" = "320 331 800 450 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "345 507 560 195 0 0 1440 875 ";
    PluginDebugMode = 1;
    PluginDirectory = "/Users/***/Developer/SwiftBar Plugins";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-04-02 15:13:30 +0000";
    SUSendProfileInfo = 0;
    Terminal = iTerm;
}
```

**Comment by melonamin** [comment]
🤨🤨🤨
Will try on a clean machine, I guess

**Comment by xilopaint** [comment]
Hey, the menu mysteriously appeared today. I have no clue why.

**Comment by melonamin** [comment]
The menu appears only after plugin refresh(which is wrong and I’ll change it), probably this is it.
