### ISSUE TITLE
Streaming plugins disappearing from menu bar periodically

### ISSUE THREAD

**Issue by shepazon** [swiftbar/SwiftBar#184]
I have a streaming plugin that builds itself, looks great, and sleeps for 15 seconds before outputting the "~~~" to trigger a fresh update of the menu. While the plugin is running, though, it seems to vanish for a minute or two at a time, then return for 15 seconds or so before disappearing again. I can't tell what's going wrong, but something's up.

**Comment by melonamin** [comment]
Hi @shepazon , can you share you plugin?

Just in case: `~~~` resets the menu, i.e. if you don't have any output from the script after `~~~` for a some time there will be nothing in the menubar.

Here is a simple example of a streaming plugin, as soon as random generator emits 1 the menubar will disappear:

```python
#!/usr/bin/env python3
# <swiftbar.type>streamable</swiftbar.type>

import random
import time

n = 0
while True:
    print('~~~', flush=True)
    if n != 1:
        n = random.choice(range(5))
        print(n, flush=True)
    time.sleep(1)
```

**Comment by melonamin** [comment]
Please re-open if needed.

**Comment by shepazon** [comment]
FWIW, the docs (or some of the examples; I don't remember which) showed the "~~~" being done at the end of processing, which is why I did it that way.
