### ISSUE TITLE
Bug: ⚠️ icon when executing echo "-.---" in menu bar

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#19]
Problem: SwiftBar print the ⚠️ icon in the menu bar, when a single command within the script fails, i.e. exits with error, even if there is no stderr & the script catches errors internally, and itself exists without error.

Example:

```
default_value="bar"
var=$(cat /tmp/foo 2>/dev/null)
if ! [[ $var ]] ; then
	var="$default_value"
	echo -n "$default_value" > /tmp/foo
fi
# do something with $var
```

If `/tmp/foo` doesn't exist, e.g. at first run, the `cat` command will exit with an error, but due to the `2>/dev/null` and the consecutive iffi with `echo`, the error is caught and a value is assigned nonetheless, and the script can continue without hickups.

Still, SwiftBar detects the error-exit of the `cat` command and prints the ⚠️ icon.

Solution: Ignore individual exit statuses of individual commands within a script, if there is no stderr, and only print the ⚠️ icon in the menu bar (plus error message in the dropdown menu), if the *script itself* fails, or if there is an actually stderr, e.g. from a command without an appended `2>/dev/null`.

**Comment by melonamin** [comment]
In the recent build this would show "Test" in the menu bar:

```
#!/bin/bash
cat /tmp/this_file_doesnt_exist 2>/dev/null
echo "Test"
```

and this will result in in ⚠️, as expected since script exit code is non 0:
 ```
#!/bin/bash
cat /tmp/this_file_doesnt_exist 2>/dev/null
```

Am I missing something?

**Comment by JayBrown** [comment]
In this case, you're right, because the cat command is "in the open", so to speak. But I'm talking about the following:

```
#!/bin/bash
filecontents=$(cat /tmp/doesnotexist 2>/dev/null)
! [[ $filecontents ]] && filecontents="default content"
echo "TEST | dropdown=false"
echo "---"
echo "$filecontents"
```

In that case I catch any error _within_ the script, but the `cat` command will (of course) still exit with error, because the file doesn't exist. But this should not be caught be SwiftBar. It should not interest SwiftBar at all, because this is 100% the domain of the script, to run commands, and account for commands who return different values, or no values at all.

**Comment by JayBrown** [comment]
PS: I just ran the above test, and it does *not* print the ⚠️ icon… so this is weird… have to check the other script again.

**Comment by JayBrown** [comment]
Okay, I found the error… it's weirder than I thought. I'm actually trying to do the following:

```
allfontfamilies=$(osascript 2>/dev/null << EOF
use framework "AppKit"
set fontFamilyNames to (current application's NSFontManager's sharedFontManager's availableFontFamilies) as list
return fontFamilyNames
EOF
)
if echo "$allfontfamilies" | grep -q "SF Mono" &>/dev/null ; then
	menufont="font=SFMono-Regular size=11"
else
	menufont="font=Menlo-Regular size=11"
fi
echo "-.--- | color=red $menufont dropdown=false"
echo "---"
echo "foo"
```

It seems that printing `-.---` with `echo` works fine in BitBar, but SwiftParse somehow mangles it… maybe SwiftBar thinks that it's a leading `--` or a separator `---`, but that shouldn't be the case.

So my suggestion is that SwiftBar should only account for leading double dashes, in grep syntax `^--`, as a minimum, so when you have a leading `-.`, SwiftBar will ignore it and handle it as a standard echo job.

**Comment by melonamin** [comment]
New [build](https://github.com/swiftbar/SwiftBar/releases/tag/1.0.2-beta-4) is up

**Comment by JayBrown** [comment]
This works, even with leading double-dashes `--.---`

![snap](https://i.imgur.com/CRfQld0.png)
