### ISSUE TITLE
Runs in Terminal, won't run in menubar?

### ISSUE THREAD

**Issue by TerryLansdown** [swiftbar/SwiftBar#191]
Hi, I have been writing a simple crypto tracker, and I'm having trouble as per the title. Here's the code. There's a python script using the coinmarketcap api, along with a local .csv.

Anything obvious I'm doing wrong or is this is a bug?

```
#!/usr/bin/env PYTHONIOENCODING=UTF-8 /usr/local/bin/python3.9

# <bitbar.title>Test</bitbar.title>
# <bitbar.version>v1.0</bitbar.version>
# <bitbar.author>test</bitbar.author>
# <bitbar.author.github>Me</bitbar.author.github>
# <bitbar.desc>Crypto Performance</bitbar.desc>
# <bitbar.image></bitbar.image>
# <bitbar.dependencies>python3, requests, pandas, json</bitbar.dependencies>

from requests import Request, Session
import json
import pandas as pd
import os

cwd = os.getcwd()
print(cwd)
data = pd.read_csv('test.csv', index_col = False)

total_invested    = (data.loc[data['items'] == 'total_invested']).iloc[0,1]
ether_invested    = (data.loc[data['items'] == 'ether_invested']).iloc[0,1]

# Current coins
ether       = (data.loc[data['items'] == 'ether']).iloc[0,1]
fudge       = (data.loc[data['items'] == 'fudge']).iloc[0,1]

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest'
parameters = {
  'id':'1027',
  'convert':'GBP'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '<removed>',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)

  # Ether
  #print((data).get('data').get('1027').get('name'))
  ether_price = (data.get('data').get('1027').get('quote').get('GBP').get('price'))

  # Current value
  ether_value       = ether * ether_price * fudge
  total_value       = (ether_value) * fudge

  print('Crypto = £' +      f'{total_value:.2f}')
  print('Refresh? | refresh=true')

except:
  print('!')
  print('---')
  print('Could not connnect, reload data? | refresh=true')
```

CSV file
```
items,values
total_invested,0
ether_invested,0
fudge,0
```

Thanks Terry

**Comment by melonamin** [comment]
On the first glance the script looks good to me, the only thing is - you probably want to output `---` between these two:

```python
print('Crypto = £' + f'{total_value:.2f}')
print('Refresh? | refresh=true')
```

When you say it "won't run in menubar", what exactly do you mean?

Usual debug process will include:
* looking at logs in Console.app (filtered by SwiftBar)
* if you see ⚠️ in the menubar - click it and choose Show Error

**Comment by TerryLansdown** [comment]
Hi Alex, thanks for getting back to me. Sorry should have been clearer.

Looking at the Console, I'm getting
```
Failed to execute script
/Users/terry/swiftbar/Plugins/test.2h.py
Traceback (most recent call last):
  File "/Users/terry/swiftbar/Plugins/test.2h.py", line 18, in <module>
    data = pd.read_csv('test.csv', index_col = False)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in <…>
```
Looking at the in-app Show Error, it reports file not found, but the test.csv is definitely in the same plug-in's directory. It runs fine if executed via 'Run in Terminal'. Any ideas?

Thanks, Terry

**Comment by melonamin** [comment]
> Looking at the in-app Show Error, it reports file not found, but the test.csv is definitely in the same plug-in's directory.

Ahh, that makes sense, SwiftBar doesn't run plugins in a context of a Plugin Directory. SwiftBar sets special env variable for this `SWIFTBAR_PLUGINS_PATH` - use it.

One other observation - all files in SwiftBar plugins folder are considered to be plugins, SwiftBar will try to execute test.csv in this case. If you want to keep it in plugins folder make it invisible.

**Comment by TerryLansdown** [comment]
Hi, thanks. 

Sorry being dumb. Could you explain further how to use the ```SWIFTBAR_PLUGINS_PATH```? Can't find examples in the other Issues, or the readme. Tried adding

```SWIFTBAR_PLUGINS_PATH = '/data'``` to the file, or
```SWIFTBAR_PLUGINS_PATH = '../data'``` and moving the data files to the right places, but no luck. Sorry for being thick.


In my initial version I had the data file in another location, but couldn't get the os.chdir() to work, so defaulted to the same Plug-ins directory (and disabled the .csv in the in-app settings).

Thanks again.

**Comment by melonamin** [comment]
I mean something like this:

```python
#!/usr/bin/python 

import os

pluginFolder = os.environ['SWIFTBAR_PLUGINS_PATH']
csvFile = "test.csv"
print(pluginFolder + "/" + csvFile)
```

**Comment by TerryLansdown** [comment]
Hi Alex, that's great, thanks, working. Swiftbar is awesome! For other dinks like me, I had to make a slight tweak to get it working:
```
pluginFolder = os.environ['SWIFTBAR_PLUGINS_PATH'] = '/Users/terry/swiftbar/Plugins'
csvFile = 'crypto.csv'
datafile = (pluginFolder + "/" + csvFile)
data = pd.read_csv(datafile, index_col = False)
```
