### ISSUE TITLE
Navigation using arrow keys stops working

### ISSUE THREAD

**Issue by bilal-fazlani** [swiftbar/SwiftBar#193]
Hi,

Navigation using arrow keys does not seem to work correctly. 

It works the first time after plugin is refreshed. After that if you use mouse/trackpad of navigate the menu, then after that arrow key navigation doesn't work until you refresh the plugin.

**Comment by melonamin** [comment]
@bilal-fazlani do you know a reliable way to reproduce it? I've managed to reproduce it once, but not sure how...

https://user-images.githubusercontent.com/222100/116941078-fdbd7800-ac3c-11eb-86ea-250352a8263d.mp4

**Comment by bilal-fazlani** [comment]
Let me try’s  and find out a reproducible pattern. Might need a few days to get back at this.

**Comment by melonamin** [comment]
I still can't reproduce this 😔

**Comment by bilal-fazlani** [comment]
I still does't work for me. I don't know why. Feel free to close this issue.. may be its just my system.

**Comment by melonamin** [comment]
I'll leave it, maybe someone will pitch in
