### ISSUE TITLE
Bug: number of executions increases every time you click "Refresh All" when using "swiftbar.schedule"

### ISSUE THREAD

**Issue by inacho** [swiftbar/SwiftBar#194]
## Overview

When using the tag `<swiftbar.schedule>`, the plugin is executed multiple times if you have used the option "Refresh All" previously.
The number of times that the plugin will be executed depends on the number of times you clicked on "Refresh All".

For example, If I have a plugin with the following schedule `<swiftbar.schedule>* * * * *</swiftbar.schedule>` and I have clicked "Refresh All" 10 times, my plugin will be executed 10 times every minute from now on.
It's pretty problematic especially when the plugin sends notifications or does something that should only happen once. Also, I noticed that it causes a high spike of CPU when you have refreshed many times (for example during plugin development)

## Steps for reproducing the bug

**1 - Create a plugin called `test.sh` with the following contents:**

```bash
#!/usr/bin/env bash

# <bitbar.title>test</bitbar.title>
# <swiftbar.schedule>* * * * *</swiftbar.schedule>

echo 'test'
echo "$(date) Plugin executed" >> ~/plugin-test.log
```

**2 - Click "Refresh All" a few times, for example, 5 times**

**3 - Check the log and wait for the next automatic execution:**

```bash
tail -f ~/plugin-test.log
```

**4- You will see that the plugin has been executed 5 times**

Example:

```
Thu May 13 10:42:00 JST 2021 Plugin executed
Thu May 13 10:42:00 JST 2021 Plugin executed
Thu May 13 10:42:00 JST 2021 Plugin executed
Thu May 13 10:42:00 JST 2021 Plugin executed
Thu May 13 10:42:00 JST 2021 Plugin executed
```

**Comment by melonamin** [comment]
Thanks for reporting this 👍

Fixed for "Refresh All", need to fix it for "Refresh" as well
