### ISSUE TITLE
Header colors change when selected

### ISSUE THREAD

**Issue by disappearinjon** [swiftbar/SwiftBar#196]
My header prints an SF Symbol followed by a Number (e.g., ":envelope.fill: 1"), and when I set both sfcolor and color it displays correctly. However, when I select and pull up the menu, the number shows as white (in dark mode) rather than staying the color (as the envelope does).

Good: ![good - unselected](https://user-images.githubusercontent.com/9439669/119276966-dae60a00-bbd1-11eb-8271-59665b77072a.png)

Bad: ![bad - selected](https://user-images.githubusercontent.com/9439669/119276968-dcafcd80-bbd1-11eb-9ac5-7b66849c8ff1.png)

**Comment by melonamin** [comment]
Yeah, we can look at this as a bug, but in my mind fix would make the envelope white as well.

**Comment by disappearinjon** [comment]
I don't care which way it goes so long as it's consistent. 😁

**Comment by melonamin** [comment]
Fixed
