### ISSUE TITLE
Color names work in lowercase but not in mixed case

### ISSUE THREAD

**Issue by disappearinjon** [swiftbar/SwiftBar#197]
When using CSS color names (as pulled from https://www.w3schools.com/cssref/css_colors.asp) the colors did not display until I changed the names into lowercase.  (This is easy to work around in my code, and I did, but IMHO I shouldn't have to.)

Alternatively, the lowercase-only requirement should be documented.

**Comment by melonamin** [comment]
Thanks, fixed
