### ISSUE TITLE
Request: SVG Support for Images

### ISSUE THREAD

**Issue by cliss** [swiftbar/SwiftBar#198]
Idea: it'd be neat to allow for SVG images using the `image` parameter.

My theory is that it'd be nice because it could fit whatever the native resolution is. However, I recognize that is, in some ways, harder, since it requires SwiftBar to manage the size of the image that results.

Not a do-or-die thing, but I think it'd be neat.

(If this is already supported, my apologies. I tried it and it didn't seem to work.)

**Comment by melonamin** [comment]
AFAIK there is nothing in AppKit that can help me to display an SVG in UIImage\cgImage. 

Probably I can render SVG in WKWebView and do UIGraphicsGetImageFromCurrentImageContext dance... All that to say that I need to research.

**Comment by cliss** [comment]
> Probably I can render SVG in WKWebView and do UIGraphicsGetImageFromCurrentImageContext dance

Honestly I don't think it's worth all that trouble; was just spitballin'.

That said, apologies if I just [nerd-sniped](https://www.urbandictionary.com/define.php?term=nerd-snipe) you. 😆

**Comment by melonamin** [comment]
I built a prototype, it works, but I hate it.🤢

I'm sorry but you'll have to get by with `image`(png/jpeg) and `sfimage` 🙂
