### ISSUE TITLE
Bug: inline image not displayed

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#20]
Example:

```
img="foo" # base64 encoded (144 ppi, 32*32 px)
echo "bar | image=\"$img\""
```

This should print/display the base64-encoded image in front of "foo", just like the SwiftBar icon is in front of "SwiftBar".

However, SwiftBar just prints the base64 string in plaintext.

![snap](https://i.imgur.com/tjaphBT.png)

**Comment by melonamin** [comment]
Works fine for me 🤔:

<img width="430" alt="CleanShot 2020-11-26 at 10 39 05@2x" src="https://user-images.githubusercontent.com/222100/100370071-b965e600-2fd3-11eb-8b03-e3058ac90017.png">

Test Script: [DarkModeToggle.txt](https://github.com/swiftbar/SwiftBar/files/5603896/DarkModeToggle.txt)

**Comment by JayBrown** [comment]
Yes, but you're using `templateImage=foo`, not `image=foo`. The former is for black & white, mainly to be used in the menu bar proper, the latter can be used with color. See e.g. this screenshot:

![snap](https://raw.githubusercontent.com/JayBrown/MacUpdate-Menu/master/img/MUM_screengrab.png)

**Comment by melonamin** [comment]
Sure, but both are working on my end:

<img width="223" alt="Screen Shot 2020-11-26 at 11 02 21 AM" src="https://user-images.githubusercontent.com/222100/100372205-e8ca2200-2fd6-11eb-8b5e-8a527e3b14d3.png">

Can you give me a full script example with broken images?

**Comment by JayBrown** [comment]
Work in progress (on Catalina). `refresh=true` doesn't seem to work either, by the way.

Needs `gtimeout` from the `coreutils`.
[PingThing.10s.sh.zip](https://github.com/swiftbar/SwiftBar/files/5604013/PingThing.10s.sh.zip)

**Comment by JayBrown** [comment]
Here is the version with the relevant lines uncommented.

Maybe the reason is that I'm using line breaks in the base64?
[PingThing.10s.sh.zip](https://github.com/swiftbar/SwiftBar/files/5604027/PingThing.10s.sh.zip)

**Comment by JayBrown** [comment]
Yes, the line breaks in the base64 were the reason.

So it seems that you can only use line breaks for the `templateImage`.

**Comment by melonamin** [comment]
Yes, line breaks are no go, SwiftBar treats each new line as a separate menu item.

BTW I've tried your example in BitBar - it breaks too.

**Comment by JayBrown** [comment]
Though you *can* use line breaks in base64 for the template image, i.e. `base64 -b 64 -i foo.png | pbcopy`
