### ISSUE TITLE
[Request] Default plugin data directories accessible through environment variables

### ISSUE THREAD

**Issue by xilopaint** [swiftbar/SwiftBar#200]
The Alfred app has default locations for saving volatile and non volatile data for its plugins (named "workflows") and these locations are accessible through [environment variables](https://www.alfredapp.com/help/workflows/script-environment-variables/).

Some of my SwiftBar plugins store logs and cache files and I miss default locations to save those files. Would it be possible to implement something like this?

**Comment by melonamin** [comment]
Sound like a great idea 👍

**Comment by melonamin** [comment]
Added `SWIFTBAR_PLUGIN_CACHE_PATH` and `SWIFTBAR_PLUGIN_DATA_PATH`, [ beta build](https://github.com/swiftbar/SwiftBar/releases/tag/v1.3.1)

**Comment by xilopaint** [comment]
Thanks!

**Comment by xilopaint** [comment]
This is no longer working for me.
