### ISSUE TITLE
[Bug] Deleted plugins listed in Preferences

### ISSUE THREAD

**Issue by xilopaint** [swiftbar/SwiftBar#202]
![Screen Shot 2021-06-19 at 11 09 28](https://user-images.githubusercontent.com/11052366/122645171-611d3f80-d0ef-11eb-8231-b3ac3fe8e136.png)

The plugins named `error` are deleted plugins that I can see as disabled plugins if I run `defaults read com.ameba.SwiftBar`.

**Comment by melonamin** [comment]
What are the steps to reproduce?

**Comment by xilopaint** [comment]
> What are the steps to reproduce?

I don't know how to reproduce. 😟

**Comment by xilopaint** [comment]
> What are the steps to reproduce?

I don't know. I tried to uninstall and reinstall the SwiftBar and the issue persists, which suggests that I didn't delete the file that stores the info of disabled plugins. What is the location of this file?

**Comment by xilopaint** [comment]
@melonamin I tried to uninstall and reinstall SwiftBar and the issue persists, which suggests that I didn't delete the file that stores the info of disabled plugins. What is the location of this file?

**Comment by melonamin** [comment]
I'm going to try to reproduce the issue over the weekend.

As for list of disabled plugins, it is stored in `DisabledPlugins` in app preferences `defaults read com.ameba.SwiftBar`

**Comment by xilopaint** [comment]
> As for list of disabled plugins, it is stored in `DisabledPlugins` in app preferences `defaults read com.ameba.SwiftBar`

I know I can see that using `defaults read com.ameba.SwiftBar`, that's in my first post. But `defaults` command reads the plist file, right? Why do I keep seeing deleted plugins listed in `DisabledPlugins` after uninstalling the app and reinstalling it again?

**Comment by melonamin** [comment]
How exactly you're uninstalling it?

Preferences file persists between installations, when you deleting the app from Applications you're not deleting it preferences. 

If you're uninstalling from brew - it should remove everything, you can see it in the [formulae](https://formulae.brew.sh/api/cask/swiftbar.json)

**Comment by xilopaint** [comment]
> If you're uninstalling from brew - it should remove everything, you can see it in the [formulae](https://formulae.brew.sh/api/cask/swiftbar.json)

I've used AppCleaner which deletes all the files specified in the formula including the plist file. For a while it fixed the problem but after a few days the issue came back and I saw the deleted plugins again in `DisabledPlugins`. Very weird behavior. I just uninstalled and reinstalled the app and will let you know if the issue reoccurs.

**Comment by melonamin** [comment]
That sounds weird, I don't see how SwiftBar itself can cause it. 🤔

**Comment by xilopaint** [comment]
Now I have a clue on how to reproduce the issue. It has to do with the new data folders introduced by v1.3.1. Try this sample plugin:

```python3
#!/usr/bin/env python3
import os
import logging

logging.basicConfig(
    filename=os.environ['SWIFTBAR_PLUGIN_CACHE_PATH'] + '/error.log',
)

print('foo')
```

If you run this plugin, close SwiftBar and reopen it you will see an `error.log` folder being created in the `Caches` folder and a non-existent `error` plugin listed in Preferences.

**Comment by melonamin** [comment]
> Now I have a clue on how to reproduce the issue.

Nope, doesn't work for me. SwiftBar will pick up `error.log` as a plugin only if its within the plugin folder. What is your plugin folder?

**Comment by xilopaint** [comment]
> What is your plugin folder?

It's named SwiftBar.

v1.3.1 is super buggy to me. Another issue I'm facing is a duplicated streaming plugin in the menu bar.

**Comment by melonamin** [comment]
> It's named SwiftBar.

What I meant is - where is it? Does it contain a reference to SwiftBar Caches folder in any way?

From what you are describing it looks like the problem is on your machine, I can't reproduce any of it at.

1.3.1 [didn't change much.](https://github.com/swiftbar/SwiftBar/commit/9585f9ffae1d1cb7efacf399d87184a503d8d589)

**Comment by xilopaint** [comment]
> What I meant is - where is it? Does it contain a reference to SwiftBar Caches folder in any way?

Yes, I have a symlink to the caches folder within the plugin folder. 😬

Is that a problem?

**Comment by melonamin** [comment]
Yes, it is.

Nested folders are traversed by SwiftBar, including symlinks. To hide it from SwiftBar: `chflags -h hidden <symlink>`

**Comment by xilopaint** [comment]
Deleting the symlink fixed the problem. Would it be possible to add menu items for revealing the new data folders in Finder?

**Comment by melonamin** [comment]
I don't think this is a good idea for general public. If you need it often just add it to your plugins

**Comment by xilopaint** [comment]
In Safari preferences you can activate the Develop menu which is hidden by default. Why not doing something similar to SwiftBar?
