### ISSUE TITLE
Streaming plugin doesn't start on macOS wake up and clicking on `Show Error` doesn't display any output

### ISSUE THREAD

**Issue by xilopaint** [swiftbar/SwiftBar#203]

**Comment by melonamin** [comment]
I need logs, and please move this to #179

**Comment by xilopaint** [comment]
How can I get these logs if the problem occurs on system wake up?

**Comment by melonamin** [comment]
Open Console.app, filter events by Process = SwiftBar, keep it open. Export the log when you see the problem

**Comment by melonamin** [comment]
Closed in favor of #179
