### ISSUE TITLE
Docs on streamable plugins

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#208]
The readme mentions that `<swiftbar.type>streamable</swiftbar.type>` makes a plugin “streamable” but doesn't explain that what means at all. I was assuming that it's related to the `~~~` long-running plugins feature that's been discussed in another issue but that doesn't seem the case (or if it is I can't get it to work). More docs would be greatly appreciated.

**Comment by melonamin** [comment]
Added some info into the read me. Let me know if this clears things up.

**Comment by fenhl** [comment]
Indeed it does: I didn't realize that including a refresh period in the filename makes the plugin ignore the streamable property.
