### ISSUE TITLE
swiftbar.environment not available as environment variable

### ISSUE THREAD

**Issue by JeroenVdb** [swiftbar/SwiftBar#214]
The `swiftbar.environment` parameter is not working for me. I tried using it in both node and bash environments. If I understand correctly it was introduced in https://github.com/swiftbar/SwiftBar/issues/160 and released in 1.2.3?

macOS Catalina 10.15.7
Swiftbar 1.3.0

An example script:
```bash
#!/bin/bash

# <bitbar.title>Title goes here</bitbar.title>
# <bitbar.version>v1.0</bitbar.version>
# <bitbar.author>Your Name</bitbar.author>
# <bitbar.author.github>your-github-username</bitbar.author.github>
# <bitbar.desc>Short description of what your plugin does.</bitbar.desc>
# <bitbar.image>http://www.hosted-somewhere/pluginimage</bitbar.image>
# <bitbar.dependencies>python,ruby,node</bitbar.dependencies>
# <bitbar.abouturl>http://url-to-about.com/</bitbar.abouturl>
# <bitbar.droptypes>Supported UTI's for dropping things on menu bar</bitbar.droptypes>
# <swiftbar.environment>['databaseId':'THEDATABASEID']</swiftbar.environment>

export otherDatabaseId="someId"

echo "Debug:"
echo "---"
echo "databaseId: $databaseId"
echo "otherDatabaseId: $otherDatabaseId"
```

I would expect that environmental variable `databaseId` would have value "THEDATABASEID", but it does not exist.

<img width="206" alt="Screenshot 2021-07-08 at 16 57 28" src="https://user-images.githubusercontent.com/657797/124954991-93470080-e00e-11eb-9b0a-e6411a4f7978.png">

The plugins screen shows this:

<img width="750" alt="Screenshot 2021-07-08 at 17 06 28" src="https://user-images.githubusercontent.com/657797/124955353-e15c0400-e00e-11eb-9ca2-de6b9bbbea5c.png">

**Comment by melonamin** [comment]
Thanks you for reporting! 👍

**Comment by rafiazman** [comment]
Using the example script with version 1.4.4 I am not able to see the Environment Variable section anymore in the plugins screen. Has this been removed?
