### ISSUE TITLE
author.github metadata not parsed 

### ISSUE THREAD

**Issue by astrowonk** [swiftbar/SwiftBar#215]
Tested this with my own plugin + others from the repo, the github username <xbar.author.github> key does not seem to get parsed in about or in preferences.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/13702392/125542307-f27feafd-c85e-429c-adb5-ed10b90efdb9.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/13702392/125542383-2d91aac3-e18b-401f-a0f2-8d02e086b690.png">

**Comment by melonamin** [comment]
Thanks for reporting!
