### ISSUE TITLE
[Simple Fix] Improve "Plugin Repository" or "Get Plugins..." View for macOS Catalina

### ISSUE THREAD

**Issue by JQ555888** [swiftbar/SwiftBar#216]
First of all, really appreciate the hard work! This is an excellent app and has been the go to for every Mac that I set up.

Problem see screenshot.

![Screen Shot 2021-07-24 at 4 53 59 PM](https://user-images.githubusercontent.com/47416213/126863262-b933660e-819c-4675-ad98-b070da5898e9.png)

Currently SwiftBar shows a square Window border for the plug in view on Catalina and the Repository view is also quite different from that of Big Sur. Other than that this app has been perfect. This shouldn't be too difficult to fix and I guess it's just due to a different way of dealing with the UI because of the older framework. A lot of clients couldn't update to Big Sur due to some driver incompatibility issues as it further locks down some kexts. Would be awesome to have this minor issue fixed on Catalina. Thanks again for taking the time to maintain this lightweight successor of BitBar!

**Comment by melonamin** [comment]
@JQ555888 you are right, this is due API differences(SwiftUI specifically) between Catalina and Big Sur.
It definitely can be fixed, but I'll prioritize the limited time I have to fixing bugs and adding new features.

I'll keep this issue open, maybe someone from the community would take a stab at it.
