### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by joeshaw** [swiftbar/SwiftBar#218]
I have a plugin that outputs data like:

```
A Foo       100
Some Bazzes 200
Quux        300,000
```

It does this using tabs.

I would like for that alignment to be maintained by SwiftBar.  It isn't because SwiftBar uses a variable width font.  However, it was aligned in BitBar.  (Not sure the mechanism there.)

I'm not wedded to using tabs, though.  I'd be happy to format things another way to get this kind of vertical alignment.

**Comment by melonamin** [comment]
For what it worth setting monospaced font works as expected:

```bash
#!/usr/bin/env bash

echo "ssh"
echo "---"
echo "A Foo         100 | font='Menlo'"
echo "Some Bazzes   200 | font='Menlo'"
echo "Quux          300,000 | font='Menlo'"
```

<img width="214" alt="CleanShot 2021-07-31 at 11 10 57@2x" src="https://user-images.githubusercontent.com/222100/127744266-3714d7b1-d1cc-42ae-b750-e0db267160d1.png">

**Comment by joeshaw** [comment]
Great idea.  Tabs don't work, but spaces do.
