### ISSUE TITLE
Bug: refresh=true not working on Catalina

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#22]
With a line like the following (writing to a preferences file with `defaults`)…

```
echo "--$server | refresh=true terminal=false bash=/usr/bin/defaults param1=write param2=\"$prefs\" param3=currentServer param4=\"$server\" param5=2>/dev/null"
```

…the value gets written to the preferences plist, but SwiftBar (on Catalina) doesn't refresh the plugin, i.e. the user has to wait for the plugin's default refresh time to pass, before the script can load the new value from the preferences file.

The same (no refresh) happens when you run it as a function:

```
if [[ $1 == "writeserver" ]] ; then
	defaults write "$prefs" currentServer "$2" 2>/dev/null
	exit
fi

echo "--$server | refresh=true terminal=false bash=$0 param1=writeserver param2=\"$server\""
```

**Comment by melonamin** [comment]
Note: `refresh=true` works, what doesn't work is `refresh=true` and `bash=...` together, only bash part executes

**Comment by JayBrown** [comment]
Also check if it works with additional `alternate=true` and other combinations, because sometimes I (and probably others) have something like

`echo "foo | image=\"$bar\" checked=true alternate=true refresh=true terminal=false bash=…"`

PS: would be nice to grey out the icon or text in the menu bar when the plug-in is refreshing. (BitBar does that, and it's a great indicator.)
