### ISSUE TITLE
Menu bar item color reverts to black after selection

### ISSUE THREAD

**Issue by astrowonk** [swiftbar/SwiftBar#221]
Expected Behavior: Menu bar item colors remain as defined in the plugin output.

Actual behavior: Once menu bar item with a hyperlink is selected, the color of the text briefly reverts to black. 

Steps to reproduce: Observable below. 

https://user-images.githubusercontent.com/13702392/130465501-5ff5bc92-4b57-41a0-907e-6fba5bba5529.mov

**Comment by melonamin** [comment]
Fixed

![CleanShot 2021-09-11 at 10 11 48](https://user-images.githubusercontent.com/222100/132950754-d58bc023-7006-4805-b336-2ceca88b4249.gif)

**Comment by astrowonk** [comment]
This possible is reverted? Seeing this happen in 1.4.

**Comment by melonamin** [comment]
Thanks, I'll look at it later this week
