### ISSUE TITLE
certain icons move when pressed

### ISSUE THREAD

**Issue by es183923** [swiftbar/SwiftBar#224]
When I use the SF Symbol icon `:cloud.sun:`, the icon moves when pressed. It doesn't matter if there are other icons or text there. I believe that there are more icons that have this behavior.

Here is the code:
```bash
#!/bin/bash
echo ":cloud.sun: optional text or icon | symbolize=true"
```

Here is a gif:
![CleanShot 2021-09-08 at 20 04 42](https://user-images.githubusercontent.com/72744903/132601296-85e7c482-3f1b-4fee-9d3b-c75dfcdf7fe8.gif)

**Comment by melonamin** [comment]
So far I've found a workaround, I can't explain it yet, but it should let you use it just fine. Just set a color for SF Symbol:
```
echo ":cloud.sun: optional text or icon | symbolize=true sfcolor=white"
```

![CleanShot 2021-09-11 at 15 38 04](https://user-images.githubusercontent.com/222100/132959511-33dc9882-333a-449f-96b8-bebdbada5d90.gif)
