### ISSUE TITLE
Feature request: Preferences > tick box: Hide SwiftBar icon

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#23]
Feature request for a tick box in SwiftBar preferences to hide the SwiftBar icon.

This is important for plug-ins, where the user is displaying his own icons with an individual layout/design in terms of size, padding etc.

Alternatively: a text input field in Preferences, where the user can enter the display size of the SwiftBar icon.

Or both. ;)

**Comment by melonamin** [comment]
> Alternatively: a text input field in Preferences, where the user can enter the display size of the SwiftBar icon.

This is to much to my taste, "Disable SwiftBar Icon" checkbox added in #26
