### ISSUE TITLE
SFSymbol Size

### ISSUE THREAD

**Issue by moshed** [swiftbar/SwiftBar#230]
seems the SF symbol isn't affected the the font size.

even better would a way to customize the symbol size independent of the text similar to how you you have `sfcolor`. Maybe `sfsize`?

**Comment by moshed** [comment]
@melonamin not sure if you get notifications if issue is closed so im tagging you.
sfsize appears to only function if the sfimage is emojized so `echo ":bitcoinsign.circle.fill: $BTC_price | sfsize=12"` works but `echo "$BTC_price | sfimage= bitcoinsign.circle.fill sfsize=12"` does not

**Comment by melonamin** [comment]
That is by design, `image`, `templateImage`, and `sfimage` are using standard image size for menubar status item.
