### ISSUE TITLE
Icons go under notch on new MacBook Pro 

### ISSUE THREAD

**Issue by gbrandt** [swiftbar/SwiftBar#231]
Not sure if this is an OS issue or a SwiftBar issue.  With the new 2021 MacBook Pro's the menu bar items will disappear under the notch.

**Comment by melonamin** [comment]
macOS 12.1 "fixed" this, items doesn't go under the notch and hidden instead. There is nothing I can do in SwiftBar to improve this behavior.

Bartender and alike to the rescue.
