### ISSUE TITLE
php scripts does not work under Mac OS Monterey

### ISSUE THREAD

**Issue by lowfreq2010** [swiftbar/SwiftBar#236]
all is does - shows error in bar. how i can fix it.
my computer is mac mini M1

![Screenshot 2021-11-01 at 12 14 41](https://user-images.githubusercontent.com/77280903/139649370-f9e2daa1-a160-4412-a2f9-f51c09bccd00.png)

**Comment by lowfreq2010** [comment]
p.s i have installed php via brew install php command

**Comment by melonamin** [comment]
PHP has been removed in Monterey, that's why you see  `/usr/bin/php: bad interpreter: No such file or directory` If you installed PHP through brew it would be probably in `/opt/homebrew/bin/` directory. 

To fix the plugin, try the following:
- run `which php` to find the full path to PHP directory
- replace `/usr/bin/php` in the script with this path

**Comment by lowfreq2010** [comment]
thanks! it really helped. but now it shows a warning as shown on screenshot
![Screenshot 2021-11-01 at 16 21 18](https://user-images.githubusercontent.com/77280903/139678523-72a693bf-b1ce-4e0a-89be-7b0f5d988606.png)

**Comment by melonamin** [comment]
This question is really fro the plugin developer and should be directed to them.

But on a first glance, it looks like PHP 8 deprecated a function and you see the warning in script's output. My suggestions are either to go to a previous version of PHP or to reach out to the plugin developer.

You can install a specific version of PHP with brew, start by removing the current one and then `brew install php@7.4` Double check that path and see if it fixes the issue

**Comment by lowfreq2010** [comment]
thanks for suggestions. I went with third way with adding error_reporting(0); call at the top of script. and the message was supressed for good.

**Comment by matopeto** [comment]
Hi @lowfreq2010 the issue is on my plugin

see: https://github.com/matopeto/xcode-build-times/issues/17

i will update script to remove the duplicate warning but for now there is one manual step after install the PHP  to specify php path in shebang in the plugin file

**Comment by matopeto** [comment]
@lowfreq2010 deprecated usort warning was fixed, see: https://github.com/matopeto/xcode-build-times/issues/18
