### ISSUE TITLE
The trim parameter does not work

### ISSUE THREAD

**Issue by manabusakai** [swiftbar/SwiftBar#237]
I'm a big fan of SwiftBar ❤️

After updating to v1.4.0, I noticed that the trim parameter does not work.

Here is the code:
```bash
#!/bin/bash

export PATH="$PATH:/usr/local/bin"

echo ":calendar:"
echo "---"
cal -h -3 | while IFS= read line; do
  echo "$line | trim=false font=menlo size=11"
done
```

**v1.2.3**
![v1.2.3](https://user-images.githubusercontent.com/2246869/139856748-a30129ad-2b74-4ca2-b3d8-fb4dddf7d15c.png)

**v1.4.0**
![v1.4.0](https://user-images.githubusercontent.com/2246869/139856800-ef1392ec-81c4-48df-9666-e2f625f4066c.png)

**Comment by melonamin** [comment]
Wow, 1.2.3 was a long time ago, at least it feels like that.

Workaround: add `symbolize=false`. I'll work on a fix a little later
