### ISSUE TITLE
Shebang with space dont work

### ISSUE THREAD

**Issue by matopeto** [swiftbar/SwiftBar#238]
Hi i have a PHP plugin, and as you write in #236 there is problem with Shebang

But i resolve the issue with 

```
#!/usr/bin/env php
```

and that resolve the issue when i run my plugin from commandline.

```
./xcodeBuildTimes.1m.php
```

 But when it is running on swiftbar i get the error:

<img width="750" alt="Screen Shot 2021-11-04 at 18 02 21" src="https://user-images.githubusercontent.com/2447996/140385246-bbb2bf78-43ab-4a65-8879-d05e604b0bff.png">

**Comment by melonamin** [comment]
`#!/usr/bin/env php` picks first php from the `$PATH`. Check contents of `$PATH` in SwiftBar plugin.

**Comment by matopeto** [comment]
Hi @melonamin thanks for quick reply, Where can i check `$PATH` for swiftbar plugin?

When i run from commandline/terminal it is ok, also ok in xbar, i cannot find any path settings in swiftbar preferences.

**Comment by melonamin** [comment]
Please refer to discussion in #77, let me know if it doesn't help

**Comment by matopeto** [comment]
Thanks it was the issue. I switch to zsh in swiftbar settings and PATH is now correct :) thanks again
