### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by DUOLabs333** [swiftbar/SwiftBar#242]
I'm trying to have a script that locks my screen when I close it (but not turn it off). The script, `lockscreen.1s.sh` works in bash, but not in SwiftBar

```
#!/opt/local/bin/bash

while true
do
	if [[ $(ioreg -r -k AppleClamshellState | grep '"AppleClamshellState"' | cut -f2 -d"=") = ' Yes' ]]; then
		./lockscreen
		sleep 1
	fi
done
```

**Comment by melonamin** [comment]
I'm not sure what you're trying to achieve...

The main use for SwiftBar is to show something in the menu bar(like weather) or create a custom menu of things, both can be updated on a schedule. In this case you have a deamon style script, SwiftBar can't help you with that, use launchd

**Comment by xilopaint** [comment]
> I'm not sure what you're trying to achieve...
> 
> The main use for SwiftBar is to show something in the menu bar(like weather) or create a custom menu of things, both can be updated on a schedule. In this case you have a deamon style script, SwiftBar can't help you with that, use launchd

Wouldn't it be possible for a streaming plugin to do the job?

**Comment by melonamin** [comment]
You probably can hack around something, in the end SwiftBar "just launches scripts", but I don't endorse it, it doesn't make sense.

More than that, as soon as the system prepares to sleep SwiftBar kills all running plugins and restart them on wake up.
