### ISSUE TITLE
Always showing the dropdown menu on right click

### ISSUE THREAD

**Issue by fabiospampinato** [swiftbar/SwiftBar#244]
Currently it seems that if the first/title item has a shell action associated with it then you can no longer see the many anymore, even when right-clicking the item.

IMO it'd be much much better to always show the dropdown on right clicks. Otherwise certain kinds of little apps becomes impossible to build and for no good reason really.

**Comment by fabiospampinato** [comment]
Also it's unclear to me if it's possible to open SwiftBar at all in situations like that. 

How should I change its preferences for example? IMO opening SwiftBar.app should always show something that can be interacted with.

**Comment by melonamin** [comment]
It is a bug introduced in 1.4.0, I've noticed it about a week ago, thanks for creating the issue. I think I've introduced it while implementing #217
