### ISSUE TITLE
beta 1.4.1 release icon behavior

### ISSUE THREAD

**Issue by mlcampbe** [swiftbar/SwiftBar#251]
I've loaded the beta release and noticed a new behavior that I don't know is expected or not. When a plugin starts up I see 3 ellipses in the system bar. If I click the icon then when I release the click it shows the expected icon for me. Even if the refresh interval on the plugin is passed I don't see the icon until I click on it. For example, setting a 5s refresh and all I see is the ellipses until I click/release the mouse on it.

Is that normal?

**Comment by melonamin** [comment]
Is it consistent behavior or random?
If it's consistent - can you share the plugin?

**Comment by mlcampbe** [comment]
It seems to be consistent for each start up of swiftbar. The plugin I am using is called colorfulBatteryLevel.

**Comment by melonamin** [comment]
I can reproduce it with this plugin on my machine, thanks.
Investigating.

**Comment by mlcampbe** [comment]
I don't think it is specific to that plugin as I have 1 of 2 plugins I have written that also exhibits the same behavior.

**Comment by melonamin** [comment]
Yeah, I understand, my plugins just wouldn't trigger this behavior for whatever reason.

Try [new build](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.1-beta-3)

**Comment by mlcampbe** [comment]
The new build seems to work fine for all of the plugins I use. Thanks for the quick fix.
