### ISSUE TITLE
Changed code signature in 1.4.1?

### ISSUE THREAD

**Issue by suschizu** [swiftbar/SwiftBar#252]
Hello! I've received a notification that the code signature has changed between version 1.4.0 and 1.4.1 (https://github.com/swiftbar/SwiftBar/releases/download/v1.4.1/SwiftBar.zip)

Ekaterina Belinskaya (X93LWC49WV) but FOUND Ameba Labs, LLC (X93LWC49WV)

can you confirm this?

**Comment by melonamin** [comment]
Hi @suschizu 
Yes, this is OK. We've moved the Apple Developer account from personal to an LLC, this is expected.

**Comment by suschizu** [comment]
thanks @melonamin :)
