### ISSUE TITLE
1.4.1 - \n doesn´t work unter Monterey?

### ISSUE THREAD

**Issue by warmup72** [swiftbar/SwiftBar#253]
Hi,
I´ve upgrade from Big Sur to Monterey 5 minutes ago.
First thing I see was, that my Swiftbar Plugins doesn´t support a new line with \n?
echo "1 \n 2"
echo "1 \n 2"
echo "---"
echo "1 \n 2"
echo "--1 \n 2"

Doesn´t matter using \ oder \\ there is no new line anymore.
A downgrade to 1.4.0 was sucessful.

Seems a Problem with Monterey an 1.4.1

**Comment by melonamin** [comment]
Thanks, looks like it is caused by adding markdown support #168

**Comment by melonamin** [comment]
Try the [new build](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.2-beta-1) please

**Comment by warmup72** [comment]
Hi, yes this fix the problem - Thx!
