### ISSUE TITLE
Swiftbar appears to process STDERR too now

### ISSUE THREAD

**Issue by unixorn** [swiftbar/SwiftBar#255]
I got a bug report on my lima plugin that it was showing log entries, but only on Swiftbar and not Xbar.

I've been using the python logging module, which defaults to write to `STDERR`, which Swiftbar had been ignoring. When I updated to 1.4.1, sure enough I started seeing the log entries too.

See https://github.com/unixorn/lima-xbar-plugin/issues/26 for a screen shot of what we were seeing.

It was an easy enough fix to turn off logging, but could you either make the default behavior to continue to ignore `STDERR`, or add a `<swiftbar.ignoreSTDERR>true</swiftbar.STDERR>` directive we could set in our plugins?

Thanks!

**Comment by dw808303** [comment]
Wonder if [this](https://github.com/swiftbar/SwiftBar/issues/254) is related.

**Comment by unixorn** [comment]
It looks likely, yeah.

To keep compatible with other xbar/bitbar plugins, I think the default behavior should be to ignore `STDERR` unless a directive is explicitly set to scan it too.

The default on unix is to not send `STDERR` to pipes and it would be good to be consistent with that.

**Comment by melonamin** [comment]
Try the [new build](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.2-beta-1) please

**Comment by unixorn** [comment]
The new build seems to have fixed it, thanks!

**Comment by unixorn** [comment]
It would be nice if `STDERR` got captured and written to swiftbar's logs to make plugin debugging easier.

**Comment by melonamin** [comment]
Will do, a quick fix for now

**Comment by unixorn** [comment]
Thanks!

**Comment by melonamin** [comment]
>It would be nice if STDERR got captured and written to swiftbar's logs to make plugin debugging easier.

Extracted here #257 

Closing this one
