### ISSUE TITLE
SF Symbols starting with numbers not being detected in the title (v1.4.1)

### ISSUE THREAD

**Issue by inacho** [swiftbar/SwiftBar#256]
SF symbols starting with numbers (for example `:1.circle:`, `:2.circle:`, etc) are not being detected correctly in the title since version 1.4.1

![Screen Shot 2021-12-23 at 9 37 43](https://user-images.githubusercontent.com/742624/147170382-58796785-5a41-41f7-8f37-b9d963fe0d1c.png)

I believe the cause might the following regex which doesn't match SF symbols starting with numbers:

https://github.com/swiftbar/SwiftBar/blob/2500864b3c5d16cff5029b2fa85bfe2a8eb9beae/SwiftBar/Utility/NSMutableAttributedString%2BSFSymbols.swift#L8

**Comment by melonamin** [comment]
Thanks, try the [new build](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.2-beta-1) please
