### ISSUE TITLE
Redirect plugin's STDERR to SwitBar log and/or Plugin Debug View

### ISSUE THREAD

**Issue by melonamin** [swiftbar/SwiftBar#257]
Based on discussion [here](https://github.com/swiftbar/SwiftBar/issues/255#issuecomment-999985552)

**Comment by unixorn** [comment]
Thanks!

**Comment by unixorn** [comment]
Cool, thanks!

**Comment by xilopaint** [comment]
Debug View is not working for me on v1.4.3.

**Comment by xilopaint** [comment]
@melonamin are you aware about this?

**Comment by melonamin** [comment]
Hey, I can’t do much with “Debug View is not working”, because it’s working for me.

I need more details, steps to reproduce in clean environment, etc.

**Comment by xilopaint** [comment]
It got back to work. Not sure if it's the issue mentioned by you [in this comment](https://github.com/swiftbar/SwiftBar/issues/182#issuecomment-812865456).
