### ISSUE TITLE
Changed code signature in version 1.4.2

### ISSUE THREAD

**Issue by suschizu** [swiftbar/SwiftBar#258]
Hello! I've received a notification that the code signature has changed between version 1.4.1 and 1.4.2:
EXPECTED Ekaterina Belinskaya (X93LWC49WV) but FOUND Ameba Labs, LLC (X93LWC49WV)

can you confirm the change? thanks

**Comment by xilopaint** [comment]
See #252.

**Comment by suschizu** [comment]
oh sorry for that - I totally forgot to fix the error message! thanks
