### ISSUE TITLE
header color support broken in 1.4.2 

### ISSUE THREAD

**Issue by nicoster** [swiftbar/SwiftBar#260]
```
#!/bin/bash

echo "foo|color=red"

echo "---"
echo "bar"
```
whenever a color is specified (whether in text or hex), unwanted separators show up in the menu. 
<img width="218" alt="image" src="https://user-images.githubusercontent.com/625174/147623297-f8641969-9703-4b2a-b3c5-711555357663.png">

Interestingly when right-clicking the header, the dropdown menu looks as expected.
<img width="206" alt="image" src="https://user-images.githubusercontent.com/625174/147623477-e2f94860-f48c-4f01-b4ec-cfcf60ebdf91.png">

**Comment by melonamin** [comment]
HI @nicoster, what macOS version you're on? I don't see this behavior on Monterey.

I've noticed another bug on your screenshot and been able to reproduce it - left-click doesn't change text color like it should(see right click)

**Comment by karillo** [comment]
I just wanted to mention that I had observed the "double separator when using color in the title" behavior from the original report when using 1.4.2 on Catalina (10.5.7). 

The fix for switching color on left-click in 1.4.3 resolves that double-separator issue as well.
