### ISSUE TITLE
Not updating on Monterey M1

### ISSUE THREAD

**Issue by Cygnusfear** [swiftbar/SwiftBar#263]
Scripts (node/js) seem to have stopped updating on Monterey. Manually refreshing works. Interactions in preference window are very unresponsive and (hit and miss) so are right clicks on the menu bar items. 

https://user-images.githubusercontent.com/2925132/147886402-63ff95f1-aff3-4e76-b860-39990b1c808d.mp4

(was looking to post some logs but can't seem to figure out where to find them 🥴)

**Comment by melonamin** [comment]
Logs are in Console.app(filter by process "SwiftBar")
Can you please check [this](https://github.com/swiftbar/SwiftBar/issues/259#issuecomment-1002613099) as well?

If you can share any of non-working plugins it could help too.

**Comment by Cygnusfear** [comment]
In console I get only 'Successfully executed' like the other issue; right clicking selecting 'open plugin folder' hangs and gives me a spinner / end up having to kill the process. It happened to all my plugins.

Deleted application support Swiftbar folder, reinstalled Swiftbar. I had several plugins run at 10ms, I changed those to 1s and it seems to have fixed the spinner issues / is now functional. 

Wildly guessing the issue is Swiftbar running the plugins in the same thread, or other changes in behavior?

**Comment by Cygnusfear** [comment]
Actually, it's no longer hanging/spinner but it seems that even though it's updating in the background the actual Swiftbar isn't updating.

**Comment by melonamin** [comment]
Ok, I think we're making progress.

>I had several plugins run at 10ms

I've created a test plugin `test.10ms.sh`:
```bash
#!/bin/bash
echo $((1 + $RANDOM % 10))
```

I can't reproduce the hanging yet, and as far as I see in the code it shouldn't hang - UI updates and plugin updates are on separate queues.

What I've found is that menu bar will stop updating after right-clicking, but seems to work fine on left click.

**Comment by melonamin** [comment]
Update, I've launched 10 test scripts at the same time and managed to reproduce hanging, you can see this message in the log right before SwiftBar stops refreshing and UI become sluggish `[default] enable_updates_common timed out waiting for updates to reenable`

**Comment by Cygnusfear** [comment]
Some additional information, hopefully useful: while Swiftbar doesn't hang with 1s scripts, the bar doesn't seem to consistently update. 

Console log gives me the line you mentioned:
`enable_updates_common timed out waiting for updates to reenable`

When I right click on the script, the bar does update itself (at least that specific script). I am seeing a few updates after that and then it stops updating again. 
So this basically confirms what you discovered 🙃

**Comment by melonamin** [comment]
Hye @Cygnusfear, can you try this build? [SwiftBar.zip](https://github.com/swiftbar/SwiftBar/files/7927665/SwiftBar.zip)

**Comment by melonamin** [comment]
@Cygnusfear can you check if everything is ok in [Beta 5](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-5)?
