### ISSUE TITLE
Is it possible to open an app when clicking a menu item

### ISSUE THREAD

**Issue by mlcampbe** [swiftbar/SwiftBar#264]
I know I can create a bash script that runs when the menu item is clicked:

echo "This is the Menu Title"
echo "---"
echo "Item Name | bash=<path to script>.sh terminal=true refresh=true"

That works but I'd like to launch an application (one from the /Applications folder) when clicking the menu item. I know I can create a new bash script that opens the app but is there a way to launch an app from the menu item directly? For example I am looking to try to do something like:
echo "Item Name | open=/Applications/<name>/app"

**Comment by melonamin** [comment]
How about this:

```bash
#!/bin/bash

echo ":bookmark:"
echo "---"
echo "Open TextEdit | shell='open' param1='-a' param2='/System/Applications/TextEdit.app/' terminal=false"
```

**Comment by mlcampbe** [comment]
Alex,

Yep that works perfect. Thank You.
