### ISSUE TITLE
How ignore some files in the plugin directory

### ISSUE THREAD

**Issue by teopost** [swiftbar/SwiftBar#266]
Hi,
  in my plugins directory I have a python library

![image](https://user-images.githubusercontent.com/2573389/149990863-fc59ddc4-2ed5-4337-8737-b4ff767fac3a.png)

In the bar I have this 

![image](https://user-images.githubusercontent.com/2573389/149991053-c1817f1f-9055-4c0d-8cb2-7e07956cb5d0.png)

How can I exclude the execution of the jira.py file?

**Comment by melonamin** [comment]
SwiftBar will ignore hidden folder, hide `mylibs` and it will be excluded.

Refer to [this comment](https://github.com/swiftbar/SwiftBar/issues/141#issuecomment-759092357) for more context

**Comment by teopost** [comment]
Thanks.
