### ISSUE TITLE
some SF Symbols not working

### ISSUE THREAD

**Issue by incanus** [swiftbar/SwiftBar#267]
Maybe it's a length issue? I will look into it, but wanted to post first in case it was obvious for someone else. 

In a given plugin, something like `:sun.max:` works just fine, but this does not: 

![Screen Shot 2022-01-25 at 9 49 37 AM](https://user-images.githubusercontent.com/17722/151031374-b2eb4aa4-9edb-4769-a0bd-c094d2748f0c.png)

**Comment by melonamin** [comment]
Work just fine for me:
```bash
#!/bin/bash
echo ":cloud: :point.3.filled.connected.trianglepath.dotted:"
```
<img width="200" alt="CleanShot 2022-01-25 at 09 57 40@2x" src="https://user-images.githubusercontent.com/222100/151032636-458069a8-24b5-47fa-87bb-ea7ae604a8a6.png">

This particular symbol is a part of [SF Symbols 3.0 release](https://developer.apple.com/sf-symbols/release-notes/), can you see it OK in the SF Symbols app?

**Comment by incanus** [comment]
Yep, I copy & pasted it from the app just to be sure. 

![Screen Shot 2022-01-25 at 10 05 53 AM](https://user-images.githubusercontent.com/17722/151033875-d33fa9a2-f213-4e2d-af59-20ea132c5cc6.png)

Now that I look a bit, this is a Big Sur machine, and it doesn't work on my other Big Sur either. Fine on Monterey.

**Comment by melonamin** [comment]
That makes sense, Apple bundles SF Symbols with the OS, newer Symbols are not available on older macOS and iOS releases

**Comment by incanus** [comment]
Huh, I guess I was confused since I have the 3.2 app on Big Sur and it shows up fine there.

**Comment by melonamin** [comment]
| SF Symbols Version | iOS Version | macOS Version | tvOS Version | watchOS Version |
| ------------------ | ----------- | ------------- | ------------ | --------------- |
| 1.0 | 13.0 | 11.0 | 13.0 | 6.0 |
| 2.0 | 14.0 | 11.0 | 14.0 | 7.0 |
| 2.1 | 14.2 | 11.0 | 14.2 | 7.1 |
| 2.2 | 14.5 | 11.3 | 14.5 | 7.4 |
| 3.0 | 15.0 | 12.0 | 15.0 | 8.0 |
| 3.1 | 15.1 | 12.0 | 15.1 | 8.1 |

Got it from [here](https://github.com/SFSafeSymbols/SFSafeSymbols/blob/stable/README.md)

**Comment by incanus** [comment]
Great, thanks for the clarification and sorry for the noise. At least it's documented here now.
