### ISSUE TITLE
Swiftbar taking focus from frontmost app at random

### ISSUE THREAD

**Issue by shepazon** [swiftbar/SwiftBar#268]
I've yet to figure out if there's a pattern, but Swiftbar is periodically pulling itself to the foreground and staying there until the user retargets their focus. This is happening to me periodically while I work in other apps, which is frustrating when trying to edit code -- some number of characters I type go into the ether instead of into my source code during the brief period between focus changing and my recognizing the beeping of keystrokes without a useful focus.

I'm using version 1.4.2. This was not happening to me until I updated to 1.4.2 in the past few days, so I suspect it may be a regression of some sort.

I determined that Swiftbar was taking focus using a [script](https://superuser.com/a/874314) that displays the name and pathname of the frontmost app whenever it changes.

I have just one plugin installed and enabled, a custom one I developed myself. It has not changed since long before the problem began to happen a couple of days ago. (It just happened to me a moment ago, right between typing the words "happen" and "a" -- and then again after typing  the "o" in "words).

**Comment by melonamin** [comment]
Interesting, let me research it a bit, thank you for providing the focus tracking script.

Meanwhile, can you try running this build and see if it causes any trouble?  [SwiftBar.zip](https://github.com/swiftbar/SwiftBar/files/7927665/SwiftBar.zip)

**Comment by shepazon** [comment]
I’m checking it out and will let you know the results.

Eric Shepherd
Senior Developer Writer
Amazon Web Services

On Jan 25, 2022, at 3:18 PM, Alex Mazanov ***@***.******@***.***>> wrote:



Interesting, let me research it a bit, thank you for providing the focus tracking script.

Meanwhile, can you try running this build and see if it causes any trouble? SwiftBar.zip<https://github.com/swiftbar/SwiftBar/files/7927665/SwiftBar.zip>

**Comment by shepazon** [comment]
This is definitely still happening. Can't say why...

**Comment by melonamin** [comment]
Hm, ok.
I did run the monitoring script with SwiftBar in the background for the whole day and didn't catch it.

What plugins are you running? can you share any?

**Comment by shepazon** [comment]
I've figured out what's happening here. When my plugin's support script detects a state change, it issues the command `open swiftbar://refreshplugin?name=mypluginname`  to tell Swiftbar to refresh my plugin.

Doing this causes Swiftbar to take on keyboard focus even though it has no visible UI of its own. That shouldn't happen.

**Comment by shepazon** [comment]
Yep, that solved the issue. Sorry about that, false alarm. (Which really is a good thing). :)
