### ISSUE TITLE
Swiftbar not working on Monterey 12.3 bèta (21E5196i)

### ISSUE THREAD

**Issue by etrahretep** [swiftbar/SwiftBar#271]
Swiftbar not working on Monterey 12.3 bèta (21E5196i)
Every other version before warned that Switrbar should be updated.

**Comment by etrahretep** [comment]
Swiftbar works but there's no python framework in the latest beta?

**Comment by melonamin** [comment]
Check 12.3 Beta release notes:

>Python
Deprecations
Python 2.7 was removed from macOS in this update. Developers should use Python 3 or an alternative language instead. (39795874)
