### ISSUE TITLE
Streamable plugins randomly disappear

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#273]
I added a simple streamable plugin for testing purposes:

```sh
#!/usr/local/bin/zsh
# <swiftbar.type>streamable</swiftbar.type>

n=0

while true; do
    sleep 1
    echo '~~~'
    echo $n
    n=$(($n + 1))
done
```

This plugin sometimes appears and sometimes disappears, seemingly at random.

I am testing on [this test build](https://github.com/swiftbar/SwiftBar/issues/259#issuecomment-1020369658).

**Comment by melonamin** [comment]
How long should I wait? :)

I'm running the [latest build](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-1), watched from 0 to 350 - all good.

**Comment by melonamin** [comment]
BTW there is `defaults write com.ameba.SwiftBar StreamablePluginDebugOutput -bool YES`, this will show stream updates in Console. SwiftBar's "Debug Plugin" doesn't work for streamable plugins

**Comment by fenhl** [comment]
This seems to be related to the flickering issue discussed in #161, as the plugin moves to the left instead of disappearing if Bartender is not running.

If I'm understanding the discussion there correctly, this is an instance of the race condition I pointed out in https://github.com/swiftbar/SwiftBar/issues/118#issuecomment-762202999. Maybe a metadata field could be added to change the behavior of `~~~` as suggested there?

**Comment by fenhl** [comment]
Tried again on 1.4.3-beta-1 and it happens there too.

More evidence this is that race condition:
<img width="225" alt="image" src="https://user-images.githubusercontent.com/641386/151908937-459058e7-111f-49b9-af09-3677a01f4ab0.png">

**Comment by melonamin** [comment]
I'm re-reading your comment from #118 and it makes sense to me, closing `~~~` is a bit more logical from the user standpoint, and probably less error-prone

This is what I currently doing:

```swift
if str.contains(streamSeparator) {
    pluginOutput = str.components(separatedBy: streamSeparator).last
    return
}
pluginOutput.append(str)
```
As you can see, it allows me to escape additional state management and simplify separator logic. If I switch to closing `~~~` I'll have to store the plugin output somewhere between updates.

Anyway, try the [new build](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-2)
`<swiftbar.useTrailingStreamSeparator>true</swiftbar.useTrailingStreamSeparator>`

**Comment by fenhl** [comment]
A modified version of the test plugin with the trailing stream separator feature has counted to 2000 without moving to the left (with Bartender disabled). I'd call that a success!

For anyone who would like to support this with graceful fallback, check for a `SWIFTBAR_BUILD` environment variable ≥ 399.

**Comment by xilopaint** [comment]
> I'm re-reading your comment from #118 and it makes sense to me, closing `~~~` is a bit more logical from the user standpoint, and probably less error-prone

So from now on we need to put the separator at the end?

**Comment by fenhl** [comment]
Only if you use the new `<swiftbar.useTrailingStreamSeparator>true</swiftbar.useTrailingStreamSeparator>` metadata field.

**Comment by xilopaint** [comment]
> Only if you use the new `<swiftbar.useTrailingStreamSeparator>true</swiftbar.useTrailingStreamSeparator>` metadata field.

Could you explain what this metadata does?

**Comment by xilopaint** [comment]
> Only if you use the new `<swiftbar.useTrailingStreamSeparator>true</swiftbar.useTrailingStreamSeparator>` metadata field.

It means the trailing separator is not a new default behavior but an option activated by this metadata?
