### ISSUE TITLE
Run command on notification click

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#274]
Similar to the option of opening a URL added in #190, it would be useful if notifications could run a command when clicked. For consistency with menu item format, I suggest a syntax of `&bash=%2Fusr%2Fbin%2Fsay&param1=hello&terminal=false`.

**Comment by melonamin** [comment]
For a plugin named `test.2s.sh`:
```
open -e 'swiftbar://notify?plugin=test.2s.sh&title=title&subtitle=subtitle&body=body&silent=true&bash=%2Fusr%2Fbin%2Fsay&param1=hello&terminal=false'
```
[Beta 4](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-4)

**Comment by fenhl** [comment]
This seems to be ignoring the `&terminal=false` parameter.

**Comment by melonamin** [comment]
Just retested the build and example from above - works as expected on my end. You see different results?

**Comment by fenhl** [comment]
I'm experimenting with different commands and sometimes getting the expected result but sometimes not. It might be related to URL length? Not sure.

**Comment by melonamin** [comment]
I don't think there is a limit that you can reach on practice, at least from the URL Scheme or Swift stand point...

Give me something that doesn't work and I'll debug it.

**Comment by fenhl** [comment]
I ran this command 10 times:

```sh
open -e 'swiftbar://notify?plugin=01-night.o&title=Title&subtitle=Notification%20Subtitle&body=This%20is%20a%20notification%20that%20talks%20when%20clicked&silent=true&bash=%2Fusr%2Fbin%2Fsay&param1=hello&terminal=false'
```

* 5 times clicking it did nothing
* Twice it worked as expected
* Once it opened a new Terminal tab and ran the command there, as if `&terminal=false` was ignored
* Once it pasted the command into the existing Terminal tab
* Once it ran the command outside of a Terminal *and* opened a new Terminal tab (but didn't run anything there)

**Comment by melonamin** [comment]
Seems to be an escaping issue... as usual. Try this one [SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/8007156/SwiftBar.app.zip)

p.s. Apple Notarization service is not working at the moment, so macOs maybe a little unhappy about this binary

**Comment by fenhl** [comment]
Seems to be working consistently now!
