### ISSUE TITLE
Newlines sometimes ignored in streaming plugins

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#277]
Test plugin:

```sh
#!/usr/local/bin/zsh
# <swiftbar.type>streamable</swiftbar.type>
# <swiftbar.useTrailingStreamSeparator>true</swiftbar.useTrailingStreamSeparator>

n=0

while true; do
    sleep 1
    echo $n
    echo '---'
    echo content
    n=$(($n + 1))
    echo '~~~'
done
```

This uses the trailing stream separator feature added for #273; I'm running on [Swiftbar 1.4.3 beta 4](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-4).

For some iterations of the loop, the plugin displays e.g. `5---content` in the menu bar, with no menu content (other than the SwiftBar submenu, “Updated in 0 Seconds”, etc). Other times, it just displays the number in the menu bar and the menu content is “content”, as expected.

**Comment by fenhl** [comment]
In another plugin I'm running, I also sometimes see the last few menu items merged into one, so it looks like whatever is going wrong here can happen in the middle of the plugin content, not just for the entire content.

**Comment by melonamin** [comment]
[Beta 5](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-5)

**Comment by fenhl** [comment]
Seems to be fixed!
