### ISSUE TITLE
New plugin does not display

### ISSUE THREAD

**Issue by zkarj735** [swiftbar/SwiftBar#279]
Everything has been running fine until I tried creating a new plugin today.

The new plugin was a copy of an existing one with a couple of minor detail changes in content and a different name (obviously). But this new plugin simply does not show up in the menu bar, even though it:
a) shows up in the preferences as enabled
b) shows in Console as having executed successfully
c) executes exactly as I suspect when run manually

Furthermore, while trying to troubleshoot this issue, I tried renaming the new plugin *and* the existing one from which it was copied. Still the new one would not display and the old one also stopped displaying. I could not get the old one working until I renamed it back to its original name.

Reading various issues here I tried:
a) installing some newer builds (linked in issues)
b) wiping out the Application Support folder for SwiftBar
c) downgrading to 1.4.0

None of this has changed the behaviour.

The fact it was a direct copy of a working plugin, plus the disappearance of the known working one when renamed suggests there is something not right in SwiftBar.

The plugin outputs are:
Old:
`:thermometer: 24º 74% | color=#ffdd33 sfcolor=#6699ff`
New:
`:thermometer: 28º 62% | color=#33ddff sfcolor=#6699ff`

**Comment by melonamin** [comment]
Hey, @zkarj735

As you can imagine, as SwiftBar developer I'm constantly adding\removing plugins and I would notice if something were off to such extent. But this obviously doesn't help you, so let's try to figure out what is going on on your machine 🙂

For starters, can you please:
* confirm that you're using the [latest Beta](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-5) (this would be easier for me to debug)
* confirm that you're not running Bartender or app like that
* confirm that you have enough space in the menu bar (notched MacBooks behave funny sometimes)
* show me the output of `defaults read com.ameba.SwiftBar`
* attach Console logs
* share plugins code or at least the metadata portion(if any)

**Comment by zkarj735** [comment]
I did say "suggests" because it is also possible I've done something stupid. :-)

* latest beta installed now
* Bartender...

Did I say I might have done something stupid? Excuse me while I go sit in the corner now.

I thought the name of the scripts was a weirdly specific contributor to the behaviour, but it makes perfect sense now and now I have allowed the new one onto the menu bar all is well.

**Comment by girishso** [comment]
FWIW, I had the same problem of SwiftBar not showing up.  Uninstalled and installed 1.4.3 BETA 5, it fixed the issue for me.

**Comment by zkarj735** [comment]
As penance, I should clean it up and publish for others to use.

**Comment by zkarj735** [comment]
Done. Limited use, as researching for the doco I discovered not anyone can get the required API key any more. But useful to some nonetheless.
https://github.com/zkarj735/swiftbar_wunderground
