### ISSUE TITLE
Refresh URL does nothing

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#280]
Testing on [1.4.3 beta 5](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-5), running `open -e 'swiftbar://refreshplugin?name=09-speedruncom.10m.sh'` has no effect (no output in Console, and the plugin's “Updated x minutes ago” doesn't reset). As the name indicates, this is a shell script that runs on a schedule, but the behavior seems to be the same for binary scheduled plugins and binary streaming plugins.

**Comment by melonamin** [comment]
The problem is an error in documentation and inconsistency in documentation...

All URLs except 'swiftbar://notify' expect "plugin id", and notify takes `plugin id`. For `09-speedruncom.10m.sh`:
* `name` - 09-speedruncom
* `id` - 09-speedruncom.10m.sh

This is obviously dumb

**Comment by melonamin** [comment]
URL scheme accepts `name` or `plugin` parameter, content of which can be plugin name or plugin id(see README) [1.4.3 BETA 6](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-6)
