### ISSUE TITLE
Extra line breaks inserted into streaming plugins

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#282]
Testing on [1.4.3 beta 5](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-5), a streamable plugin I'm running is displayed incorrectly for some elements of the stream. When this happens, the menu bar alternates between displaying the header text without the image and not displaying any plugins at all, presumably because the base64 text for the image is too long to fit into the menu bar, and clicking on the plugin shows both the header text and the base64 code, then a separator, and then the plugin body.

From this behavior, I'm guessing that the plugin output is being parsed as if there were a line break in the middle of the first line, specifically between `templateImage=` and the base64 code for the image. This is essentially the opposite of #277 so I'm guessing it's a side effect of the fix there.

**Comment by melonamin** [comment]
[1.4.3 BETA 6](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.3-beta-6)
