### ISSUE TITLE
Incompatible with Future Versions Dialog on Launch

### ISSUE THREAD

**Issue by cliss** [swiftbar/SwiftBar#283]
I keep getting the following dialog when I launch the app:

<img width="372" alt="Screen Shot 2022-02-11 at 11 05 19 AM" src="https://user-images.githubusercontent.com/282460/153653112-37827ec9-169b-4edc-9571-4b829d57bc31.png">

> "SwiftBar" needs to be updated
> This app will not work with future
> versions of macOS and needs to be
> updated to improve compatibility.
> Contact the developer for more
> information.

Not even sure why this is happening, to be honest, as it's built for Apple Silicon and is 64-bit...?

**Comment by melonamin** [comment]
Ehhh... 🤔

Do you have Python plugins? Maybe this is due to Python 2.7 depreciation in macOS 12.3?

**Comment by melonamin** [comment]
I've tested this just to double check, this script gives me the same warning:
```
#!/usr/bin/python2.7

print("Python Test")
```
Python 3 works fine as expected

>Sigh. Oh, Apple. 

I think in this case they are doing the right thing, Python 3 is 10+ years old, IT IS TIME TO UPGRADE CASEY! 😝
The messaging could be better, so much "SwiftBar needs to be updated"...

**Comment by cliss** [comment]
You're 100% correct; out of habit/laziness/ignorance I had been referencing `python` in a script; by changing it to `python3` it worked no sweat.

Apologies for wasting your time, @melonamin! 🤦  😞
