### ISSUE TITLE
Menu items prefixed with ']697;DoneSourcing'

### ISSUE THREAD

**Issue by simonwj** [swiftbar/SwiftBar#286]
Firstly, thank you for SwiftBar.  I love it.

**Describe the bug**
After I ran the last update on SwiftBar it shows the text ']697;DoneSourcing' as a prefix to the emoji symbols I am using for the menu items.  See screenshot

**To Reproduce**
It shows whenever SwiftBar is running.

**Expected behaviour**
Prior to the update SwiftBar used to just show the emoji symbols in the menu.

**Screenshots**
![SwiftBar-prefix](https://user-images.githubusercontent.com/2728700/154545167-e157ff4b-f726-413b-8d79-92d4902f469c.jpg)

**Environment:**
 - macOS version: 12.1
 - SwiftBar version: 1.4.2
 - Using Bartender 4.1.31

**Plugin Example:**
I am using Sunrise plugin https://github.com/matryer/xbar-plugins/blob/main/Time/sunrise.4h.swift
and this SuperDuper plugin written in Python.  I have been running both plugins for several versions without problems.
[superduper.6h.py.zip](https://github.com/swiftbar/SwiftBar/files/8091232/superduper.6h.py.zip)

**Additional Context:**
- [x] I run Bartender but the problem exists whether Bartender is running or not.
- [x] I have tried running the python plugin using xbar and it runs okay.
- [x] I have de-installed SwiftBar cleared all of the files (with help from Hazel) and then reinstalled and the the problem persisted.
- [x] I have checked the source code of both plugins in BBEdit for the text ']697;DoneSourcing' but it is not present.

Can you recommend anything else I could try? Thanks, Simon

**Comment by melonamin** [comment]
Hi @simonwj, I have a loong thread for you to read #269, it has all answers

**Comment by simonwj** [comment]
Awesome Alex.  I wrapped the fig_osc "DoneSourcing" in the if block and that has done it.  Thanks again, for a great tool.

if [ -z $SWIFTBAR ]; then
	fig_osc "DoneSourcing"
fi
