### ISSUE TITLE
Plugin numeric output not showing in dropdown

### ISSUE THREAD

**Issue by msroest** [swiftbar/SwiftBar#289]
**Describe the bug**
I have a plugin that is outputting a numeric value to show in the dropdown.  For some reason the numeric value is not shown

**To Reproduce**
Run the following plugin
```
#!/bin/bash

VAL=$(curl -s https://hub.docker.com/v2/repositories/msroest/sabnzbd_exporter/ | jq -r .pull_count)
echo ⬇️
echo "---"
echo "stuff"
echo $VAL
```

**Expected behavior**
I expect to see the numeric value that is the result of the curl command in the dropdown
Output when run from the terminal:
```
❯ ./exporterpulls.1m.sh
⬇️
---
stuff
1926752
```

**Screenshots**
<img width="281" alt="image" src="https://user-images.githubusercontent.com/91028/155802364-20b503d6-b80b-49d1-b72c-2ed70403d492.png">

**Environment:**
 - macOS version: 12.2.1
 - SwiftBar version: 1.4.2

**Plugin Example:**
Sample plugin to reproduce the issue, link or code. 
See above 
**Additional Context:**

- [x] I don't run Bartender/Dozer/etc. or tested the issue without it running

**Comment by msroest** [comment]
I've tried wrapping the number value in additional quotes and result is
<img width="281" alt="Screen Shot 2022-02-25 at 14 29 56" src="https://user-images.githubusercontent.com/91028/155805678-60df44e9-d0b3-456d-b8b0-b53f3a497bde.png">

```
#!/bin/bash

VAL=$(curl -s https://hub.docker.com/v2/repositories/msroest/sabnzbd_exporter/ | jq -r .pull_count)
echo ⬇️
echo "---"
echo "stuff"
echo "\"$VAL\""
```

**Comment by melonamin** [comment]
I bet it can't find `jq`, to test this try the full path to `jq`.
If it works, something is off in path probably

**Comment by msroest** [comment]
@melonamin yep you're right the jq is from homebrew and looks like swiftbar path didn't have homebrew location.  Putting the full path fixed it.
