### ISSUE TITLE
SwiftBar doesn't load/display plugins in a predictable order

### ISSUE THREAD

**Issue by andrewferrier** [swiftbar/SwiftBar#292]
**Describe the bug**
I recently migrated to SwiftBar from xbar due to many stability bugs in the latter. So far SwiftBar seems much improved over xbar. I was also really pleased to see that as a fellow descendant from BitBar the plugin formats were compatible. However, one thing that seems very different is that plugins are not displayed on the menu bar in a predictable or stable order, even if these are named with a filenaming scheme which should put them in a predictable order.

**To Reproduce**
Have a number of plugins in the plugins directory on various different schedules and which take various times for the plugin scripts to run.

**Expected behavior**
Each plugin will always be in the same order on the menu bar relative to others, even after quitting and restarting SwiftBar.

**Environment:**
 - macOS version: 12.1
 - SwiftBar version: 1.4.2 (386)

**Plugin Example:**
Too complex to easily provide - let me know if you don't recognize or recreate the problem and I'll create some samples.

**Additional Context:**
FWIW, the way xbar handles this is that it processes plugin files based on their filename order - so you can prefix with e.g. `001`, `002`, etc. and have them in a predictable order on the menu bar.

- [X] I don't run Bartender/Dozer/etc. or tested the issue without it running

Thanks for all your hard work on this great app!

**Comment by melonamin** [comment]
Hi @andrewferrier,

can you please show me the output of `defaults read com.ameba.SwiftBar`?

**Comment by andrewferrier** [comment]
Sure, here you go:

```
{
    DisabledPlugins =     (
    );
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~/Documents";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Visible 001-yabai_space.1m.sh" = 1;
    "NSStatusItem Visible 002-weather.15m.sh" = 1;
    "NSStatusItem Visible 003-mpd-control.1m.sh" = 1;
    "NSStatusItem Visible 004-load-warning.30s.sh" = 0;
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-4" = 0;
    "NSWindow Frame GoToSheet" = "1050 859 460 208 0 0 2560 1415 ";
    "NSWindow Frame NSNavPanelAutosaveName" = "880 725 800 448 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "1280 1163 410 252 0 0 2560 1415 ";
    PluginDirectory = "/Users/ferriera/.config/swiftbar";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SUSendProfileInfo = 0;
}
```

**Comment by melonamin** [comment]
Got it. So the way it works right now, it will save the position if you move any SwiftBar item in the menu bar.
To move an item hold `command` and click and drag. Check the output of `defaults read com.ameba.SwiftBar` after that, you’ll see additional items there saying “preferred position…”. 

In short if you move items around they’ll remember that space and use it in the future. Initial state is kinda random now, this is an opportunity for improvement, I guess.

**Comment by andrewferrier** [comment]
Oh, interesting! I had no idea. I just realized you can do that with non-SwiftBar items too which I had no idea about. So I've just learned something about MacOS :)

So this is clearly a way in which SwiftBar operates a bit differently from xbar (not sure about BitBar). I think this behaviour is actually fine. Personally given a blank sheet I'd rather a more declarative/code-based model a bit like the xbar one I described, but frankly that kind of is nose-cone-polishing. Maybe the initial filenames could be used to sort the initial order, but I wouldn't blame you for closing that bug; it's hardly critical.

The one thing I would suggest here though is improving the docs. I searched the README for 'order' and 'position' and didn't find any info on it. I appreciate it is a MacOS feature so not SwiftBar specific, but a quick sentence or two wouldn't hurt just for ignoramuses like me!

**Comment by melonamin** [comment]
> The one thing I would suggest here though is improving the docs. I searched the README for 'order' and 'position' and didn't find any info on it. 

Point taken. Documentation can use some love.

**Comment by melonamin** [comment]
> if you'd be interested

Interested is a wrong word, I would say desperate is more stable! Kidding, all contributions are welcom, big and small. 🙏

**Comment by andrewferrier** [comment]
:) Done, see https://github.com/swiftbar/SwiftBar/pull/293.
