### ISSUE TITLE
Problem with large images: new versions do not work with script that worked in old versions

### ISSUE THREAD

**Issue by tsurezuregusa** [swiftbar/SwiftBar#294]
**Describe the bug**
The new version does not work with my complex script (https://github.com/tsurezuregusa/jma-ruby). The menu bar only shows ... and there is no output in the menu. It shows no error. It seems the problem is with the two large images in menus. The second example file shows one of them and nothing else. Version 1.4 worked.

**Environment:**
 - macOS version: 10.15.7
 - SwiftBar version: 1.4.3

**Plugin Example:**
https://gist.github.com/tsurezuregusa/44af3884be78e408ba1935602dcca4d5

**Additional Context:**

- [ yes ] I don't run Bartender/Dozer/etc. or tested the issue without it running

**Comment by melonamin** [comment]
Just a quick update - still fighting this, quite a pirculiar issue

**Comment by tsurezuregusa** [comment]
Thank you for the consideration. I yet have not been able to look at this again. But the older version continues to function.

**Comment by melonamin** [comment]
@tsurezuregusa 👋 can you please try this build? https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.4-beta-2

**Comment by tsurezuregusa** [comment]
It looks to work well. Thank you very  much!
