### ISSUE TITLE
Icon color not shown (sfcolor not working) in Monterey

### ISSUE THREAD

**Issue by davidgourde** [swiftbar/SwiftBar#295]
**Describe the bug**
When writing a script which uses an icon and a color with the `sfcolor` parameter, the color is ignored in MacOs Monterey (at least).

**To Reproduce**
Steps to reproduce the behavior (on Monterey):
1. Write a script return value like so: `returnValue to ":mic.fill: | sfcolor=#53945d"`
2. The color of the icon is black. Always.

**Expected behavior**
The icon is shown in the chosen color.

**Screenshots**
![Screen Shot 2022-03-18 at 10 05 35 AM](https://user-images.githubusercontent.com/77303785/159017671-b8cdae02-8903-49a0-85ff-b1b70aafb645.png)

**Environment:**
 - macOS version: Monterey: version 12.2.1 (21D62)
 - SwiftBar version: 1.4.3

**Plugin Example:**
[Sample plugin to reproduce the issue](https://github.com/nickjvturner/SwiftBar-Zoom-Plugins/blob/main/zoomMuteState.1s.scpt)

**Additional Context:**

- [x] I don't run Bartender/Dozer/etc. or tested the issue without it running

**Comment by melonamin** [comment]
Hm, on a first try it works for me just fine on Monterey. I've tried boht your exaple and this:
```
!#/bin/zsh
echo ":mic.fill: | sfcolor=#53945d"
```
Can you try this one and report back?

<img width="67" alt="CleanShot 2022-03-18 at 12 23 11@2x" src="https://user-images.githubusercontent.com/222100/159042502-b2cb302f-bb23-41e9-a5cd-14c5c9e22f2a.png">

**Comment by melonamin** [comment]
@david-gourde 👋

**Comment by rinogo** [comment]
I'm a new user with a fresh install on Monterey. I'm having the same issue as @davidgourde on version 1.4.4.

**Comment by rinogo** [comment]
Also, @davidgourde, I think you were trying to do [something similar to me](https://chromatichq.com/insights/quick-win-zoom-mute-status-macos-menubar/), likely.

Given this bug, this is what I ended up using:
```
#Unmuted (Red fill doesn't work currently)
set returnValue to ":mic.fill: | sfcolor=red"

#Muted
set returnValue to ":mic.slash.fill:"
```

**Comment by jahluwalia** [comment]
fwiw, I'm seeing same issue.

**Comment by rinogo** [comment]
Bump? 😁

**Comment by melonamin** [comment]
The problem is I have no idea how to reproduce it! Here I am running SwiftBar 1.4.4 on a clean macOS Monterey:

![Screen Shot 2023-01-13 at 5 28 24 PM](https://user-images.githubusercontent.com/222100/212431033-a4b1d9f6-94ef-458b-bde8-9eb5a3e69f1f.png)

**Comment by rinogo** [comment]
Gah, bummer! Thanks for checking again! Hopefully, others who have the problem can chime in so we can find some commonality that is causing the problem.

**Comment by rbren** [comment]
Same issue here--lmk if there's any info I can provide

**Comment by teocasse** [comment]
I was following the same guide shared by the above commenters for zoom icons, and I found the root cause.

Basically, the script in the guide sets `returnValue` as shared above:
```
set returnValue to ":mic.fill: | sfcolor=#53945d"
```

What the above commenters didn't mention though is that, a few lines below in the script, the _actual_ final `returnValue` is constructed by appending additional instructions:
```
return returnValue & "| size=18
---
zoomMuteState"
``` 

If you look carefully... there is a missing space before the `|`!!! So, changing the line that sets the color as follows fix the issue.
```
set returnValue to ":mic.fill: | sfcolor=#53945d "
```

**Comment by melonamin** [comment]
@teocasse excellent debugging skills, thanks!

 @davidgourde can you confirm this please?
