### ISSUE TITLE
[Request] Add a Developer tab in Preferences

### ISSUE THREAD

**Issue by xilopaint** [swiftbar/SwiftBar#302]
I think developers would benefit from a `Developer` tab in Preferences with options that are only accessible in Terminal through `defaults` command (e.g. activating the Debug menu). Other than that some specialties could be added like an option to set a period for deleting files in the Cache folder (e.g. files older than 1d, 7d, or 30d). I also lack a LOT an easy way to reveal the cache folder in Finder.

The Developer tab could be activated through `defaults` in Terminal so it would not be visible by the regular user and they would have no chance to mess things up.

**Comment by melonamin** [comment]
I mainly want to focus on user features and user experience, I think app is in a good place from plugin development standpoint.

You can create a plugin to address you needs, why not do that and share with the people who needs it?

**Comment by xilopaint** [comment]
> I mainly want to focus on user features

User features in Swiftbar are mainly created by developers through plugins. Imho, apps like Alfred, Swiftbar and Popclip are improved by offering the best possible tools to their developer communities. You have done a great job in that regard, btw.

Other than that, I think Swiftbar userbase, unlike Alfred and Popclip which are available in websites/App Store, is mainly formed by coders, since the app can only be found in GitHub and Homebrew.

> You can create a plugin to address you needs, why not do that and share with the people who needs it?

I would do it if I thought those features would be well addressed through a plugin, but I don't think it's a good approach.

**Comment by melonamin** [comment]
I’m not going to argue over that. I’m ok if somebody pick this up and implements a preference pane. 

I’ll let this issue stick around for sometime.

**Comment by xilopaint** [comment]
Hey @melonamin, I can understand this request is not a priority so I'm closing the issue.
