### ISSUE TITLE
SwiftBar own About not working

### ISSUE THREAD

**Issue by bicaluv** [swiftbar/SwiftBar#303]
**Describe the bug**
The About menu item of SwiftBar (not the one for a plugin) does not work in version 1.4.3.

**To Reproduce**
1. Call About menu item of SwiftBar
2. Nothin happens

**Expected behavior**
I would expect to see an About Dialog or a call to an About Web Page of SwiftBar.

**Environment:**
 - macOS version: 12.3
 - SwiftBar version: 1.4.3

**Plugin Example:**
Not depending on a specific plugin.

**Comment by xilopaint** [comment]
Are you sure you're not facing #285?

**Comment by bicaluv** [comment]
You are right. So my bad.

**Comment by xilopaint** [comment]
Well, I hope your mistake can help convince @melonamin to fix #285. :)
