### ISSUE TITLE
`font=` parameter disallow execution

### ISSUE THREAD

**Issue by kdeldycke** [swiftbar/SwiftBar#306]
**Describe the bug**

It seems that an entry in a sub-menu is not allowed to be clicked and is greyed out each time a font-related option (like `font=` or `emojize=`) is used.

**To Reproduce**

Here is a simple script printing a string:
```python
#!/usr/bin/env python3

print(
"""↑4 | dropdown=false
---
Homebrew Formulae: 3 packages | font=Menlo | emojize=false
--broot     1.11.0 → 1.11.1 | refresh=true | shell=/opt/homebrew/bin/brew | param1=upgrade | param2=broot | param3=--formula | terminal=true
-----
--Upgrade all | shell=/opt/homebrew/bin/brew | param1=upgrade | param2=None | param3=--formula | font=Menlo | refresh=true | terminal=false
""")
```

This renders as:

<img width="449" alt="Screen Shot 2022-04-06 at 17 02 31" src="https://user-images.githubusercontent.com/159718/161982082-3dfcf10c-7815-4c2f-b7f3-a972a095de97.png">

Now if I change that script to (notice the addition of `| font=Menlo |` to the `broot` line):

```python
#!/usr/bin/env python3

print(
"""↑4 | dropdown=false
---
Homebrew Formulae: 3 packages | font=Menlo | emojize=false
--broot     1.11.0 → 1.11.1 | font=Menlo | refresh=true | shell=/opt/homebrew/bin/brew | param1=upgrade | param2=broot | param3=--formula | terminal=true
-----
--Upgrade all | shell=/opt/homebrew/bin/brew | param1=upgrade | param2=None | param3=--formula | font=Menlo | refresh=true | terminal=false
""")
```

It renders as:

<img width="491" alt="Screen Shot 2022-04-06 at 17 10 39" src="https://user-images.githubusercontent.com/159718/161982225-cad72955-c5e0-4196-be3f-4e4efd6b8a9e.png">

You can notice how the submenu item is disabled and greyed-out.

Instead, I expect it to be enabled.

**Environment:**
 - macOS version: macOS 12.3.1
 - SwiftBar version: 1.4.3 (422)

**Plugin Example:**
This issue has been simplified but was encountered with the [latest version (`v4.12.1`) of the `meta_package_manager.7h.py` plugin](https://github.com/kdeldycke/meta-package-manager/blob/v4.12.1/meta_package_manager/xbar/meta_package_manager.7h.py).

**Comment by melonamin** [comment]
Hey @kdeldycke 

You are using the following syntax: `<Item Title> | param = ... | param = ... | param = ...`. Where is it coming from?

Per Readme `<Item Title> | [param = ...]`, where:

- "Item Title" can be any string, this will be used as a menu item title.
- [param = ...] is an optional set of parameters\modificators. Each parameter is a key-value separated by =. Use | to separate parameters from the title.

And your simplified example should look like this:
```
print(
    """↑4 | dropdown=false
---
Homebrew Formulae: 3 packages | font=Menlo emojize=false
--broot     1.11.0 → 1.11.1 | font=Menlo  refresh=true  shell=/opt/homebrew/bin/brew  param1=upgrade  param2=broot  param3=--formula  terminal=true
-----
--Upgrade all | shell=/opt/homebrew/bin/brew  param1=upgrade  param2=None  param3=--formula  font=Menlo  refresh=true  terminal=false
"""
)
```

I hope it helps.

**Comment by kdeldycke** [comment]
Oh I see. `<Item Title> | param = ... | param = ... | param = ...` is from the bitbar/xbar specifications.

I'll try to have my script works for both xbar and SwiftBar them. Thanks for the tip and sorry for the noise! 😅

**Comment by kdeldycke** [comment]
> I don't believe that Bitbar ever behaved like this, I re-implemented the specification 1-to-1. Looks like it was [added ](https://github.com/matryer/xbar/commit/e82cf359908c96dcab0d3341ea36427396ce66d5) as a part of xbar evolution, I have no idea why...

Indeed, this seems like a recent addition. Still, you're right: the pipe separator is supported but optional. I guess we'll see more of these pipe-separated parameters from the plugin repository now that the cat is out of the bag.

As for the reason this was added, maybe it is to make the parser more robust. I might even have encountered some edge-cases, but need to experiment more on my side.
