### ISSUE TITLE
Using `bash` from HomeBrew

### ISSUE THREAD

**Issue by leshik** [swiftbar/SwiftBar#307]
Is there any reason not to use `/usr/bin/env bash` instead of `/bin/bash`?
macOS uses an old version of `bash3`, and I use `bash5` from HomeBrew. Some tools have completions that use `complete -o nosort -o nospace -o default -F ...` and `nosort` option doesn't work in `bash3`, resulting in plugins failure.

**Comment by melonamin** [comment]
Honestly, I can't come up with a reason why not to switch to `/usr/bin/env bash` 🤔

**Comment by melonamin** [comment]
Addedd a separate option in Preferences, try [beta](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.4-beta-1)

**Comment by leshik** [comment]
@melonamin Doesn't work for me for some reason. I.e. the shell used is still system's bash, not the one from HomeBrew despite I have it set in system preferences.

**Comment by xilopaint** [comment]
> @melonamin Doesn't work for me for some reason. I.e. the shell used is still system's bash, not the one from HomeBrew despite I have it set in system preferences.

The latest beta build works for me.

@leshik can you post a screenshot of the dropdown menu using the following plugin?

```bash
echo 'foo'
echo '---'
echo $PATH
echo $(which bash)
```

**Comment by leshik** [comment]
@xilopaint The problem is, I can't even run any script because it fails earlier failing to load `/usr/local/etc/bash-completions.d` as scripts there have some features that are incompatible with Bash v3.

**Comment by xilopaint** [comment]
What error message do you get?

**Comment by leshik** [comment]
@xilopaint
<img width="448" alt="image" src="https://user-images.githubusercontent.com/443678/163707998-d8e5e98c-3cb7-4b64-9db0-3efea0458624.png">

**Comment by xilopaint** [comment]
My bet is you're based on the wrong assumption that SwiftBar is still running the system bash. The message suggests the script expects a Terminal (maybe calling `tmux`?) but SwiftBar is not a Terminal. You can try disabling tab completion and running the script I recommended to check your actual shell.

**Comment by leshik** [comment]
@xilopaint There are 2 errors here, and I'm talking about the first one, i.e. `nosort: invalid option name`, which is resulted from an incorrect Bash version. To confirm this, I edited `/usr/local/etc/bash_completion.d/ipfs-completion.bash`, commented the line `5259` (which is the last one in this file), and added `echo $BASH_VERSION > /tmp/bv.txt` there. SwiftBar has `bash(env)` as a shell selected. Here are the results:
```
$ cat /tmp/bv.txt
3.2.57(1)-release
```
Meanwhile:
```
$ /usr/bin/env bash -c 'echo $BASH_VERSION'
5.1.16(1)-release
```

**Comment by melonamin** [comment]
@leshik I reworked this a bit, please try again using `default` as the shell in SwiftBar Preferences [BETA 4](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.4-beta-4)

**Comment by leshik** [comment]
@melonamin no, not working - same issue

**Comment by melonamin** [comment]
Can you do a quick test for me please?

Run a plugin like this(I'm on mobile, can't test it):

```
!#/bin/env bash

echo "Test"
echo "---"
echo $SHELL
echo $0
ps -p $$

```

And show me the output please.

**Comment by leshik** [comment]
@melonamin as I described in [one of my previous comments](https://github.com/swiftbar/SwiftBar/issues/307#issuecomment-1100805208), I can't run this script as a plugin as the actual error happens prior to any plugin being executed, this my only option was to edit the HomeBrew completion file that causes the error, and insert your code there before the command that fails. Anyway, the results are interesting:
<img width="480" alt="Captura de Pantalla 2022-09-20 a la(s) 9 40 39" src="https://user-images.githubusercontent.com/443678/191155816-0411c8da-f4ca-4b78-954b-072679dbb0a3.png">

**Comment by melonamin** [comment]
Ok, plz help me reproduce your setup on my end, I need to:

1. install bash from brew `brew install bash`
2. change my default shell to freshly installed bash `chsh …`
3. install custom bash completions(???)
4. …
5. It should be as broken as yours

Correct? What should I do at step 3 and what is missing?

**Comment by leshik** [comment]
@melonamin `brew install bash ipfs` (`ipfs` is the package whose completions cause the issue)
`chsh` or just set the default shell for a user in UI (Users - Advanced options)

**Comment by melonamin** [comment]
Ok, I replicated the environment and combination of this plugin and [this build](https://github.com/swiftbar/SwiftBar/files/9641598/SwiftBar.app.zip) seems to be working correctly on my end.

```
#!/usr/bin/env bash

echo "Test"
echo "---"
echo $SHELL
echo $0
ps -p $$
```

<img width="613" alt="CleanShot 2022-09-25 at 15 03 08@2x" src="https://user-images.githubusercontent.com/222100/192161181-008e309d-e05d-4027-abac-d27e4957ec44.png">

**Comment by leshik** [comment]
@melonamin I don't know how else I could help to troubleshoot this. I'm on Intel Mac if it matters (I see yours is ARM), though not sure if it makes any difference.

**Comment by leshik** [comment]
@melonamin while experimenting I somehow screwed the settings, and now I can't access SwiftBar UI at all (though I can see it running in processes). I tried to delete settings, plugins, and restart – but it didn't help. How can I reset SwiftBar to the default state?

**Comment by melonamin** [comment]
Nuking `~/Library/Preferences/com.ameba.SwiftBar.plist` should be enough, but here is the full list of files and folders created by SwiftBar:
![CleanShot 2022-10-05 at 08 01 09@2x](https://user-images.githubusercontent.com/222100/194055713-d307db6f-09f8-4154-a9b3-f0d33c6468b5.png)

**Comment by leshik** [comment]
@melonamin something weird is happening now with this build. The test plugin only works when the shell is set to `zsh`. Selecting `default` results in no output at all (then it's not even possible to access settings), and selecting `bash` draws `⍰` in the bar, but now it doesn't even matter if I comment `complete -o sort ...` option in bash completions – it doesn't work in any case.
