### ISSUE TITLE
Deal with problems regarding "Disable Plugin" in tandem with only one loaded plug-in

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#31]
When a user only has one plug-in loaded, and then clicks on the "Disable Plugin" command in the plugin's dropdown menu, SwiftBar vanishes from the menu bar completely. (The same happens when he clicks on "Disable" in Preferences.)

With SwiftBar gone from the menu bar, the only option to get any plugins back is to quit SwiftBar, which is now difficult, because it has vanished. So you'd need to do it in Activity Monitor, or with `killall SwiftBar` or `osascript -e 'tell application "SwiftBar" to quit' etc.

After relaunch, SwiftBar will then display the "SwiftBar" default string in the menu bar, and is available again for the user.

This, however, should happen immediately, i.e.: with SwiftBar running, when only one plug-in is loaded, and the user disables that plug-in, SwiftBar should immediately display the "SwiftBar" default string, so the user still has access to the app and its preferences.

**Comment by melonamin** [comment]
It works on my end, but for some reason it takes a long time. Can you confirm that it works for you too and just slow?

![CleanShot 2020-11-28 at 12 14 29](https://user-images.githubusercontent.com/222100/100521741-65920300-3173-11eb-98a3-0121000d8c66.gif)

**Comment by JayBrown** [comment]
Ah, my bad. When disabling the last (only) plugin, SwiftBar actually moves from its user-defined position to the far left of my menu bar, and there the "SwiftBar" string was obscured by other applications' menus on the left.

So it's a non-issue. Sorry about that.
