### ISSUE TITLE
I am getting errors on any plugin installed

### ISSUE THREAD

**Issue by SensitiveMeatball** [swiftbar/SwiftBar#311]
i am not a coder. so i am sorry if i miss any guideline to submit my issue here. 

here is the error icons i am getting on every plugin.
![image](https://user-images.githubusercontent.com/104295311/164965660-a2bda4e2-bccd-4e4a-8998-6f34bcfc7196.png)

here is an example error log to one plugin.
![Screenshot 2022-04-24 at 08 42 10](https://user-images.githubusercontent.com/104295311/164965833-7c7c5e81-775b-4fe1-bec3-b3cefc3232a2.png)

i looked at hat PY means and found that it's something called pyhton. i installed that module and restarted my pc but still getting the same stuff.

can anybody help?

**Comment by melonamin** [comment]
Hey @SensitiveMeatball,

Honestly I don't recommend you using this software ig you're not a developer, not trying to become one or don't have a friendly developer nearby :) It is just too finicky by it nature.

Some of the plugins work without any problem, other will not.  Plugins are developed byt the community and supported(if supported) by the plugin developer.

You can try your luck by creating an issue in [xbar-plugins](https://github.com/matryer/xbar-plugins/issues) repository, maybe even tag a developer of a plugin you're interested in.
