### ISSUE TITLE
Delay loading plugin until volume is mounted

### ISSUE THREAD

**Issue by MarcinFalkowski** [swiftbar/SwiftBar#312]
Hi,
I set a plugin folder in Google Drive virtual volume. Unfortunately the volume is initialised late after startup. Swiftbar launches earlier and cannot find the folder. 

Is there a way to delay startup of Swiftbar or to wait until the volume is mounted?

**Comment by melonamin** [comment]
Very interesting use case 🤔

There is no way to "delay" the launch of a program, as far as I'm aware. I think the question is rather - can SwiftBar keep trying to access the plugin folder if it isn't accesible on the first try.

Can you test what would happen if you create a symlinked folder to a Google Drive location and use that as th Plugin Folder for SwiftBar?
