### ISSUE TITLE
Stuck when output exceeds 64KB

### ISSUE THREAD

**Issue by xfangfang** [swiftbar/SwiftBar#313]
**Describe the bug**

I have a script developed in python that may output a large amount of content. 

It works normally on Xbar. When I switch to SwiftBar, I find that the program always displays three points as placeholders at startup. 

When I check the process(`ps -ef  | grep *.py`), I found that the script was running, but when I use `run in Terminal...`, it quickly produce output.

By manually interrupting the script, I get an error message on the status bar. The content of the message is what I originally wanted to output, but it is only 64KB long.

**To Reproduce**

Run any script that produces more than 64KB of content.

**Expected behavior**

Output longer content

**Screenshots**

**Environment:**
 - macOS version: 12.3
 - SwiftBar version: 1.4.3 (422)

**Plugin Example:**

```python
#!/usr/bin/env /usr/bin/python3

# every menu item got 1KB size
LARGE_DATA = "*"*(1024-len("content 00 | extra="))

print("Long Content")
print("---")
# after changing 64 to 63, the problem disappears
for i in range(64):
    print(f"content {i:0>2} | extra={LARGE_DATA}")
```

**Additional Context:**

- [x] I don't run Bartender/Dozer/etc. or tested the issue without it running

https://github.com/swiftbar/SwiftBar/blob/4dbe224c878981d87858b1937e9ee3962d554936/SwiftBar/Utility/RunScript.swift#L73-L86

I guess the problem is that the default buffer size is only 64KB. When the output content is too large, the program will get stuck at line 82, so I adjusted the above code(line 82 to 85) to:

```swift
  
             outputData = outputPipe.fileHandleForReading.readDataToEndOfFile() 
             errorData = errorPipe.fileHandleForReading.readDataToEndOfFile() 

             waitUntilExit() 

```

Then the program can run normally.

Ralated issue: https://github.com/swiftbar/SwiftBar/issues/294https://github.com/swiftbar/SwiftBar/issues/294

**Comment by melonamin** [comment]
Hey @xfangfang, thank you, your assesment is correct, I've got to this point as well when was researching #294 
The problem is I couldn't find any buffer configuration options, yet.

> so I adjusted the above code(line 82 to 85)

This is an interesting idea, I was editing this code so much and got a little blindspoted, thank you for suggestion, I'll test.

**Comment by melonamin** [comment]
Implemented in this beta [build](https://github.com/swiftbar/SwiftBar/releases/tag/v1.4.4-beta-2)?

**Comment by xfangfang** [comment]
@melonamin Great! It works fine for me.
