### ISSUE TITLE
Debug mode toggling is unreliable

### ISSUE THREAD

**Issue by xilopaint** [swiftbar/SwiftBar#316]
I still have issues in toggling debug mode through `defaults`. The value changes between `0` and `1` but the change is not immediately applied in the UI. Nevertheless (not sure if in hours or days) the change is finally applied.

I don't know how to give more steps to reproduce the issue as I don't have Console output when toggling.

**Comment by melonamin** [comment]
Try restarting SwiftBar after toggling the `PluginDebugMode` option
