### ISSUE TITLE
Nothing showing on bar showing on M1 MAX with Notch

### ISSUE THREAD

**Issue by jonathanalevi** [swiftbar/SwiftBar#318]
**Describe the bug**
SwiftBar isn't showing anything on M1 max, and I've tried to click to see if it's a blank space - it's not. It's just not there at all. 

**To Reproduce**
1. Install SwiftBar. 
2. Try to find it. 3. 

**Expected behavior**
App should be there in the bar... 

**Screenshots**
N/A

**Environment:**
 - Monterey 12.3.1
 - 1.4.3b

**Plugin Example:**
N/A

**Additional Context:**

**Comment by melonamin** [comment]
Hey @jonathanalevi 

Do you see SwiftBar process running in Activity Monitor?
