### ISSUE TITLE
Refresh Indicator

### ISSUE THREAD

**Issue by carlosfrodriguez** [swiftbar/SwiftBar#321]
Add an option to have a visual feedback when the plugins are refreshing.

This was done in BitBar and it is also present in xbar, would be a nice addition to also preserve that feature in SwiftBar (for sure is not needed to be enabled by default)

**Comment by melonamin** [comment]
I assume you want to see it only for manual Refresh, correct?

**Comment by carlosfrodriguez** [comment]
Yes that would be fine

**Comment by garyking** [comment]
Yes, this is a good idea. For manual refreshes in SwiftBar, the plugin's text should grey out, as it currently does in xbar.

**Comment by garyking** [comment]
Thanks for the changes! Please close this issue when it's been released, so we are notified.

**Comment by garyking** [comment]
Thanks. I've updated to the new version just now. But the plugins are not dimming when being manually refreshed, using `open -g swiftbar://refreshplugin?name=plugin.1m.js`. The command itself works fine as always, but the plugin does not get dimmed while refreshing (such as while it grabs data from the web).

**Comment by melonamin** [comment]
Yeah, it doesn't do that... Currently it dims the menu on clicking SwiftBar -> Refresh All and a menu item with `... | refresh=true`.
URL scheme is not included :( 

Created #338
