### ISSUE TITLE
in Two-lines Title, the first line is cropped

### ISSUE THREAD

**Issue by snakewa** [swiftbar/SwiftBar#323]
**Describe the bug**
in Two-lines Title, the first line is cropped

**To Reproduce**
1. Just follow readme instruction to use \\n

**Expected behavior**
Line 1 should be displayed without cropped

**Screenshots**
<img width="265" alt="Screen Shot 2022-06-10 at 11 15 22 AM" src="https://user-images.githubusercontent.com/83506/172983344-eb3f4b13-c1ca-4d67-bd95-e37e11b44d32.png">

**Environment:**
 - macOS version: 12.0.1 (21A559)
 - SwiftBar version: Version v1.4.3(422) ~ 1.4.4 (435)
 - Macbook Air M1

**Plugin Example:**
#!/usr/bin/env sh
echo 'Line 1\\n Line2| size=10'
echo '---'

**Additional Context:**

- [x ] I don't run Bartender/Dozer/etc. or tested the issue without it running

**Comment by snakewa** [comment]
or possible to have some more parameter line marginTop ? now like a negative value of marginTop. And I know possbile different menu bar height for lastst macbooks with notch

**Comment by melonamin** [comment]
Hi @snakewa,

the README is outdated, I've decided to not support two line tilte at this moment, I couldn't find a good way to implement it without overcomplicating the code.
