### ISSUE TITLE
Is there a way to decrease the padding in the menu icon?

### ISSUE THREAD

**Issue by npearson72** [swiftbar/SwiftBar#326]
**Describe the bug**
A bit of trivial issue, but wondering if there's a way to reduce the left and right padding around the icon in the menu? For some reason the SwiftBar icon has a bit more space around it when compared to other menu items.

**Screenshots**
<img width="537" alt="Screen Shot 2022-07-17 at 9 15 09 PM" src="https://user-images.githubusercontent.com/1323414/179444513-6724121a-e011-4390-8e4e-cc534ba01bfa.png">
<img width="540" alt="Screen Shot 2022-07-17 at 9 11 12 PM" src="https://user-images.githubusercontent.com/1323414/179444380-ed42919b-9ce7-4b62-89ba-5d8e5641a5c6.png">
<img width="537" alt="Screen Shot 2022-07-17 at 9 15 50 PM" src="https://user-images.githubusercontent.com/1323414/179444566-f83792bf-7f36-42ce-9a90-0d9e6cb69675.png">

**Environment:**
 - macOS version: `12.4`
 - SwiftBar version: `1.4.3`

**Plugin Example:**
I don't think the plugin is the cause

**Comment by bobobox** [comment]
Noticed this too. Minor but a little irritating.

**Comment by jakemauer** [comment]
I'm curious about this as well. I'd love to trim down the padding to match the layout of other icons on my menubar.

**Comment by melonamin** [comment]
I decided not to persue #331 - too much change and support burden.

At the moment SwiftBar using standard(i.e. Apple) padding, I'll keep it this way for consistency with system APIs. Looks like it is not possible to cusomize the padding of the standard element
