### ISSUE TITLE
Text in menu bar is slightly too high up, when using `Oswald Regular` font

### ISSUE THREAD

**Issue by garyking** [swiftbar/SwiftBar#327]
I'm using the [Oswald Regular](https://fonts.adobe.com/fonts/oswald) font for `font`, with `size` set to `15`. The text in the menu bar is slightly higher up than it should be. Is there anything I can do to line it up correctly?

I'm using this font because it's thinner than normal, so I can fit more text in my menu bar.

Obviously this is an incredibly minor issue, but it would be nice to have a way to adjust the vertical spacing here, since I could then apply it universally to all my plugins, easily.

Here's a screenshot:

![SwiftBar - Oswald Regular font](https://user-images.githubusercontent.com/343940/181350372-215d83f2-b751-4f6c-991f-2393947f6dc3.png)

**Comment by melonamin** [comment]
Initially I was planning to implement a custom handling for menu bar view in #331, but this turned out to be a bit more complex than I want. Closing this as "Won't fix" since I don't know a good fix for this.
