### ISSUE TITLE
Calendar permission (for icalbuddy) stopped working after update to Ventura

### ISSUE THREAD

**Issue by mtaras0** [swiftbar/SwiftBar#328]
I know icalbuddy has problems on its own, but I had figured it out on Monterey. But after upgrade to Ventura beta some app permissions got "revoked" it seems like, had to reinstall a few apps. But swiftbar keeps its settings after reinstall, so it never asks for the permission again and icalbuddy returns "error no calendars". I may be wrong on how to fix it, but any way I'd appreciate some help.

**Comment by melonamin** [comment]
Hey, I don't have a machine with Ventura yet. You'll have to wait while I get around to install it somewhere.

**Comment by melonamin** [comment]
This is failing on Ventura because SwiftBar wouldn't ask for Reminders Access permission. This would happen even if you use icalBuddy to read only your calendars and not reminders.

Fixed by adding promt to request Reminders Access.
