### ISSUE TITLE
Question: support for droptypes from the BitBar beta API?

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#33]
Among other stuff, the BitBar v2 beta API has a `droptypes` option, e.g.

`# <bitbar.droptypes>filenames</bitbar.droptypes>`

I'm not seeing those in the relevant SwiftBar README section, so my question is whether SwiftBar already supports those, and, if not, if it will be implemented eventually.

BitBar beta: https://github.com/matryer/bitbar/tree/beta
Examples: https://github.com/matryer/bitbar/blob/beta/Docs/DropToPlugin.md#example
UTIs: https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html

**Comment by JayBrown** [comment]
There's also `# <bitbar.demo>--demo</bitbar.demo>`, but I've never used it.

Another thing that was a big part of the v2 beta, was **streaming through stdout**, but I never got around to really dig into it, so eventually I never used it. (But it might be important to other users.)

https://github.com/matryer/bitbar/blob/beta/Docs/LongRunningPlugins.md#streaming-through-stdout

**Comment by melonamin** [comment]
>I'm not seeing those in the relevant SwiftBar README section, so my question is whether SwiftBar already supports those, and, if not, if it will be implemented eventually.

Not implemented as of now, but planned, we can keep this issue around to track the progress.

>There's also # <bitbar.demo>--demo</bitbar.demo>, but I've never used it.

I feel like this one is a too much hustle for unclear benefits.

>Another thing that was a big part of the v2 beta, was streaming through stdout, but I never got around to really dig into it, so eventually I never used it. (But it might be important to other users.)

This is something I want to implement, it was excluded from initial release because I couldn't find any plugins in bitbar-plugins which are using that.

**Comment by melonamin** [comment]
Closing in favor of #104
