### ISSUE TITLE
[feature request] make the scripts directory headlessly configurable

### ISSUE THREAD

**Issue by IvarWithoutBones** [swiftbar/SwiftBar#330]
Hello, I was wondering if you would be interested in added a command line or configuration file option to set the path to the scripts directory.

I'm using [Nix](https://github.com/LnL7/nix-darwin) to manage my user environment, which takes care of managing dependencies for some scripts I use with this project. Those scripts are written to nix's store, a completely isolated directory which path looks something like `/nix/store/<sha256 hash>-swiftbar-scripts/`. The `<hash>` part would change if any dependencies update, or if I make any changes to the scripts.

It would be great if I could point swiftbar to that store path without having to go through the GUI, that's quite a pain right now. Since I also launch swiftbar through a service managed with nix, I could easily point it to the correct directory with a command line flag, so that no graphical setup is required for my configuration to work.

I currently work around the store paths being inconsistent upon updates by symlinking my scripts directory from the store to `/etc/swiftbar-scripts`,  but its not quite an optimal solution since I still need to go through the GUI to select that.

**Comment by melonamin** [comment]
How about #192?

**Comment by IvarWithoutBones** [comment]
Thanks for the quick response!

Unfortunately that doesn't quite do the trick. Running that command will work when setting the directory the first time, but it doesn't update it when running the command again with a different directory.

**Comment by melonamin** [comment]
Shouldn’t be the case, this command changes the plugin directory, it does more or less the same thing as the UI.

The trick is to restart SwiftBar if it is running.

**Comment by IvarWithoutBones** [comment]
> Shouldn’t be the case, this command changes the plugin directory, it does more or less the same thing as the UI.
> 
> The trick is to restart SwiftBar if it is running.

That's odd. It doesn't seem to update the plugin folder at all for me, even after restarting it. Tried the following without swiftbar running to attempt to debug this:

```shell
~ > mkdir foo                                                      INSERT
~ > sudo defaults write com.ameba.Swiftbar PluginDirectory foo     
~ > defaults write com.ameba.Swiftbar PluginDirectory foo          
~ > SwiftBar                                          
```

But the directory used was still the same as before I ran these commands, the `foo` directory is not recognized at all. The defaults seem correct though:
```shell
~ > defaults read com.ameba.Swiftbar PluginDirectory                           
foo
~ > sudo defaults read com.ameba.Swiftbar PluginDirectory                      
foo
```

Where does it store these preferences? I dont see `com.ameba.Swiftbar` in `~/Library` or `/Library`.

**Comment by IvarWithoutBones** [comment]
Ah, never mind! It appears the capitalization in my command wasn't correct, `com.ameba.Swiftbar` -> `com.ameba.SwiftBar` did the trick :)
