### ISSUE TITLE
Error output logged after every execution

### ISSUE THREAD

**Issue by jbboynton** [swiftbar/SwiftBar#333]
#### Describe the bug

- Every time a script is executed, error output is logged in the console
- The error output contains only the empty string

#### To reproduce

- Add the plugin example below and check the messages logged in the console

#### Expected behavior

- Blank error output should not be logged

#### Screenshots

| ![swiftbar-logs](https://user-images.githubusercontent.com/16706305/191579947-51153ef4-0130-4ca7-a8d2-0dc84dd22734.png) |
|:---:|
| Log messages as they appear in the console |

#### Environment

- macOS Monterey 12.6
- SwiftBar 1.4.3 (422)

#### Plugin example

```bash
#!/bin/bash

# metadata
# <xbar.title>Test</xbar.title>
# <xbar.author>Test</xbar.author>
# <xbar.desc>Test</xbar.desc>

echo "test"
```

- [x] I don't run Bartender/Dozer/etc. or tested the issue without it running

**Comment by melonamin** [comment]
Hey @jbboynton, this have been [addressed](e84e498c4145895dc47179ff98a30104a2c2b026) in 1.4.4. You can jump on the BETA train a wait until it released.
