### ISSUE TITLE
Naming a script with extra ‘.’ causes issues with refresh

### ISSUE THREAD

**Issue by Joshfindit** [swiftbar/SwiftBar#334]
**Describe the bug**

I had some scripts from xbar named `ping.internal.01.3s.sh`, `ping.internal.misc.3s.sh`, `ping.external.dns.3s.sh`, and so-on.

When I upgraded to SwiftBar, they stopped refreshing at all.

After some puzzling, I renamed them to swap `.` for `_` (such as `ping_internal_01.3s.sh`) and it works fine.

**To Reproduce**
1. Add extra `.`s to the filename of a script
2. Run SwiftBar

*May be complicated by the numbers at the end of the filenames*

**Expected behavior**
SwiftBar parses the `.sh` and the interval from the next name segment to the left, then stops parsing.

**Screenshots**
N/A

**Environment:**
 - macOS version: `12.3`
 - SwiftBar version: `1.4.3`

**Plugin Example:**
ping v1.1 from thealmightygrant

**Additional Context:**

- [X] I don't run Bartender/Dozer/etc

**Comment by melonamin** [comment]
Added a bit of dumb, but effective code that seems to eliminate this issue
