### ISSUE TITLE
Different schedules depending on time of the day or day of the week

### ISSUE THREAD

**Issue by samcarter** [swiftbar/SwiftBar#336]
I'm wondering if it is possible to have different schedules depending on the time of the day or day of the week? For example more frequent updates during working hours and less frequent updates during the night or on the weekend?

I tried to put two `swiftbar.schedule` lines in my plugin

```
# <swiftbar.schedule>2 10-18 * * *</swiftbar.schedule>
# <swiftbar.schedule>15 19-9 * * *</swiftbar.schedule>
```

but swiftbar seems to only pick up the first one.

Swiftbar: 1.4.3 (422)
OS: macOS 11.6.8

**Comment by melonamin** [comment]
More than one `schedule` is indeed not supported at the moment, but on the first glance should be easy to implement. Let me take a closser look.

**Comment by melonamin** [comment]
Will release in 1.4.4, [updated readme](**https://github.com/swiftbar/SwiftBar#refresh-schedule**)

**Comment by samcarter** [comment]
Brilliant! Thanks a lot for the fast enhancement! 

(I was using bitbar and xbar before I switched to swiftbar and I'm so glad I found your project! Swiftbar just works - no restarts or anything required, one can just leave it running for weeks without probelms)
