### ISSUE TITLE
xbar repository un-maintained?

### ISSUE THREAD

**Issue by jgclark** [swiftbar/SwiftBar#339]
I cannot get PRs to my existing plugins to be actioned at the [xbar repository](https://github.com/matryer/xbar-plugins). I then raised an issue asking whether the repo is still alive ... no reply.

As far as I can understand it from comments in #1 and #2 that you're assuming xbar is active. As it doesn't seem to be, can you please consider alternatives?

**Comment by melonamin** [comment]
Hey @jgclark, in my mind, the value of xbar-plugins repository primarily comes from two things:
* number of plugins
* popularity of the repository(number of stars, watchers, etc.)

I can create a new repository under SwiftBar umbrella, and as you know, I even had one initially, but abandoned the idea.

Currently, I think that having two apps(SwiftBar and xbar) is good for the community, if one of the apps is "slacking" users can switch to another one. This was the reason why I created SwiftBar in the first place. 

Plugins repository is a different story, having multiple repos wouldn't help anyone, and will just create more work for everyone.

xbar has bigger userbase than SwiftBar, maybe, if this changes in the future, @matryer and I will figure out what to do with the plugins repository. Until then I suggest you and others to offer help to @matryer in maintaining the repo.
