### ISSUE TITLE
Feature request: system version environment variable offered by SwiftBar

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#34]
This would obviously break compatibility with the BitBar API, i.e. plugins would only run in SwiftBar, unless the user accounts for the variable `SYSTEM_VERSION` to be empty, and then runs his own checks.

We could probably come up with different environment variables, but one could be `SYSTEM_VERSION`, which would read e.g. "10" for legacy systems, and "11", "12", "13" etc. for new-era systems.

I had the idea when applying the `sfimage=` visual parameter.

Currently I'm doing it like this:

```
#!/bin/zsh
# initial version checks
export SYSTEM_VERSION_COMPAT=0
legacy=false
sysvers=$(sw_vers -productVersion)
vmaj=$(echo "$sysvers" | awk -F"." '{print $1}')
if [[ $vmaj -le 10 ]] ; then
	if [[ $vmaj -eq 10 ]] ; then
		vmin=$(echo "$sysvers" | awk -F"." '{print $2}')
		[[ $vmin -lt 16 ]] && legacy=true
	else
		legacy=true
	fi
fi
# later in the script
if $paused ; then
	if $legacy ; then
		echo "⏸ Pings On Hold | color=blue"
	else
		echo "Pings On Hold | sfimage=pause.circle.fill color=blue"
	fi
	echo "---"
fi
```

If SwiftBar offered the system version number (the major version number) via environmental variable, the whole inital version check could be skipped… unless the script runs in BitBar; then the variable would be empty, and you would need those additional checks.

**Comment by melonamin** [comment]
Closing this as "duplicate"(I know it is original), moving conversation to #50
