### ISSUE TITLE
Refreshing repository data lasts forever ...

### ISSUE THREAD

**Issue by tomads** [swiftbar/SwiftBar#35]
Using SwiftBar 1.0.2 (latest).
When I select the menu item `Get Plugins ... `, the 'Plugin Repository' window is displayed and the message 'Refeshing repository data' within.
However, any plugins are not displayed. The window remains empty ...
(This also happened to me with the previous versions of SwiftBar).

Greetings
Tom

**Comment by melonamin** [comment]
Tom, have you read though #15? Does it help?

Can you please attach SwiftBar logs from Console.app when you're trying to open the Plugin Repository.

**Comment by tomads** [comment]
Hi Alex.

Thanks for your reply.

I think I have solved the problem by now.
So far I had created the plugins folder in my Documents directory. Here `Get Plugins` did not work, the window remained empty. There were no error messages in the console logs.

Then I created the plugins folder on the desktop. And see there: the list of plugins was loaded immediately! Same result with the plugins folder in my user home directory.

No idea why it does not work in the documents folder. Possibly a problem with the access rights?

By the way, I use macos Big Sur ...

A small hint:
If you change the plugins folder in Swiftbar (several times), the plugins are often not displayed (after clicking Get Plugins). The only thing that helps is to restart Swiftbar....
Swiftbar crashes on startup if the originally set Plugins folder has been deleted or moved.

Thanks

Tom

**Comment by melonamin** [comment]
Thanks for the thorough write up, all of these leads me to believe that storing repository data in the Plugin Folder is not a very good idea, I think I'll just move it to another place, like UserDefaults or something like that.

> No idea why it does not work in the documents folder. Possibly a problem with the access rights?

That should work fine, I just tested it on my Big Sur machine. I think we should add more logging, to help with debugging of such issues.

> Swiftbar crashes on startup if the originally set Plugins folder has been deleted or moved.

Great catch, moved it separate issue #47

**Comment by melonamin** [comment]
Found and fixed another possible issue - if plugin directory path contains spaces Repository would not load.
Closing this, till we face more issues like that

**Comment by tomads** [comment]
Hi Alex.

You are right. Now the GetPlugins-Command works, when the Folder `SwiftBarPlugins` is in Documents ...

But i`ve encountered another problem:
When i try to install one of these Plugins, i always get the yellow errorsign in menubar. This is, because inside the downloaded file is nothing then: 404: Not Found

I have attached one of these downloaded files.

THX
