### ISSUE TITLE
Feature request: .swiftbarignore file to specify ignored files, patterns or directories

### ISSUE THREAD

**Issue by dchevell** [swiftbar/SwiftBar#358]
The two current mechanisms for ignoring files are:

1. Start file/directory names with a dot
2. set the `hidden` flag (i.e. `chflags hidden <path>`)

I'd like to suggest a potentially more robust method: .ignore files, a la `.gitignore` or `.dockerignore`.

It's not always possible to set up directories starting with dots - take node's `node_modules` or Python's `__pycache__` folders. As for `chflags`, I can tell you that file syncing services (including iCloud) often mess these flags up, fail to sync them, or reset them. The most robust approach I can think of would be to have a `.swiftbarignore` file that allowed for the same kind of basic pattern matching `.gitignore` or `.dockerignore` files allow. Perhaps you would even consider shipping one with a few sane defaults to prevent the most obvious situations. 

I can't contribute much in the way of swift code but I'd happily contribute docs, find some sane defaults, etc.

(let me know if I'm becoming annoying - I don't have any other pending requests/bugs though! Unless you want to add support for escaping `|` in menu text 😛)

**Comment by melonamin** [comment]
Cool idea and reasoning behind it, not sure why it hadn't surfaced before.

> let me know if I'm becoming annoying

You are not annoying, you are contributing in a very good way, keep it up!

> Unless you want to add support for escaping | in menu text

I bet there is an obscure unicode vertical bar you can use instead 😈
