### ISSUE TITLE
Feature Request: webview persistence control

### ISSUE THREAD

**Issue by ontipto** [swiftbar/SwiftBar#359]
When using a webview, the page stays open when hidden, but reloads when redisplayed. If this could be controlled via an action attribute, persistence and background resources could be tailored to the page.

E.g., when displaying a music website, staying open works great for streaming. But, it's interrupted on redisplay as the page reloads. On a complex page, significant resources can be used even when hidden.

If the persistence and load-on-display could be controlled via something like **webviewpersistent=true** to only load at initial display and stay open when hidden, and **=false** to close the page when hidden and reload on display, these two cases would be more useful.

**Comment by melonamin** [comment]
Great idea, thanks.

I made it persistent by default and now existing `refreshOnOpen` parameter can be used with webview plugin as well.
While I was at it I made this view detachable as well #374

**Comment by ontipto** [comment]
Excellent - thanks! Looking forward to v2.

**Comment by ontipto** [comment]
Tried this using:

webviewpersistent=false
webviewPersistent=false

yet I still see a process in Activity Monitor for the page after first opened; was expecting SwiftBar webviews to act like Safari tabs, where when they're closed, all resources released.

Let me know if I have the param or expectations wrong.

Thanks - exciting to see the first 2.0.0 drop!

**Comment by x-f** [comment]
I have the same issue as @chew-z - I don't want to refresh the plugin on every click (scheduling suits better), but I want the page in webview to reload on click, otherwise I'm seeing the same old content every time I click on the icon. I have a time-related Javascript there.

"webviewpersistent=true|false" is not available as a parameter.
I have to revert back to v1.5.0.

**Comment by melonamin** [comment]
@chew-z and @x-f thanks for your input, this approach makes sense to me.

Updated as follows:
* Added new plugin parameter `#<swiftbar.persistentWebView>true</swiftbar.persistentWebView>`, if set to `true` the web view will **not** refresh on menu open. Defaults to false (i.e. web view refreshes on each open)
* If `persistentWebView = false` then web view process is explicitly killed and not hanging in background

Web view will always refresh when Plugin refreshes, either on schedule or manually.

**Comment by ontipto** [comment]
`persistentWebView = false` works great re: killed web view process, but only when menu is detached then clicked outside of.

Also, all detached web view windows close on desktop click, even when `persistentWebView = true` (process persists in latter case 👍). Should stay open unless explicitly closed, regardless of `persistentWebView`?

**Comment by melonamin** [comment]
> all detached web view windows close on desktop click

This is a bug, oppened an issue #397
