### ISSUE TITLE
Localizations?

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#36]
I could supply a German localization for the app.

Would probably need to be prepared with a `.strings` file and an `.lproj` folder.

PS: my own system is English, but I could switch for testing, if necessary.

**Comment by melonamin** [comment]
Yes! Let me prepare the project to support Localization and do English first, then we could add other languages.

**Comment by JayBrown** [comment]
Take your time. I probably won't have any either before Christmas. 😉

**Comment by melonamin** [comment]
This is done, to add German localization you need to edit [this file](https://github.com/swiftbar/SwiftBar/blob/main/SwiftBar/Resources/Localization/de.lproj/Localizable.strings)

**Comment by JayBrown** [comment]
Before I update the files, some questions & comments.

(1) Some keys/strings possibly missing?
```
"PF_LAUNCH_AT_LOGIN" = "Launch at login";
"PF_RESET_ALL" = "Reset All";
```

(2) Typos (will also correct in the English file)
* "Ok" should be "OK"
* three dots `...` should be displayed with the ellipsis `…`

(3) `MB_LAST_UPDATED`
English "Updated" would be German "Aktualisiert". However, as far as I can tell, this key refers to the root menu string displayed as e.g. "Updated 9 Seconds Ago", "Updated 8 Minutes Ago", "Updated 7 Hours Ago" etc.

A German key would then render the root menu string into "Aktualisiert 9 Seconds Ago" etc., which would be a mix of German and English, and also have an incorrect grammatical order… in reality it would have to be "Vor 9 Sekunden aktualisiert" etc.

So we might need some additional keys, e.g. like so: `"Updated $num $time Ago" > "Vor $num $time aktualisiert"`

And the time strings for the time variable would be:

```
"Second" > "Sekunde"
"Seconds" > "Sekunden"
"Minute" > "Minute"
"Minutes" > "Minuten"
"Hour" > "Stunde"
"Hours" > "Stunden"
"Day" > "Tag"
"Days" > "Tagen"
```

…with differentiation between singular (for one second/minute/hour) and plural (more than two seconds/minutes/hours or more).

**Comment by melonamin** [comment]
> (1) Some keys/strings possibly missing?

"Launch at login" good catch, I though it is localized in external library, fixed.
 "Reset All" was replaced to "PF_ENABLE_ALL" = "Enable All";

>(2) Typos (will also correct in the English file)

Fixed

>(3) MB_LAST_UPDATED

Here is the code:
```
let relativeDate = formatter.localizedString(for: lastUpdated, relativeTo: Date()).capitalized
lastUpdatedItem.title = "\(Localizable.MenuBar.LastUpdated.localized) \(relativeDate)"
```

The date piece localized by iOS, this will probably cause problems in languages where the verb can't be on the first place? I don't know.

Here how it looks at this moment in German locale:

<img width="222" alt="CleanShot 2020-12-20 at 10 07 21@2x" src="https://user-images.githubusercontent.com/222100/102716637-2b67dd00-42ab-11eb-8ba4-a3f4d8d1f9c6.png">

**Comment by xilopaint** [comment]
> I could supply a German localization for the app.
> 
> Would probably need to be prepared with a `.strings` file and an `.lproj` folder.

@JayBrown German localization is still pending. You already have the necessary files to submit a PR.
