### ISSUE TITLE
sfimage parameter is not effected by sfcolor

### ISSUE THREAD

**Issue by bringel** [swiftbar/SwiftBar#364]
**Describe the bug**
While working on a plugin, was using the `sfimage` and `sfcolor` parameters on my output expecting the color to change. This did not work until I changed to using the `:sfsymbol.name.here:` syntax in the text part of the output.

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Environment:**
 - macOS version:
 - SwiftBar version:

**Plugin Example:**
Sample plugin to reproduce the issue, link or code. 

**Additional Context:**

- [x] I don't run Bartender/Dozer/etc. or tested the issue without it running

**Comment by dchevell** [comment]
I believe this would be a breaking change for existing plugins - right now `sfcolor` sets the colour of inline symbols in the menu item text. Making this change would mean existing plugin scripts that already use `sfcolor` for inline symbols, and which also use `sfimage`, would end up with weird / unwanted colours set for `sfimage`.

**Comment by smammy** [comment]
Personally I'd be more worried about having a confusing/overly-complicated API than backwards-compatibility: the plugin ecosystem is small and plugins are easily hackable.

But if this is a concern, adding an `sfimagecolor` parameter would make sense to me.

**Comment by dchevell** [comment]
It's not just that - this would effectively link two unrelated symbols to the one colour directive, so something would have to change either way. One alternative I can think of would be to simply consider `sfimage` when counting the indexes for `sfcolor`, so if `sfimage` is present then it's considered to be at index `0`, and inline symbols would then start from `1`.

For reference, I was testing a beta build for [an unrelated issue](https://github.com/swiftbar/SwiftBar/issues/344#issuecomment-1515370182) and found that multiple scripts of mine were all broken with random icon colours, now I know it was this change being tested :)

**Comment by smammy** [comment]
Ah, gotcha. Assigning the `sfimage` index 0 in the sfcolor list (would that be `sfcolor0`?) would work.

Not sure if there's precedent for this, but what about extending the format of `sfimage` so that it could take colors as extra parameters? For example: `sfimage=exclamationmark.triangle,#ffe000,#ffffcc` This could keep the color information "closer" to the symbol name, which might be nice.

**Comment by peanball** [comment]
It's already merged: https://github.com/swiftbar/SwiftBar/pull/370

**Comment by dchevell** [comment]
Is there a workaround for the concern I raised above? My scripts that use `sfimage` and inline icons now share a colour that was only intended for the inline icon. Indexing all available icons from 0 (starting with sfimage) or something would help
