### ISSUE TITLE
emoji font can't show

### ISSUE THREAD

**Issue by gatspy** [swiftbar/SwiftBar#365]
**Describe the bug**
brew service plugin can't display completely

**Screenshots**
![image](https://user-images.githubusercontent.com/804446/219272728-5187bd56-f2c3-4802-8b6d-04ad0becf0fd.png)

**Environment:**
 - macOS version: macOS 12.6
 - SwiftBar version: 1.4.4(461)

**Plugin Example:**
Brew Service 3.0.1

**Comment by melonamin** [comment]
Here is the list of supported emojis, you can create a pull request to add missing ones https://github.com/swiftbar/SwiftBar/blob/main/SwiftBar/Utility/String+Emoji.swift

**Comment by gatspy** [comment]
add `| symbolize=false` , work fine!
