### ISSUE TITLE
Show a notification when the number of menu items increases

### ISSUE THREAD

**Issue by teopost** [swiftbar/SwiftBar#367]
I have created a plugin that displays a list of issues taken from Jira and assigned to me. Is it possible to show a notification when the number of menu items increases?

**Comment by melonamin** [comment]
Hi @teopost,

There are now built in helpers for this in SwiftBar, but you can do it yourself. Something like this should work:
- On each run save the output the plugin produced in /tmp folder
- Compare the current  output and previously saved one, be as  smart as you want(i.e. only notify issue additions)
- Use SwiftBar [URL Scheme action](https://github.com/swiftbar/SwiftBar#url-scheme) `notify` to present a notification
