### ISSUE TITLE
Can text in the bar be updated by command line or Applescripts?

### ISSUE THREAD

**Issue by MonKong** [swiftbar/SwiftBar#373]
Can text in the bar be updated by command line or Applescripts?

**Comment by melonamin** [comment]
Hi @MonKong,

in the latest released version there is no built in way to do that, but you can easily achive it like this:
* write a simple plugin that outputs contents of a file to menubar
* update this file from command line or Apple Script (independently from SwiftBar)
* tell SwiftBar to reload plugin using URL scheme

In upcoming version this will become much easier with  Ephemeral Plugins #357
