### ISSUE TITLE
How to set templateImage tint color?

### ISSUE THREAD

**Issue by eu81273** [swiftbar/SwiftBar#380]
I want set tint color with templateImage like below sample.

<img width="54" alt="tint color" src="https://github.com/swiftbar/SwiftBar/assets/2687916/abf5d277-f502-4f58-a09a-e7842a15d398">

But I can't found any attributes for this tint color setting.
I made system tray icon image with alpha channel. If tint color option applied to template image, the alpha channel area color changed to that tint color... Is it right?
Is there any way to apply tint color or any plan to support this tint color option?

Thank you for this fantastic project.

**Comment by melonamin** [comment]
Hi @eu81273, can you attach the icon so I can test it?

Related - I'm working on color support for SFSymbols, you would be able to achive what you want when I ship it

**Comment by eu81273** [comment]
@melonamin 
Great!!
This is the icon I made. But I did NOT tested this icon image presents well with tint color.
https://github.com/matryer/xbar-plugins/blob/main/Dev/GitHub/prnotii.5m.js#L25
Just made it with the rule described on the document. (maybe made wrong..)
