### ISSUE TITLE
Tooltips do not display new-line

### ISSUE THREAD

**Issue by teopost** [swiftbar/SwiftBar#382]
I have a text with some newlines that I want to display in the tooltip. The '\n' character is not being converted into a newline. How can I do that?

This line 
```
    def format_tooltip(self, text):

        if text is not None:
            retval = '"' + text.replace('\n', '\\n').replace('\r', ' ') + '"'
        else:
            retval = ''
        return(retval)
```

produce this:

![image](https://github.com/swiftbar/SwiftBar/assets/2573389/a359dab9-9038-456b-8feb-7900b705a13a)

**Comment by melonamin** [comment]
My gut reaction - it is not possible to have a multiline tooltip. But I checked - you definetly can.

You're correct that currently SwiftBar doesn't render '\n' properly in this case and I'm not sure why, needs some digging.

**Comment by melonamin** [comment]
@teopost Try the beta build please [2.0.0-beta-1](https://github.com/swiftbar/SwiftBar/releases/tag/v2.0.0-beta-1)
