### ISSUE TITLE
LaunchAtLoginHelper is not Apple Silicon

### ISSUE THREAD

**Issue by franconi** [swiftbar/SwiftBar#384]
**Describe the bug**
SwiftBar does not autostart at login without Rosetta on Apple Silicon macs.

**To Reproduce**
1. disable Rosetta 
2. Set "Launch at login"
3. Or try to add SwiftBar to Open at Login Items (via System Settings)

**Expected behavior**
SwiftBar does not auto launch at login.
SwiftBar can not be added to Open at Login items.

**Environment:**
 - macOS version: Ventura 13.5, MacBook Pro, Apple 2 Max.
 - SwiftBar version: 1.5.0 (479)

**Comment by melonamin** [comment]
Looks like I need to migrate to [new version of the lib](https://github.com/sindresorhus/LaunchAtLogin-Modern)
