### ISSUE TITLE
sfcolor sets sfimage and first inline icon colour, so they can't be different

### ISSUE THREAD

**Issue by dchevell** [swiftbar/SwiftBar#385]
### Problem

Prior to #364, where `sfimage` didn't support colours, `sfcolor` was bound to inline symbols in the text.

So this example would show a white checkmark, and a blue video icon:
```
echo ":video.circle.fill: Zoom meeting | sfcolor=blue sfimage=checkmark"
```

Since #364, both `sfimage` *and* the first inline symbol are bound to the same color parameter, meaning it's impossible to set one without setting the other. In the above example, both the checkmark and the inline symbol would appear as blue. There's no apparent workaround for this (e.g. using indexes like `sfcolor2`). 

### Suggestions

1. Account for the existence of `sfimage` in the existing `sfcolor` indexing logic - in other words, if `sfimage` is present, then that would be "first" and receive the value of `sfcolor`, and the first inline symbol would be indexed at `sfcolor2`. (There might be other approaches here - e.g. always indexing `sfimage` at `0`, so `sfcolor0` could be used … or something like that)
2. Use a different/unique property for `sfimage` colours, e.g. `sfimagecolor`. This might be "cleaner" in terms of not overloading the API, and the new behaviour has yet to be *formally* released … but given there are beta releases with the existing behaviour out there already, this might be less desirable than option 1.

PS: I know a number of unofficial betas have been dropped in various issues, I'm running one of them. Any chance of updated betas (if not releases) on the [Releases](https://github.com/swiftbar/SwiftBar/releases) page? I'd love to test out some other features like `.swiftbarignore`

**Comment by melonamin** [comment]
Take a look at #354, it ads `sfconfig` property that affects only sfimage. I think this adresses the issue

**Comment by melonamin** [comment]
> Any chance of updated betas (if not releases) on the Releases page?
Here you go  [2.0.0-beta-1](https://github.com/swiftbar/SwiftBar/releases/tag/v2.0.0-beta-1)

**Comment by dchevell** [comment]
Works for me @melonamin , I'll close this out. Thank you!

**Comment by peanball** [comment]
very nice @melonamin, better solution than https://github.com/swiftbar/SwiftBar/pull/370
