### ISSUE TITLE
[Feature Request] Support for shell commands on notification click

### ISSUE THREAD

**Issue by bilal-fazlani** [swiftbar/SwiftBar#386]
Currently notifications support a url which can be http or even custom schemas. 

I needed a way to trigger a bash command on click on notification.

**Comment by melonamin** [comment]
@bilal-fazlani You can do this currently with a combination of a URL Scheme and Shortcuts. Have you considered this?

**Comment by bilal-fazlani** [comment]
How do I do it?

**Comment by melonamin** [comment]
[Run a shortcut using a URL scheme on Mac](https://support.apple.com/guide/shortcuts-mac/run-a-shortcut-from-a-url-apd624386f42/mac)

## Shortcut
![Screenshot 2023-09-03 at 16 51 09](https://github.com/swiftbar/SwiftBar/assets/222100/ee1124de-5418-4a9f-bdce-4cd95844ed7a)

## SwiftBar

Something like this:

`swiftbar://notify?plugin=MyPlugin&title=title&subtitle=subtitle&body=body&href='shortcuts://run-shortcut?name=SwiftBar: Beep'`

**Comment by melonamin** [comment]
@bilal-fazlani I'm closing this, please re-open if you need additional help

**Comment by bilal-fazlani** [comment]
This is very helpful! Thanks 👍
