### ISSUE TITLE
Consider hiding scripts that exit successfully or other mechanism to hide items based on script output

### ISSUE THREAD

**Issue by alexp2ad** [swiftbar/SwiftBar#39]
As [noted in the README](https://github.com/swiftbar/SwiftBar#logs-and-error) plugins that "fail to run" show a ⚠️ icon.

However, with BitBar I used to exit my script successfully with no output to hide the item when its display wasn't necessary (so the icon only shows when there is something to notify the user of).

With SwiftBar that returns the ⚠️. I'd prefer if that only happened for scripts that exited unsuccessfully to allow the previous BitBar behaviour.

However, if the ⚠️ behaviour is desired, perhaps there could be a new parameter such as `hidden` to allow a script to signal that it doesn't want it's output shown in the menu bar?

**Comment by melonamin** [comment]
Ok, so:

- "Empty output with exit code 0" - nothing in the menu bar
- "Any output with non 0 exit code" - ⚠️

Did I get it right? If so, then yeah, it makes more sense than current behavior(empty output is always ⚠️).

**Comment by tjluoma** [comment]
Yes, that would be ideal

**Comment by alexp2ad** [comment]
I would certainly prefer that behaviour, and it would allow the same behaviour that BitBar had for empty output.

It would mean if there's only one script with no output that there would be no menu bar item, which could be confusing, but I think might still be the best option?

**Comment by alexp2ad** [comment]
Just built `main` to get this and it works perfectly, thanks for implementing! 💜
