### ISSUE TITLE
Icon stays in dock after quitting preference window

### ISSUE THREAD

**Issue by samcarter** [swiftbar/SwiftBar#396]
**Describe the bug**

After quitting the SwiftBar preferences, the SwiftBar icon stays in the dock. This behaviour seems to have started after today's update to version [2.0.0](https://github.com/swiftbar/SwiftBar/releases/tag/v2.0.0). I installed [2.0.0 BETA 1](https://github.com/swiftbar/SwiftBar/releases/tag/v2.0.0-beta-1) again and don't see this problem there.

**To Reproduce**
Steps to reproduce the behaviour:
1. Left click on any SwiftBar plugin in the menu bar and open the SwiftBar preferences
2. The preference window will open as desired. At the same time as the preference window opens, also the dock icon of SwiftBar appears. So far so good.
3. After closing the preference window, the SwiftBar dock icon remains visible. It stays visible even after moving the focus to another application, switching spaces. etc. The only way I found to remove it from the dock is to quit SwiftBar and open it again. Then it will happily run again in the menu bar without dock icon.

**Expected behavior**
I would expect that the dock icon would vanish when closing the preference window

**Environment:**
 - macOS version: 14.2.1
 - SwiftBar version: 2.0.0
 - SwiftBar Settings:
![Screenshot 2024-01-01 at 19 26 50](https://github.com/swiftbar/SwiftBar/assets/43832342/b32b72c0-c13f-44b2-bd8e-5bddf62bced1)

**Additional Context:**

- [x] I don't run Bartender/Dozer/etc. or tested the issue without it running

**Comment by melonamin** [comment]
Oops :)

[2.0.1 BETA 1](https://github.com/swiftbar/SwiftBar/releases/tag/v2.0.1-beta-1)

**Comment by samcarter** [comment]
@melonamin Whatever magic you did, 2.0.1 works great! Thanks a lot!
