### ISSUE TITLE
No way to disable ephemeral plugin

### ISSUE THREAD

**Issue by roizcorp** [swiftbar/SwiftBar#398]
Ephemeral Plugins are very useful, but when I do not know the timeout, I can't remove it, the `swiftbar://disableplugin?name=XXX `url does not work. if it was that would solve the issue

**Comment by melonamin** [comment]
It is not obvious, but if you set Ephemeral Plugin content to an empty string SwiftBar will remove the item.

Updated the docs.

**Comment by roizcorp** [comment]
thank you
