### ISSUE TITLE
Template Images not Displaying

### ISSUE THREAD

**Issue by cliss** [swiftbar/SwiftBar#4]
I have a plugin that is **not** timed — it is simply `DarkModeToggle.sh`. It is not being detected by SwiftBar, as far as I can tell.

Interestingly, this is a very slightly modified version of [BitBar's plugin](https://github.com/matryer/bitbar-plugins/blob/master/System/DarkModeToggle.sh).

For kicks, I tried using SwiftBar's plugin browser to see if there was an equivalent for SwiftBar. There was, but installing it simply led to the `Install` button reading `Failed`. (I suspect this is because the file already existed).

I then renamed my version, thus clearing the way for the installation of SwiftBar's. This worked — kinda — and it **was** detected. However, the script was simply a 404:

```
casey@imacpro ~/D/A/BitBar> cat DarkModeToggle.sh
404: Not Found⏎ 
```

Interestingly though, SwiftBar **did** detect it, and presented it simply as an ellipsis (`...`), due to the error. However, upon renaming my file back to `DarkModeToggle.sh`, it was no longer detected.

File attached for reference, renamed to `txt` so GitHub will accept it.

[DarkModeToggle.txt](https://github.com/swiftbar/SwiftBar/files/5583545/DarkModeToggle.txt)

**Comment by cliss** [comment]
Ah, I was wrong: it **is** being detected, but **is not** rendering the base64 template image:

<img width="223" alt="Screen_Shot_2020-11-23_at_9_33_25_AM" src="https://user-images.githubusercontent.com/282460/99974476-fc734f80-2d6e-11eb-8fc8-f45ab8c7cebb.png">

**Comment by melonamin** [comment]
> For kicks, I tried using SwiftBar's plugin browser to see if there was an equivalent for SwiftBar. There was, but installing it simply led to the Install button reading Failed. (I suspect this is because the file already existed).

To make it clear - SwiftBar Repository UI gets data from [swiftbar-plugins](https://github.com/swiftbar/swiftbar-plugins), current content comes from [bitbar-plugins](https://github.com/matryer/bitbar-plugins). More here [Plugin Repository maintenance approach #1](https://github.com/swiftbar/swiftbar-plugins/issues/1)

> I have a plugin that is not timed — it is simply DarkModeToggle.sh

I never thought about such an obvious use case!  I'll test it and see what is going on.

> Ah, I was wrong: it is being detected, but is not rendering the base64 template image:

:mag: Investigating...
