### ISSUE TITLE
Feature Request: Sparkle or other Auto-Update Mechanism

### ISSUE THREAD

**Issue by cliss** [swiftbar/SwiftBar#40]
As it says on the tin. Doesn't need to go full Google Chrome with quiet updates in the background, but something like [Sparkle](https://sparkle-project.org) would be lovely.

(Apologies if this exists already and I didn't realize it!)

**Comment by melonamin** [comment]
>Apologies if this exists already and I didn't realize it!
Nothing to apologies for, no auto-updates available as of now :)

Sparkle is probably the way to go, the main downside - it can't get update stream from GitHub Releases automatically, we'd need to support a Sparkle specific file hosted somewhere(probably just in this repo).

I don't want to do that manually and will check if I can put together a simple GitHub Action instead.

**Comment by tjluoma** [comment]
FWIW - in the meantime (for @cliss or others) I have a shell script that I use to download & install. It also checks for updates and will update the app as well, and save the release notes to a text file too¹ (all in your ~/Downloads folder). If there is no update, it will just tell you.

The script can be found at https://github.com/tjluoma/di/blob/master/di-swiftbar.sh ²

It is thoroughly commented so you should be able to understand exactly what it is doing even if you don't do a lot of shell scripting.

The only downside is that you have to invoke it manually. I recommend using something like Keyboard Maestro or launchd to check every day at a specific time. If you use Keyboard Maestro you could also have it check for updates any time the app launches (which would make it like Sparkle except it will immediately download the app), or when it quits.

Note: if the script finds an update, it will download it and unzip it, then check to see if the app is running. If it is running, it will quit it before installing the update, and then relaunch it. If the app was NOT running when an update is found, it won't be launched after downloading a new version.

**(If you have questions, you can find my email address in the script.)**

¹ Release notes can only be saved if you have `lynx` installed. Everything else uses tools which are part of a default install of macOS.

² The https://github.com/tjluoma/di/ repo has similar scripts for about 350+ apps that I have written over the past several years.

**Comment by melonamin** [comment]
Quick status update - tried to include Sparkle through SPM, it fails at the moment. Maybe this is because I'm on M1 Mac, I will test on Intel and report back.

**Comment by JayBrown** [comment]
Sparkle updates with update feeds would also be a plus, so we can update the app using CoreCode's MacUpdater: https://corecode.io/macupdater/index.html

**Comment by xilopaint** [comment]
@melonamin the current implementation is for manual updates only or there's an automatic check? I will update the Homebrew Cask formula if there's an auto-update implementation.

**Comment by melonamin** [comment]
Current implementation supports both manual and automatic updates, SwiftBar will ask you which option do you prefer.  Manual check is available in Preferences

Not sure I understand the part about the Cask formula...

**Comment by xilopaint** [comment]
> Not sure I understand the part about the Cask formula...

There's an `auto_updates` flag that can be used to keep Homebrew Cask from running `brew upgrade` on apps with self-update capabilities.

**Comment by melonamin** [comment]
TIL, thanks.

Not sure if it makes things better or not thou, if you have the most recent version brew upgrade will just ignore it, right?

**Comment by xilopaint** [comment]
> if you have the most recent version brew upgrade will just ignore it, right?

If you have the cask installed `brew upgrade` will not install new versions since the app will do it for itself. Isn't this a better approach to you? I hate having to wait Homebrew Cask updating an app that's already updated.

**Comment by melonamin** [comment]
As of today, SwiftBar cask doesn't include `auto_updates` flag, which means if you've an old version of SwiftBar you can:
* brew upgrade
* or SwiftBar -> Preferences -> Check for Update

`brew upgrade SwiftBar` will do nothing and will take virtually no-time to run if `brew` version is the same or older than the one you have installed.

I can imagine that there are people who don't like auto updates and want to run `brew upgrade`, if you include the `auto_updates` flag they will lose this ability, right?

**Comment by xilopaint** [comment]
> I can imagine that there are people who don't like auto updates and want to run `brew upgrade`, if you include the `auto_updates` flag they will lose this ability, right?

Yes, but these people in the current implementation have the option to configure SwiftBar not to update, right? I see no reason for not using the flag. As I told before it's annoying to see homebrew updating an app that's already up to date.

**Comment by xilopaint** [comment]
@melonamin what's your take on this?

**Comment by melonamin** [comment]
In my mind both options are ok, I don't care much about either :) Update the brew formula, if you'd like

**Comment by xilopaint** [comment]
> Update the brew formula, if you'd like

Thanks. I'll do it.
