### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by informatix8** [swiftbar/SwiftBar#410]
**Describe the bug**
There is no evidence of any UI. Nothing in the menu bar. Nothing in the dock. Swiftbar is visible from Activity Monitor, but no where else.

**To Reproduce**
Install via brew or zip file. Run the Swiftbar executable.

**Expected behavior**
See any UI window or menu bar item.

**Environment:**
 - macOS version: Ventura 13.0.1
 - SwiftBar version: 2.0.0

**Comment by melonamin** [comment]
@informatix8 please do the following two things:
* run `defaults read com.ameba.SwiftBar` in terminal and share the output
* open Console.app -> Filter by process = swiftbar -> Start Streaming -> Launch SwiftBar. Share the output

**Comment by MasterGroosha** [comment]
Hi, I have the same issue as OP.
First output:
```
{
    DisabledPlugins =     (
    );
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "2E697C3F-A69A-41B5-8CA7-702A6AD4FCF6";
    MSAppCenterPastDevices = {length = 1144, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000382 };
    MSAppCenterSessionIdHistory = {length = 460, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000156 };
    MSAppCenterUserIdHistory = {length = 455, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000151 };
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~/Documents/SwiftBarPlugins";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame NSNavPanelAutosaveName" = "464 473 800 448 0 0 1728 1079 ";
    PluginDirectory = "/Users/groosha/Documents/SwiftBarPlugins";
    SUHasLaunchedBefore = 1;
}
```

Second output:

```
default	00:32:11.474370+0800	SwiftBar	Gained inheritances: {(
    <RBSInheritance| environment:(none) name:com.apple.launchservices.userfacing origID:440-401-28551 0>,
    <RBSInheritance| environment:(none) name:com.apple.launchservices.userfacing origID:440-401-28551 0>
)}
default	00:32:16.061667+0800	SwiftBar	Lost inheritances: {(
    <RBSInheritance| environment:(none) name:com.apple.launchservices.userfacing origID:440-401-28551 0>,
    <RBSInheritance| environment:(none) name:com.apple.launchservices.userfacing origID:440-401-28551 0>
)}
```

**Comment by melonamin** [comment]
@MasterGroosha Thanks.

Can you put a plugin into the Plugin Directory, and see if it works? 

A simple shell script like this will suffice:
```bash
#!/bin/bash

echo "Issue #410 :bookmark:|sfcolor=red"
```

**Comment by informatix8** [comment]
```
{
    DisabledPlugins =     (
    );
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "2FE011D8-DD0B-4557-BB08-4335744EE17C";
    MSAppCenterPastDevices = {length = 1150, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000388 };
    MSAppCenterSessionIdHistory = {length = 460, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000156 };
    MSAppCenterUserIdHistory = {length = 455, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000151 };
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~/bitbar-plugins";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-1" = 0;
    "NSStatusItem Visible Item-4" = 0;
    "NSStatusItem Visible echo.1h.sh" = 1;
    "NSStatusItem Visible test.1m.sh" = 1;
    "NSWindow Frame NSNavPanelAutosaveName" = "335 353 800 448 0 0 1470 919 ";
    PluginDirectory = "/Users/doj/bitbar-plugins";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SUSendProfileInfo = 0;
}
```

**Comment by informatix8** [comment]
Out of order, sorry. I saw the test script executed in the log. Again, nothing visible in the UI.

**Comment by melonamin** [comment]
Interesting, logs look normal - should be visible.
Any menubar tweaks? Bartender, Dozer and such?

Can you try 2.0.1? It is in beta:

![Screenshot 2024-02-27 at 15 09 42](https://github.com/swiftbar/SwiftBar/assets/222100/97e74b30-d06f-4e7d-936b-66650dca0f70)

**Comment by informatix8** [comment]
No menubar tweaks installed. I have no GUI, so cannot check that box. Attempting to build from source. On commit `b86438c` I see errors. This is the first of many. Using Xcode 14.2.

<img width="1054" alt="Screenshot 2024-02-28 at 8 15 46 AM" src="https://github.com/swiftbar/SwiftBar/assets/43178730/aa2aca53-1975-4da0-8717-afceb477f8cf">

**Comment by melonamin** [comment]
No need to build from source, it is available to download in [Releases](https://github.com/swiftbar/SwiftBar/releases/tag/v2.0.1-beta-1)

**Comment by MasterGroosha** [comment]
@melonamin Oh, I'm sorry for the confusion. First time macOS user. I have an external display connected to macbook.
Due to notch on my MBP, I don't see almost half of the menu bar icons (even though I try to hide most of them with HiddenBar app). On my external display (without notch, obviously) I see that "Issue 410" text 🤦 

MacOS is still full of surprises 🤷‍♂️

**Comment by informatix8** [comment]
No luck with the binary. :(

**Comment by melonamin** [comment]
@MasterGroosha
> MacOS is still full of surprises 🤷‍♂️
😅 Glad you've figured it out

@informatix8 
> No luck with the binary. :(

Hm, no other suggestion, let me think a bit.

**Comment by informatix8** [comment]
Thank you, you rock for trying to help me!

**Comment by melonamin** [comment]
I pushed the latest state, tried to download it and open on a fresh machine - works OK. Please try again.

Note - I'm using Xcode 15.2 and not testing on anything else.

**Comment by cappslock** [comment]
Hi,

I had a similar issue. I was poking around and noticed I had a file named mpd-control.20s.sh in my ~/Documents/Swiftbar folder. I have no idea why, I have no recollection of setting this up or ever using Swiftbar.

These were the contents of the file:

```
#!/bin/bash

# <xbar.title>mpd-control</xbar.title>
# <xbar.version>v1.0</xbar.version>
# <xbar.author>Slamet Kristanto</xbar.author>
# <xbar.author.github>drselump14</xbar.author.github>
# <xbar.desc>MPD control (mopidy spotify, mopidy soundcloud , etc)</xbar.desc>
# <xbar.image>https://www.dropbox.com/s/cgkjb7hv6s1yx1a/Screenshot%202017-02-08%2020.40.02.png?raw=1</xbar.image>
# <xbar.dependencies>mpd, mpc</xbar.dependencies>

count="$( /usr/local/bin/mpc | wc -l )"

if [ "$count" -gt 2 ]
then
  echo "$(/usr/local/bin/mpc | head -1) | bash='/usr/local/bin/mpc' param1=toggle terminal=false length=25 size=12"
else
  echo ""
fi
```

I moved this file out from the folder as a quick test and immediately SwiftBar appeared in the menubar as expected.

No clue what's going on or if this is relevant to anyone else, but thought I would share in case it was helpful.

**Comment by informatix8** [comment]
I upgraded to Ventura 13.6.6 and still use Xcode 14.13.1. No luck with the binary still. I see these errors today:
 
<img width="1582" alt="Screenshot 2024-04-03 at 1 32 48 PM" src="https://github.com/swiftbar/SwiftBar/assets/43178730/2c2788b2-61fa-47fb-8407-8dcb299ca903">

**Comment by melonamin** [comment]
As I said, I'm on Xcode 15.* and I have no idea if it works on anything below that. Based on the errors you see - the version of Swift \ macOS SDK is older than expected, thats why Xcode can't find this enum values \ struct members.

**Comment by informatix8** [comment]
Finally figured it out! My mac has a notch for the camera which was limiting menu bar items. No, they did not wrap to the other side of the notch. To fix, I installed Bartender to handle the overflowing menu items.

**Comment by melonamin** [comment]
So the same as [here](https://github.com/swiftbar/SwiftBar/issues/410#issuecomment-1969061095), well, the notch... 🤷‍♂️
