### ISSUE TITLE
SwiftBar not showing in menu bar

### ISSUE THREAD

**Issue by marcschumacher** [swiftbar/SwiftBar#418]
**Describe the bug**
After I opened SwiftBar the menu bar icon is not showing. When I force quit the application and start it again, it still does not work.

**To Reproduce**
Just start the app.

**Expected behavior**
The menu bar is showing and I can use the menu of SwiftBar.

**Environment:**
 - macOS version: 14.5 (Apple M2 Max)
 - SwiftBar version:

**Additional Context:**

- [x] I don't run Bartender/Dozer/etc. or tested the issue without it running

**Comment by melonamin** [comment]
Please check this issue https://github.com/swiftbar/SwiftBar/issues/410 
A couple of people reported the same only to find out that SwiftBar were beneath the notch.

**Comment by marcschumacher** [comment]
I don‘t have a notch. It is a MacStudio I am using.

**Comment by melonamin** [comment]
Ok. Please do what I requested in [this comment](https://github.com/swiftbar/SwiftBar/issues/410#issuecomment-1963081386)

**Comment by marcschumacher** [comment]
I was able to figure out myself, actually I had this output
```
~ ❯❯❯ defaults read com.ameba.SwiftBar                                                                                                                     ✘ 1
{
    HideSwiftBarIcon = 1;
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "268CC1B3-0DCA-4C0C-9926-57256F3C83BD";
    MSAppCenterPastDevices = {length = 1144, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000382 };
    MSAppCenterSessionIdHistory = {length = 460, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000156 };
    MSAppCenterUserIdHistory = {length = 455, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000151 };
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~/Documents/swift-bar";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-1" = 0;
    "NSStatusItem Visible mpd-control.20s.sh" = 0;
    "NSWindow Frame NSNavPanelAutosaveName" = "1320 725 800 448 0 0 3440 1415 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "1345 708 410 239 0 0 3440 1415 ";
    PluginDirectory = "/Users/marc/Documents/swift-bar";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-06-25 06:06:28 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 3592087975;
    Shell = zsh;
    StealthMode = 0;
    Terminal = iTerm;
}
```

When I removed the only script from the plugin folder, the menu item immediately appeared again. Thanks for your support!

**Comment by melonamin** [comment]
👍
