### ISSUE TITLE
Limitation? Run Plugin in Terminal Always

### ISSUE THREAD

**Issue by roizcorp** [swiftbar/SwiftBar#419]
I'm not sure if I missed it and it is not supported, I want a way to run my plugin in terminal always, currently I have to select the "run in terminal" option every time I refresh the plugin.

Also it would be good to define whether the terminal should be closed when the plugin is done or not

**Comment by melonamin** [comment]
I'm not sure I'm following. If you always want to "Run In Terminal," then my guess is you don't need SwiftBar. First and foremost, SwiftBar is needed to create menubar items; "Run In Terminal" is an auxiliary debugging feature.

Maybe if you explain what you're trying to achieve, I can advise you.

**Comment by roizcorp** [comment]
sure, sorry for trying to generalizing the need, I will specify the use case.

I stream music via http from a local-lan server

To automatically playback the stream I use MPV (different software) but it does not play any audio when run within swiftbar, it has to run with the run on a terminal option (dunno why...). the plugin I created detects when the music starts and then launch MPV to stream the music. I don't mind one of my terminal tabs executes this plugin.

**Comment by melonamin** [comment]
Ok, I see.

Mind sharing the plugin?

**Comment by roizcorp** [comment]
Sure, just let me told you what other stuff the plugin does :)

So originally it was created in order to display the song which is being played, it detects whether I am connected to an external display or not and by that decide per song whether it should scroll the song name for menu bar real estate reasons.

I'm using MPD as my music engine, so I also detected "stopped" and even "N/A" all for the plugin to be power efficient.

Recently, the MPD developer decided to ditch Mac support so I needed to stream the music through HTTP even though it runs locally - this is where MPV chimes in.
[mpd_ntfy.sh.txt](https://github.com/user-attachments/files/16107106/mpd_ntfy.sh.txt)

**Comment by melonamin** [comment]
Got it, I think the problem is that mpv is 'blocking', which is not compatible with SwiftBar operation model. I have two suggestions for you to try:
* Run mpv in the background and kill the process when you need to stop it. So `mpv --no-video --quiet http://localhost:8000 &` → `ps aux | grep mpv` → `kill <PID>`
* Or better try a proper mpd client, I remember liking [this one](https://github.com/figsoda/mmtc). It will not block the process.

**Comment by roizcorp** [comment]
Thanks, I do not believe that the client you sent streams the music. I do not have any problem controlling MPD it is just streaming the music which I am trying to solve.

I understand why you do not want to support my initial request,

Thank you for the attention.

**Comment by melonamin** [comment]
Yep, you're right, sorry for the ill advice.

One last suggestion: Apple Music can play http(s) streams, and you can talk to Apple Music through AppleScript. That might be a viable option.
