### ISSUE TITLE
UI bug: non-SwiftBar menulet icons left of a SwiftBar plug-in occasionally jitter when user accesses the plug-in menu

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#42]
On Catalina 10.15.7.

Simple test plug-in, saved as `test.10s.sh`:

```
#!/bin/zsh

echo "foo | dropdown=false"
echo "---"
echo "bar"
```

Multiple jitters begin after ca. 15 seconds into the clip, and it seems that only the icons left of the SwiftBar plug-in jitter. The GIF conversion didn't catch all, but two are clearly visible.

I also tested this with a monospaced font, and you have the same issue.

https://i.imgur.com/1Oy80SF.gif

![vsnap](https://i.imgur.com/1Oy80SF.gif)

**Comment by JayBrown** [comment]
Addendum: it seems that the jitter also happens sometimes without the user accessing the plug-in, but the latter definitely forces the glitch. But yes, it seems to occur on its own… whether it's spawned by some other process, or some other user UI interaction, I can't say.

**Comment by JayBrown** [comment]
Jitters are still present in v1.1.0 beta 1.

**Comment by melonamin** [comment]
I didn't touch this one yet(you can see it in the changelog). 
Honestly I've been looking at the video for the past two minutes and can't see a thing, maybe it is just late...

**Comment by melonamin** [comment]
@JayBrown  can you see it in 1.2.1? We've change the way dropdown works, maybe it helped

**Comment by melonamin** [comment]
Can't reproduce it on recent build, please reopen if issue persists

**Comment by JayBrown** [comment]
I'm on Big Sur now since last night, and I'm not seeing the jitter anymore. Afaik the recent build also worked in this respect on Catalina. So I guess a thank you is in order. 👍
