### ISSUE TITLE
Unable to write `|`

### ISSUE THREAD

**Issue by matopeto** [swiftbar/SwiftBar#420]
Hi, thanks for great program, but i have question (not sure if it is a bug or a feature)

is there any way to write `|` in menu row (pipe character)?

I try several escaping but no one works:

```
Escaping
---
test row
\|
\\|
\\\|
\\\\|
"|"
'|'
```

Result:

<img width="361" alt="Screenshot 2024-07-27 at 18 24 15" src="https://github.com/user-attachments/assets/d40e7865-2d94-4151-8904-baa52afbfb2d">

no one works. Is there any way?

**Comment by melonamin** [comment]
Yeah, SwiftBar is pretty **bulletproof** in this part; processing of `|` is as straightforward as it gets - it doesn't take into account any escaping whatsoever.

I consider this being a feature, not a bug.

In your case, I suggest you use the vertical pipe symbol, there are a couple in Unicode.

**Comment by matopeto** [comment]
OK, thanks for suggestion :)
