### ISSUE TITLE
SonosBar : dependency install

### ISSUE THREAD

**Issue by Pl1997** [swiftbar/SwiftBar#423]
Hello,

I'm trying to make SonosBar work on my new install of SwiftBar (macos 14.4.1) but I'm having trouble understanding how to install the required dependency "SoCo"... As soon as I installed the SonosBar plugin, the script couldn't go further than "You need to install >>soco<< | href=https://github.com/SoCo/SoCo"

I have python3 and Homebrew installed on my mac, but when I try to do "python3 -m pip install soco" I get an error "error: externally-managed-environment" with a long message explaining (in short) that I need to use a venv instead of doing potentially dangerous system wide installations of packages. 

How can I install soco on my system, and still make sure that the plugin can make use of it ?

Thank you very much for your help !

**Comment by matopeto** [comment]
try this: https://dev.to/luca1iu/how-to-fix-the-externally-managed-environment-error-when-using-pip-2omo
