### ISSUE TITLE
Exclude JSON files from plugin folder

### ISSUE THREAD

**Issue by thenktor** [swiftbar/SwiftBar#424]
Hi,

xbar uses `.json` files for plugin configuration. These files are located in the plugin folder, see https://github.com/matryer/xbar-plugins/blob/main/CONTRIBUTING.md#plugin-variable-json-files
If SwiftBar uses the same plugin folder, these files are recognized as plugins. I think it would be a could idea to exclude them for compatibility reasons.

Thanks

**Comment by melonamin** [comment]
@thenktor, we have `.swiftignore` for things like that. I suggest you use that.
More info in #358

**Comment by thenktor** [comment]
Thanks, that does the job for me 👍
