### ISSUE TITLE
Feature request: display secondary templateImage (accessImage) in the menu bar when user accesses a plug-in's menu (without refresh)

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#43]
I also posted this in the BitBar issues section here: https://github.com/matryer/bitbar/issues/573

Is it possible to make SwiftBar supply the option to change the menu bar icon, when the user clicks on it?

Reason (example): if a plugin has updated info after an auto-refresh, it would display an extended icon, e.g. colored red, and when the user clicks on it, the icon should change back to its default state, e.g. colored black, because user interaction means that he noticed there are changes, and has accessed the plug-in to view the changes, and then there is no need anymore to display this "notification icon".

For this to work, there mustn't be any plug-in refresh action on user interaction, only an icon change. So I guess that this "on-click" icon change needs to be implemented in SwiftBar's code, and available via SwiftBar argument, e.g.

```
echo "| templateImage=$icon1 accessImage=$icon2 dropdown=false"
echo "---"
echo "foo"
```

Obviously, this would not be available when running the plug-in in BitBar.

**Comment by melonamin** [comment]
After long consideration I'm closing this one based on two reasons:
* no interest from other users
* Right now from SwiftBar's perspective plugins are stateless and and I don't thing it is a good idea to mess with this concept
