### ISSUE TITLE
Support SF Symbols in the same way as emojize

### ISSUE THREAD

**Issue by jmjordan** [swiftbar/SwiftBar#46]
I really like the look of SF Symbols compared to emoji. I would like to add them to my plugin the same way you do using the emojize feature. It's possible to paste the SF Symbol into your output script, but this only works if you have the SF Symbols app installed and not all editors can display them.

**Proposal:**
Add support for SF Symbols using a similar mechanism to `emojize=true`

**Possible solution:**
Add an SF symbol to plugin output by using its system name as a token, eg. `:square.and.arrow.up:`.
App would replace occurrences of these tokens with an SF Symbol if `symbolize=true`

**Comment by melonamin** [comment]
We already have it in a form of `sfimage=...` Have you tried that?

**Comment by jmjordan** [comment]
Yes, that works great, but it only works for adding symbols to the beginning of a line. I'd like to be able to use them throughout a line of text as well.

**Comment by melonamin** [comment]
Quick take, this:
```
#!/bin/bash
echo "Test Symbols :sun.min.fill: :sun.max.fill: :cloud.snow.fill: :eyedropper:"
echo "---"
echo "Test Symbols :sun.min.fill: :sun.max.fill: :cloud.snow.fill:"
```

Becomes this:
<img width="236" alt="CleanShot 2020-12-06 at 15 25 14@2x" src="https://user-images.githubusercontent.com/222100/101291497-43cdf700-37d7-11eb-9415-2903c8b63142.png">

Kind of working:
- :sun.max.fill: :cloud.snow.fill: are colored probably because they support coloring. 
- :sun.min.fill: :eyedropper: should adopt text color, but for some reason are black in the menu bar and invisible in the menu

**Comment by jmjordan** [comment]
I was able to make the icons white by embedding them into a `NSTextAttachmentCell` but that breaks the layout. I'm worried its going to require implementing a custom `NSTextAttachmentCellProtocol`.

```
extension NSTextAttachment {
    static func centeredImage(with image: NSImage, and
                                            font: NSFont) -> NSTextAttachment {
        let imageAttachment = NSTextAttachment()
        imageAttachment.bounds = CGRect(x: 0, y: (font.capHeight - image.size.height).rounded() / 2, width: image.size.width, height: image.size.height)
//        imageAttachment.image = image
        let cell = NSTextAttachmentCell(imageCell: image)
        imageAttachment.attachmentCell = cell
        return imageAttachment
    }
}
```
<img width="226" alt="Screen Shot 2020-12-06 at 1 16 29 PM" src="https://user-images.githubusercontent.com/210460/101292589-4e7f9080-37c5-11eb-8d6e-6cc58a785766.png">

**Comment by melonamin** [comment]
I have no idea what I'm doing, but [this](https://github.com/swiftbar/SwiftBar/commit/55b9396f4954ff1af059ce5c8e8ad93c6e30a3d8) seems to be working 🤔 
```
#!/bin/bash
echo "Test :sun.max: :cloud.fill: :gamecontroller.fill: :bookmark: :sun.dust:"
echo "---"
echo "Test :bookmark:"
echo "Test :sun.max:"
```

<img width="196" alt="Screen Shot 2020-12-07 at 10 05 48 PM" src="https://user-images.githubusercontent.com/222100/101433255-5e3bc980-38d8-11eb-97c0-d72bc36885d9.png">

**Comment by jmjordan** [comment]
That looks great!

**Comment by jasonsnell** [comment]
I'm using this in the new beta and it works, but I've noticed a color mismatch. I'm using Big Sur and of course it dynamically chooses menu bar text color (black or white) based on the contents of the wallpaper. I'm in a mode where all the text is white, but the SFsymbol, which appeared white when using the old method, now displays as black with this method. (The text I've added after the SFsymbol is white!)

More broadly--and forgive me if this is being addressed elsewhere, I didn't see it--I feel like there needs to be a way to deal with Big Sur dynamically changing the text in the menu bar. In Catalina I could just detect the existence of Dark Mode and adjust text colors appropriately, but I don't seem to be able to do that in Big Sur?

<img width="241" alt="Screen Shot 2020-12-11 at 9 50 56 AM" src="https://user-images.githubusercontent.com/3698050/101937185-6032b080-3b96-11eb-982b-3a426a81f1e4.png">

**Comment by jasonsnell** [comment]
Actually I have to add another data point! :smoke: was black but :wind: shows as white. WHAT. Anyway, something weird there.

**Comment by jasonsnell** [comment]
Another issue. there is a namespace collision between emoji code and SFsymbol code, so `:house:` renders as an emoji house. Should there be some other way to name SFSymbols so they don't collide with emojis?

**Comment by melonamin** [comment]
> Actually I have to add another data point! :smoke: was black but :wind: shows as white. WHAT. Anyway, something weird there.

This was fixed after I published the beta, I referred to it in [this thread](https://github.com/swiftbar/SwiftBar/issues/46#issuecomment-740344399)  ☝️  I will push another build this weekend, stay tuned.

> Should there be some other way to name SFSymbols so they don't collide with emojis?

Let me think about that, meanwhile you can disable emoji rendering, this should give you SF Symbol.

**Comment by jmjordan** [comment]
We could use a different syntax for SFSymbols to avoid collisions. `<house>` or `{house}` perhaps?

**Comment by melonamin** [comment]
I don't know, for some reason I like that we offer a uniform syntax for these two. Should we support having emoji and SF Symbols in one line at the same time? It looks quite weird.

**Comment by jmjordan** [comment]
That's fair. I don't see why anyone would want to use both SFSymbols and emoji on the same line. If they wanted to they could always use the actual emoji instead of the decoded syntax.

**Comment by jasonsnell** [comment]
> I don't know, for some reason I like that we offer a uniform syntax for these two. 

Okay, but if I do `:house:` I need to explicitly set the mode to emoji for that line because it's got an emoji counterpart... that seems not great? I'm not really talking about mixing so much as searching for relevant sfsymbols only to find that some of them collide with emojis... not great. Is there a way to force one or the other, or is it just "emojis win, use |symbolize=true if you don't like this"...

**Comment by jasonsnell** [comment]
>  If they wanted to they could always use the actual emoji instead of the decoded syntax.

This is actually what I've done with emojis up to now. Worked fine.

**Comment by melonamin** [comment]
Ok, this is how it works now:

```
#!/bin/bash
echo "Test :smoke: :wind: :house:  | emojize=false"
```
<img width="99" alt="Screen Shot 2020-12-14 at 8 52 59 PM" src="https://user-images.githubusercontent.com/222100/102157916-5aff8b00-3e4e-11eb-9a4a-3b686b30e993.png">

Emoji wins, but you can explicitly disable it. We can switch to "SF Symbols wins" mode, if you think it is a more sensible default. Either way you can control which one will be used.

Or there is something I'm not getting?

**Comment by jmjordan** [comment]
I guess I was thinking that if you enabled symbolize it would automatically disable emojize.

**Comment by melonamin** [comment]
> I guess I was thinking that if you enabled symbolize it would automatically disable emojize.

Sorry, I think I just confused everyone:
* emoji enabled by default
* SF Symbols disabled by default
* enabling SF Symbol doesn't disable emoji

**Comment by jasonsnell** [comment]
I'm definitely confused, but as long as there's a way to turn on symbols and turn off emojis so that collisions it'll work.

Still might be easier to just keep them both on with separate reference methods, though. So I could do :house: and :symbol:house: for example.

**Comment by jasonsnell** [comment]
The real issue is I'm not 100% sure why we need emoji shortcuts since files will accept emojis as characters? Shortcuts are nice but they're a convenience since you can just drop in the emoji, whereas there's no other way to reference SFSymbols. I guess that would be my argument for giving SFSymbols priority, but the important thing is to just make a decision. 😉

**Comment by melonamin** [comment]
New behavior: SF Symbols have priority, emoji will work only if SF Symbols explicitly disabled.
