### ISSUE TITLE
URL Scheme

### ISSUE THREAD

**Issue by samnunn** [swiftbar/SwiftBar#47]
Hi everyone!

Massive thanks to @cliss for putting me onto this project. I'm so happy to have an actively-developed update to BitBar!

One BitBar feature that I use a fair bit is the URL scheme described [here](https://github.com/matryer/bitbar/blob/master/Docs/URLScheme.md). It allowed you to open or refresh a plugin like so...

`bitbar://refreshPlugin?name=brew-updates.*?.sh`

I can't seem to find this anywhere in the SwiftBar repo. Is there any appetite to include this feature?

Many thanks.

**Comment by melonamin** [comment]
We actually have it, I've added description [here](https://github.com/swiftbar/SwiftBar#url-scheme)

**Comment by samnunn** [comment]
Awesome! Thank you very much.
