### ISSUE TITLE
Swifbar should not set executable flag to files itself

### ISSUE THREAD

**Issue by matopeto** [swiftbar/SwiftBar#51]
I found this in sourcecode:

```
    func makeScriptExecutable(file: String) {
        let script = """
        if [[ -x "\(file)" ]]
        then
            echo "File "\(file)" is executable"
        else
            chmod +x "\(file)"
        fi
        """
        _ = try? shellOut(to: script)
    }
```
Swifbar add +x flag to all files in Plugins folder :( 
i think swifbar shouldn't set +x to files. This shoud be set only by user itself

**Comment by melonamin** [comment]
I'm on opposite end from you on this, having to set this flag manually in BitBar annoyed my plenty. 
Can you please elaborate why you don't like it?

In the end we can add a preference to address it, but I think that current behavior  is a better default.

**Comment by matopeto** [comment]
Thank you for quick response.

At first, i created this issue because of https://github.com/swiftbar/SwiftBar/issues/49 when script sets execute permission to all files in `.xcodeBuildTimes` folder where i store data for my https://github.com/matopeto/xcode-build-times plugin and it is bad to set executable for non plugin files.

At second, i think it is not good by security reason. Only user itself should set permission (s/he known what script/files is safe to execute, and have control whom allows execute files). Only exception is when you downloading plugin from GUI and you set executable flag because you known it is a plugin

**Comment by tjluoma** [comment]
FWIW — I could definitely see making scripts executable as a feature, especially for users who are not all that experienced with the Terminal, etc. However, if feasible, I wonder if it would make sense to do it for a specific set of extensions such as .sh, .rb, .pl, etc instead of every file.

And I think I saw another issue suggesting that SwiftBar should ignore files that start with `.` and that certainly makes sense to me too.

**Comment by melonamin** [comment]
I agree with #49 and fixed it, now all hidden files are ignored.

> Only exception is when you downloading plugin from GUI and you set executable flag because you known it is a plugin

This how I head it originally, but then during testing decided to change to current behavior. I suggest to keep it as it is, but add a preference for users who wants to disable this, what do you think?

**Comment by matopeto** [comment]
Or what about swiftbar can show ⚠️ for non executable plugins and in dropdown menu be "enable plugin"/"make executable" that set +x permission if user want?

But i understand that current behavior is good and "my behavior" can be annoyed.

I leave this decision to you. You can leave it as it is, or add preferences or something similar, and close this issue.

**Comment by melonamin** [comment]
Ok, leaving it as it is, added an option to override default behavior `defaults write com.ameba.Swiftbar MakePluginExecutable -bool NO`

> Or what about swiftbar can show ⚠️ for non executable plugins and in dropdown menu be "enable plugin"/"make executable" that set +x permission if user want?

I'll add it to a separate "nice to have" list.
