### ISSUE TITLE
Executable and parameters contains spaces is not escaped and then bash= is not working

### ISSUE THREAD

**Issue by matopeto** [swiftbar/SwiftBar#53]
I have:

```
---- Swift Bar.xcodeproj| bash='/Users/matej/Projects/Others/Xcode Build Time Counter/sources/xcodeBuildTimes.1m.php' param1=config param2=filter_toggle param3=project param4="Swift Bar.xcodeproj" param5=set refresh=true terminal=false
```
(I am using terminal false)

it is not working.

When i set `terminal=true` to see what is going on. I am seeing that filename and parameter is not escaped

it runs:

```
matej@Matejs-MacBook-Pro ~/Projects/Others/Xcode Build Time Counter/sources (master) $ /Users/matej/Projects/Others/Xcode Build Time Counter/sources/xcodeBuildTimes.1m.php config filter_toggle project Swift Bar.xcodeproj set
```

Path and shoud be escaped like this:

```
matej@Matejs-MacBook-Pro ~/Projects/Others/Xcode Build Time Counter/sources (master) $ "/Users/matej/Projects/Others/Xcode Build Time Counter/sources/xcodeBuildTimes.1m.php" config filter_toggle project "Swift Bar.xcodeproj" set
```

This is only example, it shoud be escaped in good way, eg keep in mind `"`, `'` and other special characters.

PS: bitbar has similar issue/bug (it not escaped when terminal=true), but it is working correctly when terminal=false, switbar doesn't work in both cases

**Comment by melonamin** [comment]
Couldn't find a good method in the standard library to address this, so added a very naive quoting for now to handle the simplest cases like in the example

**Comment by matopeto** [comment]
@melonamin  for standart api look at bitbar (it use NSTask for running in background (terminal=false): 

https://github.com/matryer/bitbar/blob/7eabfe0d32c067c1669160e1bc6d55e387fb091d/App/BitBar/Plugin.m#L206

It works great for terminal=false

But here:
https://github.com/matryer/bitbar/blob/7eabfe0d32c067c1669160e1bc6d55e387fb091d/App/BitBar/Plugin.m#L252

 is why Bitbar it not working when terminal=true

Its simply concats paramteres without quotes/escaping

**Comment by matopeto** [comment]
I see that you use shellOut package to run terminal=false commands, and its doing some escaping: https://github.com/JohnSundell/ShellOut/blob/master/Sources/ShellOut.swift#L483

Maybe i will run your project Monday (i do not have correct xcode installed in my "weekend" laptop :)) and determine why it is not working

**Comment by matopeto** [comment]
I think this may also fails when path to plugin contains spaces:

https://github.com/swiftbar/SwiftBar/blob/53e48498edb866e41b10d8407bd9d8e0ff1977fc/SwiftBar/Plugin/PluginManger.swift#L156

maybe there are more places like this in code. Pleas look at this.

**Comment by JayBrown** [comment]
Don't know if this helps, but I'm always doing it with escaped double quotes:

`echo "---- Swift Bar.xcodeproj | bash=\"/Users/matej/Projects/Others/Xcode Build Time Counter/sources/xcodeBuildTimes.1m.php\" param1=config param2=filter_toggle param3=project param4=\"Swift Bar.xcodeproj\" param5=set refresh=true terminal=false"`

**Comment by matopeto** [comment]
@JayBrown i think `\"` workaround after this: https://github.com/swiftbar/SwiftBar/commit/55d21880b81b783a134e53769246aa97d2155070 may not be working (but i do not try yet)

**Comment by matopeto** [comment]
With current version of swiftbar 1.0.2 (without 55d2188)

```
---- mb-ios.xcworkspace| bash=\"/Users/matej/Projects/Others/Xcode Build Time Counter/sources/xcodeBuildTimes.1m.php\" param1=config param2=filter_toggle param3=workspace param4=\"mb-ios.xcworkspace\" param5=set refresh=true terminal=false
```

it is not working even with `\"`

**Comment by matopeto** [comment]
@JayBrown 

I am changed `'` to `"` and it is not working

```
---- XcodeBenchmark.xcworkspace| bash="/Users/matej/Projects/Others/Xcode Build Time Counter/sources/xcodeBuildTimes.1m.php" param1=config param2=filter_toggle param3=workspace param4="XcodeBenchmark.xcworkspace" param5=set refresh=true terminal=false
```
is not working in current version of swiftbar 1.0.2 (witout 55d2188)

For terminal=true it produce non valid command:

```
/Users/matej/Projects/Others/Xcode Build Time Counter/sources/xcodeBuildTimes.1m.php config filter_toggle workspace XcodeBenchmark.xcworkspace set
```

I also try double escape `"` so input to bitbar would be `\"` and this wont work too.
