### ISSUE TITLE
When i choose "Run in terminal" it is attatched to current terminal command

### ISSUE THREAD

**Issue by matopeto** [swiftbar/SwiftBar#58]
Swiftbar 1.0.2

I write e.g. "cd" to terminal window and do not press enter

<img width="661" alt="obrazek" src="https://user-images.githubusercontent.com/2447996/101286870-53583a80-37ed-11eb-810c-91b25abcd923.png">

Then I chose "Run in terminal" option from swiftbar plugin menu, command is attatched to current command

<img width="661" alt="obrazek" src="https://user-images.githubusercontent.com/2447996/101286886-6c60eb80-37ed-11eb-9bf6-86ea5d710aaf.png">

I think that would be better if "run in terminal" runs in new terminal window

**Comment by melonamin** [comment]
Adjusted behavior for Terminal to match iTerm - new session(tab) for Run in Terminal

**Comment by yanzhang0219** [comment]
I don't use Terminal.app nor iTerm2, but Alacritty. "Run in Terminal" opens **two** separate Terminal.app windows and executes the script in one of them. I think it would be better if SwiftBar only open a single Terminal.app window and runs the script in it when Terminal.app is not launched yet.

**Comment by melonamin** [comment]
> "Run in Terminal" opens two separate Terminal.app windows and executes the script in one of them.

Not sure what you experiencing here, this is a piece of Apple Script that is used in "Run in Terminal"

```
tell application "Terminal"
   activate
   tell application "System Events" to keystroke "t" using {command down}
   delay 0.2
   do script "\(script)" in front window
   activate
end tell
```

**Comment by yanzhang0219** [comment]
I attached a GIF below.

The script is:
```bash
#!/usr/bin/env bash
echo "Hello World"
```

I changed the terminal to iTerm in the SwiftBar Preference. Also, I don't launch iTerm2.app before I click "Run the Terminal".

![image](https://user-images.githubusercontent.com/11582667/102032884-d68a0b00-3d6e-11eb-950b-92da227c8121.png)

**Comment by melonamin** [comment]
Mine doesn't do it, it creates new tabs.

What happens when you run the apple script I provided above in Script Editor?

**Comment by yanzhang0219** [comment]
Try to use `Command-q` to totally quit Terminal.app or iTerm2.app, then click "Run in Terminal". Does it still work fine?

The apple script works well, it launches Terminal.app and creates a second tab to run the script.
