### ISSUE TITLE
Get Plugins - Install results in file with "404: Not Found"

### ISSUE THREAD

**Issue by oefe** [swiftbar/SwiftBar#59]
After installing a plugin from the "Get Plugins" screen, SwiftBar shows a "⚠️" emoji in the menu bar.

"Show Error" displays the following Error: *name of plugin*: line 1: 404:: command not found

Checking the installed Plugin, its text is "404: Not Found%" instead of a valid script.

```sh
cd ~/Tools/SwiftBar-Plugins/
cat cycle_text_and_detail.sh
404: Not Found%
```

Apparently, SwiftBar runs into a 404 error when downloading the script, and writes that to the script file.

**Comment by melonamin** [comment]
There was a typo in URL - nobody should concatenate strings to build URLs, but this is exactly what I do 😅
Fixed, thanks for reporting.

**Comment by oefe** [comment]
Thanks! It would probably also be a good idea to improve the error handling - if the server reports an error, show an error message. Don't store the error response as script. Do you want a new issue for that?

**Comment by melonamin** [comment]
Added one myself #62
