### ISSUE TITLE
SF Symbols Not Working

### ISSUE THREAD

**Issue by cliss** [swiftbar/SwiftBar#6]
Again, perhaps this is user error, but I'm running the following plugin on Big Sur:

```bash
#!/bin/sh
if [[ $(sw_vers -productVersion) == 11* ]]; then
	echo "SF Symbols Test"
	echo "---"
	echo "sfimage=sun"
	echo 'sfimage="sun"'
	echo "| sfimage=sun"
	echo '| sfimmge="sun"'
else
	echo "Catalina is not supported"
fi
```

And when I do, I see the following:

<img width="130" alt="Screen Shot 2020-11-23 at 11 22 25 AM" src="https://user-images.githubusercontent.com/282460/99987194-2b44f200-2d7e-11eb-8e73-d0f9768576fb.png">

(It's not unreasonable for the text to be shown; I was just trying several different mechanisms to get it to work.)

**Comment by cliss** [comment]
Wait, I'm an idiot. 🤦 

`sun` is not a SF Symbol.

However, things still seem a bit wonky:

```
#!/bin/sh
if [[ $(sw_vers -productVersion) == 11* ]]; then
	echo "SF Symbols Test"
	echo "---"
	echo "| sfimage=sun.max.fill"
	echo "| sfimmge=moon"
else
	echo "Catalina is not supported"
fi
```

...only shows the sun, and not the moon.

**Comment by philhinco** [comment]
@cliss Don't you have a typo in the second line? `sfimage` vs `sfimmge`?

**Comment by cliss** [comment]
For the love, you're absolutely right. 🤦🏻‍♂️🤦🏻‍♂️

Apologies, @philhinco & @melonamin.
