### ISSUE TITLE
PLUGIN_PATH env variable needed for compiled plugins

### ISSUE THREAD

**Issue by bilal-fazlani** [swiftbar/SwiftBar#60]
Hi,

First of all thank you very much for creating this, maintaining this and most importantly maintaining basic compatibility with bitbar.

I am trying to create plugins using scala/java or other compiled languages. 

Since these are not shell scripts, I don't get access to $0 argument and so I cant invoke the plugin file from menu. 

A solution I can think of is - swiftbar provides PLUGIN_PATH env variable.

PS: I recently created https://github.com/bilal-fazlani/bitbar4s and I am really glad same plugins can be re-used in swiftbar as well.

**Comment by melonamin** [comment]
> I don't get access to $0 argument and so I cant invoke the plugin file from menu.

Hmmm, I'm not following, can you please attach an example? Executable + expected vs current behavior would be ideal. Thanks!

**Comment by bilal-fazlani** [comment]
So imagine you are trying to build a menu item which has to send an email. The plugin file knows how to send the email if the plugin file is called with an argument "send-email". 
So I just have to render 

```bash
Send email | bash="$0 send-email"
```

And it will work. Because in bash $0 will get expanded to 

```bash
Send email | bash="/users/bitbar-plugins/myplugin.5s.sh send-email"
```

depending on users configured bitbar plugin repository.

but this $0 argument is not available to compiled languages such as Java/Scala or C# for example. So when developing the plugin I will have to pre-render

```bash
Send email | bash="/users/bitbar-plugins/myplugin.5s.sh send-email"
```

but since I dont know the users configured plugin directory and filename (in case user has renamed) I can't render this. Unless SwiftBar sets an environment PLUGIN_PATH. If that happens, I can then render:


```bash
Send email | bash="$PLUGIN_PATH send-email"
``

**Comment by bilal-fazlani** [comment]
Hi, thank you very much for taking up this work and updating the environment variable. The environment variable I see being populated is `Preferences.shared.pluginDirectoryPath`
However this will not help much because for invoking the plugin, we will need the entire path including the file name.

**Comment by melonamin** [comment]
Added `SWIFTBAR_PLUGIN_PATH` as well

**Comment by bilal-fazlani** [comment]
Thank you!!
