### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by yanzhang0219** [swiftbar/SwiftBar#61]
Hello,
Thank you so much for your efforts to develop this amazing swift port of BitBar.

I really want to get the latest build from the latest master because the latest release is far behind the latest master. I tried to build the latest master, however, I don't have an Apple Developer account so an error was popped up (But, I can build BitBar using XCode without an Apple Developer account) Also, this repo doesn't support `brew --HEAD`. In addition, the beta version cannot be installed via `brew`. 

Is it possible to make the repo could be built by anyone who doesn't have an Apple Developer account like BitBar? Or can we install the beta version via `brew`? 

Thank you very much.

**Comment by melonamin** [comment]
> I really want to get the latest build from the latest master because the latest release is far behind the latest master

Don't forget about pre-releases, latest pre-release just a couple commits behind

> Is it possible to make the repo could be built by anyone who doesn't have an Apple Developer account like BitBar?

Sure, you can just disable signing in Xcode by setting Team to None, see screenshot below
<img width="1593" alt="Screen Shot 2020-12-08 at 1 03 38 PM" src="https://user-images.githubusercontent.com/222100/101522895-d8f6fa00-3955-11eb-8b01-7e9437931553.png">

> Or can we install the beta version via brew?

I don't know how to do it, but I can look into it

**Comment by yanzhang0219** [comment]
Thank you for your quick response. 

> I don't know how to do it, but I can look into it

Wow. Great! It will be perfect if the pre-release could be installed via `brew`. Thanks.

**Comment by melonamin** [comment]
On a second though, we currently using `brew cask` which means we can distribute only pre-built binaries, we have a separate issue #40 about Auto Update mechanism, and Beta updates should be a part of it, I'm closing this issue for now.
