### ISSUE TITLE
Abnormal output (1.1.0 Beta 1)

### ISSUE THREAD

**Issue by yanzhang0219** [swiftbar/SwiftBar#64]
Plugin code below:
```bash
#!/usr/bin/env bash

# <bitbar.title>Yabai Stats</bitbar.title>
# <bitbar.version>v1.0</bitbar.version>
# <bitbar.author>Rocky Zhang</bitbar.author>
# <bitbar.author.github>yanzhang0219</bitbar.author.github>
# <bitbar.desc>Show yabai status (workspace id, workspace layout) on the menubar.</bitbar.desc>
# <bitbar.dependencies>yabai, skhd</bitbar.dependencies>

export PATH="/usr/local/bin:$PATH"

spaces=$(yabai -m query --displays | jq 'sort_by(.frame.x) | map(.spaces | join(" ")) | join(" │ ")' | sed "s/\"//g")
cur_space_type=$(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .type | if . == "bsp" then "B" elif . == "float" then "F" elif . == "stack" then "S" else . end' | sed "s/\"//g")

echo "${spaces} - ${cur_space_type}"
```

My plugin shows the current total desktops (i.e., workspaces) on the menu bar, cooperating with the macOS tiling window manager yabai.

On 1.0.2, it shows like this:
![image](https://user-images.githubusercontent.com/11582667/101724981-9839d680-3a64-11eb-9e65-7a8aa51319bd.png)

`4 | 1 2 | 3` means I am using three monitors, and desktop 4 is on the left monitor, desktop 1 and 2 are on the middle monitor, desktop 3 is on the right monitor. `B` means the current desktop type is "bsp" which is used by yabai to denote that the current desktop is managed. 

However, on 1.1.0 Beta 1, it becomes abnormal. 
![image](https://user-images.githubusercontent.com/11582667/101724840-4d1fc380-3a64-11eb-8a3c-f33ccfd02f8f.png)

It only shows the hyphen. 

Thank you!

**Comment by melonamin** [comment]
I don't have yabai installed and this many monitors(lol)! 

Can you give me the full script output please, i.e. run this in terminal, this will help me test it.

**Comment by yanzhang0219** [comment]
Sure. It works on both SwiftBar version 1.0.2 and Bitbar. 
![image](https://user-images.githubusercontent.com/11582667/101856267-cd543080-3b19-11eb-86a4-52d2cff406d3.png)

**Comment by melonamin** [comment]
🤔 it's seems to be fine in my testing. Can you look at logs in Console.app and send me if you see anything?

```
#!/bin/bash
echo "4 │ 1 2 │ 3 -B"
```

<img width="638" alt="Screen Shot 2020-12-10 at 10 19 53 PM" src="https://user-images.githubusercontent.com/222100/101857657-026e7c00-3b36-11eb-9181-bb51b65fa9bd.png">

**Comment by yanzhang0219** [comment]
I tried to echo this "4 │ 1 2 │ 3 -B" directly, it works fine. That's weird.
I just now did some further testing and it seems that commands under `/usr/local/bin/` cannot be found, even though I put `export PATH="/usr/local/bin:$PATH"` at the top. 
I deleted all my codes and just left one line: `echo $(ls)`, it worked fine. However, I changed it to `echo $(yabai -m query --displays)`, it didn't work and output nothing. (command `yabai` is located under `/usr/local/bin/`).
Furthermore, I tried another command `jq` under `/user/local/bin/`: `echo $(echo 2 | jq .)` which should output a single number 2, however, nothing was output. I also tried `echo $(echo 2 | /usr/local/bin/jq .)`, and it didn't work either. 

Thank you very much.

**Comment by melonamin** [comment]
What happens if you have a script with just `jq`? Probably it will give you an error `jq: command bot found bla-bla-bla`

In my case I have installed `jq` from brew and this script works as expected:
```
#!/bin/bash
export PATH="/opt/homebrew/bin/"
echo $(echo 2 | jq .)
```

**Comment by yanzhang0219** [comment]
I just reboot my laptop and I retried the `jq`, it works, however, `yabai` still failed. 

I re-tested and tried to reproduce the issue again, I will describe it below. Thank you for your patience and all your help. 

My simplest script for testing is:
```bash
#!/usr/bin/env bash
export PATH="/usr/local/bin:$PATH"
echo "$(yabai -m query --displays) - "
```
I put a hyphen at the end.

I ran this script directly from the terminal, its output was:
![image](https://user-images.githubusercontent.com/11582667/101926859-9bc67e00-3b88-11eb-80d4-ae52e9b7cd49.png)
It just outputs a JSON array showing the information of each monitor such as how many workspaces on each monitor. 

On SwfitBar version 1.0.2:
![image](https://user-images.githubusercontent.com/11582667/101927549-7ab25d00-3b89-11eb-8938-90b2a4605f47.png)
You can see that it works as expected. It shows `[{`, i.e. the beginning of the JSON output on the menu bar and the whole output is shown on the SwiftBar dropdown menu. 

However, on version 1.1.0 Beta:
![image](https://user-images.githubusercontent.com/11582667/101927991-ed233d00-3b89-11eb-9060-6fa0126f0249.png)
It only outputs the trailing hyphen, and nothing is shown on the SwiftBar dropmenu. 

Please help. Thank you very much!

**Comment by melonamin** [comment]
Give me that JSON please

**Comment by yanzhang0219** [comment]
Sure.
```bash
[{
	"id":724074068,
	"uuid":"A06CC8EF-6A98-AFD5-E3D1-CD55B46FF121",
	"index":1,
	"spaces":[1, 2],
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":2560.0000,
		"h":1440.0000
	}
},{
	"id":69734662,
	"uuid":"A0BE1156-B7D1-7548-5E4A-8044BA23D115",
	"index":3,
	"spaces":[4],
	"frame":{
		"x":-1792.0000,
		"y":355.0000,
		"w":1792.0000,
		"h":1120.0000
	}
},{
	"id":724073307,
	"uuid":"E1781594-3C32-E5D9-1687-B122F5363C79",
	"index":2,
	"spaces":[3],
	"frame":{
		"x":2560.0000,
		"y":-176.0000,
		"w":1200.0000,
		"h":1920.0000
	}
}]
```

I just now tried to echo this json directly:
```bash
#!/usr/bin/env bash

export PATH="/usr/local/bin:$PATH"

json="[{
	"id":724074068,
	"uuid":"A06CC8EF-6A98-AFD5-E3D1-CD55B46FF121",
	"index":1,
	"spaces":[1, 2],
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":2560.0000,
		"h":1440.0000
	}
},{
	"id":69734662,
	"uuid":"A0BE1156-B7D1-7548-5E4A-8044BA23D115",
	"index":3,
	"spaces":[4],
	"frame":{
		"x":-1792.0000,
		"y":355.0000,
		"w":1792.0000,
		"h":1120.0000
	}
},{
	"id":724073307,
	"uuid":"E1781594-3C32-E5D9-1687-B122F5363C79",
	"index":2,
	"spaces":[3],
	"frame":{
		"x":2560.0000,
		"y":-176.0000,
		"w":1200.0000,
		"h":1920.0000
	}
}]"

echo "${json}"
```

It works fine totally. 
![image](https://user-images.githubusercontent.com/11582667/101930730-640e0500-3b8d-11eb-915c-3c23840a231a.png)

That's so so so weird. If this JSON is generated by yabai, it cannot be outputted.

**Comment by yanzhang0219** [comment]
Any updates for this, dude.
If you need any further testing on my end, just let me know.

**Comment by yanzhang0219** [comment]
Hello,

I did some further testing. Run `yabai --version` in terminal will print out its version like `yabai-v3.3.5`, so I put `echo $(yabai --version)` in the plugin script and then `yabai-v3.3.5` will output onto the menubar. So far so good. So it means command `yabai` can be found by SwiftBar as normal.

However, SwiftBar considers the output of other yabai commands like `yabai -m query --displays` (print out information about all the monitors in JSON format) as nothing. I am looking forward to a fix for this issue because SwiftBar is becoming my daily must-have. 

I have been using yabai for a long time and it is definitely my daily must-have. However, its loss of menubar functionality to show its own status troubles me a lot until I found SwiftBar. It is so fast and has almost everything I need, and most importantly SwiftBar is still growing rapidly,  in very active development. Using SwfitBar to show the status of all my tiling windows, all the workspaces and all monitors, my workflow becomes perfect.

Thank you!!

**Comment by melonamin** [comment]
Installed yabai, tested with the script below `yabai.2s.sh`:
```
#!/bin/bash
#yabai fails to run without USER variable
export USER=Alex

yabai -m query --displays
```

Works as expected:

<img width="438" alt="Screen Shot 2020-12-12 at 2 17 51 PM" src="https://user-images.githubusercontent.com/222100/101992990-e7f6e880-3c84-11eb-92bb-db680e0a2458.png">

🤔 🤔 🤔

**Comment by yanzhang0219** [comment]
Oh gosh!!! After adding `export USER=yanzhang`, my entire script works perfectly!! It works finally. 
I really appreciate your help!! Thank you!

Where and how did you get the information about USER is required for yabai? Before without putting USER variable, I didn't get any error but just nothing output on the menubar.

**Comment by melonamin** [comment]
Great summary, you got it right.

> If command here has an error, SwiftBar won't show this error, i.e., there is no "Show Error" item in the dropdown menu. 

See #39 SwiftBar is checking only the exit code for the whole script, that's why in my test  when I had `yabai -m query --displays` on the top level  in the script - SwiftBar immediately told me what is the problem.

> For version 1.0.2 (and also for BitBar), I still don't set USER variable explicitly in the script, but it works fine. Why? I know USER is set by the shell directly, but why can SwiftBar 1.0.2 get this variable, but SwiftBar 1.1.0 cannot get and we have to set it explicitly in the script?

Due to changes made for #50, basically we were overriding "system" env variables, I've [fixed](https://github.com/swiftbar/SwiftBar/commit/3274d94a282f1189563a9e890a8b146827860332) it.

**Comment by yanzhang0219** [comment]
Thank you for your answers 👍

> See #39 SwiftBar is checking only the exit code for the whole script, that's why in my test when I had yabai -m query --displays on the top level in the script - SwiftBar immediately told me what is the problem.

Back to the summary script above, even though the entire script exits with 0, the running of some command in the script has errors. Is it possible to show some warning information for the users?

**Comment by melonamin** [comment]
Looks like an overkill to me.

Current problem was caused by SwiftBar execution environment differ from shell, we should strive to keep them identical which lets you to debug the script in shell instead.

If you really want it - please create another issue

**Comment by yanzhang0219** [comment]
Okay. I just said casually. SwiftBar is really fantastic already. Thank you for creating and maintaining it. And thank you again for all your help. 
Closing this.
