### ISSUE TITLE
Separate color options for dark/light text conditions

### ISSUE THREAD

**Issue by jasonsnell** [swiftbar/SwiftBar#67]
Keying off of a comment I made in #46 

In Mojave and Catalina there's Dark Mode, and Big Sur increases complexity by adding a dynamically changing menu bar that can have white or black items. Leaving all color declarations off of what's displayed in the menu bar *seems* to lead things to do the right thing, at least in Big Sur. (On BitBar I used to have to use AppleScript to detect dark mode and then do the right thing.)

What might be nice is the ability to set text/symbol colors based on that status, perhaps by optionally allowing colors to be passed in a pair, with a color for a dark-text context and a color for a light-text context? I have one widget that shows different colored text based on air-quality status, and obviously certain colors only work with the right colored background.

Maybe something like:

`color=#ffffff,#000000`

In the meantime I'm just ripping color out of my menu bar items... fans of monochrome menu bars, cheer!

**Comment by melonamin** [comment]
Implemented as `color=light_color,dark_color`. If only one color provided it will be used for both light and dark appearance.
