### ISSUE TITLE
Differences from BitBar

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#69]
Hi, I just found this project. I currently use BitBar and I'm trying to figure out whether I should switch to this app instead. What new features and/or bugfixes does SwiftBar offer in comparison to BitBar? Having this documented somewhere would surely be useful to many people.

**Comment by yanzhang0219** [comment]
I stumbled across SwiftBar a couple of days weeks ago. I have noticed so far:
1. Fully written in swift
2. It is very young and making up the gaps to BitBar rapidly.
3. Most importantly, the development is very active (BitBar didn't update for around 4 years until it released a new version a couple of days ago)
4. The author is very responsive and active (in BitBar, the issues page has accumulated many posts there, and no one is managing them, no one answers them...)

**Comment by bilal-fazlani** [comment]
We should probably use github's new feature "discussions" for such topics instead of "issues"

**Comment by fenhl** [comment]
I opened this as an issue because I think it should be documented e.g. in the readme or on a wiki page.

Some other differences I've noticed are that SwiftBar fixes https://github.com/matryer/bitbar/issues/342 and https://github.com/matryer/bitbar/issues/593.

**Comment by melonamin** [comment]
@fenhl I don't think it is reasonable to keep a running list of differences compared to BitBar. SwiftBar starting point strives to support most of the BitBar API's so users could start using it right away. 

SiwftBar features should be described in the README.md, whether this feature existed or not in BitBar (like keyboard shortcut) is irrelevant in my opinion.

How I see a workflow for a new user coming in with existing BitBar plugins:
- Launch SwiftBar, see if plugins are working as expected
- If not - create an issue
- Read the README.md or Release notes - see if there any features they'd like to adopt
