### ISSUE TITLE
SWIFTBAR_PLUGIN_PATH not being set

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#71]
While writing #70, I noticed that `SWIFTBAR_PLUGIN_PATH` is [defined](https://github.com/swiftbar/SwiftBar/blob/42de9511a32eba924e809172385cf16cc0a67c05/SwiftBar/Utility/RunScript.swift#L9) but [not actually set](https://github.com/swiftbar/SwiftBar/blob/42de9511a32eba924e809172385cf16cc0a67c05/SwiftBar/Utility/RunScript.swift#L15-L23).

**Comment by melonamin** [comment]
`SWIFTBAR_PLUGIN_PATH` is set at runtime, you can see it [here](https://github.com/swiftbar/SwiftBar/search?q=swiftPluginPath)
