### ISSUE TITLE
The reset ANSI, \033[0m, does not work

### ISSUE THREAD

**Issue by yanzhang0219** [swiftbar/SwiftBar#75]
Hi,

`\033[0m` and `\e[0m` seem not work fine. 

```bash
#!/usr/bin/env bash
echo -e "\033[40;38;5;82m Hello \033[30;48;5;82m World \033[0m !!! | ansi=true"
```

![image](https://user-images.githubusercontent.com/11582667/102023916-6914b500-3d43-11eb-89c1-22e088cc0ecc.png)

I also tried `\e[0m` like `printf "\e[40;38;5;82m Hello \e[30;48;5;82m World \e[0m !!! | ansi=true"` and I has the same wrong looking.

**Comment by melonamin** [comment]
I've re-uploaded the binary, please try again

**Comment by yanzhang0219** [comment]
Fixed. Thank you.
