### ISSUE TITLE
PluginDirectory does not resolve symbolic links

### ISSUE THREAD

**Issue by kdeldycke** [swiftbar/SwiftBar#76]
Thanks @melonamin for reviving the BitBar concept into an actively maintained project! 😍

SwiftBar is working great so far with my set of plugins.

Until I tried to set the preferences manually and sets the `PluginDirectory` to a symbolic link.

To reproduce the issue:
```shell-session
$ ls /Users/kde/swiftbar
brew-services.7m.rb  meta_package_manager.7h.py
$ killall SwiftBar
$ ln -s ~/.swiftbar ~/link-to-folder
$ defaults write com.ameba.SwiftBar PluginDirectory "~/link-to-folder"
$ defaults read com.ameba.SwiftBar
{
    MakePluginExecutable = 1;
    NSNavLastRootDirectory = "~";
    NSNavPanelExpandedSizeForOpenMode = "{799, 448}";
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-4" = 0;
    "NSWindow Frame NSNavPanelAutosaveName" = "328 1626 799 448 0 0 1440 877 ";
    PluginDirectory = "~/link-to-folder";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-12-13 22:59:50 +0000";
    SUSendProfileInfo = 0;
}
$ open -a SwiftBar
```

At this point SwiftBar does not recognize the `~/link-to-folder` symbolic link as valid:

<img width="420" alt="Screen Shot 2020-12-14 at 00 44 53" src="https://user-images.githubusercontent.com/159718/102027637-c04b7180-3da5-11eb-9f83-7567828b0e79.png">

**Comment by melonamin** [comment]
Thanks for a great issue description, there were two issues: symbolic link and `~/` which needs to be expanded before use.
I've fixed both.

**Comment by kdeldycke** [comment]
Thanks @melonamin for the incredible fast fix! I'll check the behaviour once the next version gets released.

**Comment by kdeldycke** [comment]
Just wanted to confirm SwiftBar 1.1.1 perfectly fix the issue. Thanks again @melonamin ! 😃
