### ISSUE TITLE
PATH env

### ISSUE THREAD

**Issue by yanzhang0219** [swiftbar/SwiftBar#77]
Hi,
I remember I don't need to set `PATH` in the script before, however for 1.1.0, I have to set it manually, otherwise, some commands cannon be found (e.g., commands installed by brew). 
Do you think it will be better if SwiftBar could get `PATH` from shell automatically so that we don't need to set it in our script?

Thank you.

**Comment by melonamin** [comment]
But `PATH` is there, don't you have it?

**Comment by yanzhang0219** [comment]
If I don't add `export PATH="/usr/local/bin:$PATH"` in my script file, some commands like `jq` and `yabai` cannot be found.

**Comment by melonamin** [comment]
This is what I see on my machine when I run this in SwiftBar,:
```
#!/bin/bash
export
```

I have a proper `PATH`

<img width="858" alt="Screen Shot 2020-12-13 at 9 41 29 PM" src="https://user-images.githubusercontent.com/222100/102034422-f7148e00-3d8b-11eb-968d-9941abeeac12.png">

What do you see?

**Comment by yanzhang0219** [comment]
Thanks for the quick reply.
Same, however, `/usr/local/bin` is not in the `PATH` outputted by SwiftBar. 

In the terminal, when I run `echo $PATH`, the output is:
![image](https://user-images.githubusercontent.com/11582667/102034764-b14bcb80-3d73-11eb-9a70-51f76071892f.png)
You can observe that `/usr/local/bin` is in it.

However, if I write a plugin script like this below:
```bash
#!/bin/bash
echo $PATH
```
![image](https://user-images.githubusercontent.com/11582667/102034854-e22c0080-3d73-11eb-8b7f-d50207e5debb.png)
You can see that it is just a few directories there. 

Thank you.

**Comment by melonamin** [comment]
```
...
 launchPath = "/bin/bash"
 arguments = ["-c", command]
...
```

SwiftBar launches `bash` and inherits whatever you have setup there, I assume that you've defined your path in `.zshrc`, it will not be there.

**Comment by yanzhang0219** [comment]
Oh. Sorry for my stupid brain. Still confused. 
Even though I set many `PATH` in my `.zshrc`, I do not add `/usr/local/bin` into `PATH` on my own anywhere. I demonstrate my confusion below using a quick example. Thank you for your patience. 

I installed `jq` from `brew` and I run `which jq` to get `/usr/local/bin/jq`.
Then I created a new plugin script file `test.365d.sh`
```bash
#!/bin/bash
echo 2 | jq '.'
```
SwiftBar got an error showing "jq command cannot be found".
![image](https://user-images.githubusercontent.com/11582667/102038080-325a9100-3d7b-11eb-81e9-0bb341b65016.png)

However, if I run this script file directly from shell (I switched to bash) by `/bin/bash ./test.365.sh`, it works well, outputting number 2. 

Then I add `export PATH="/usr/local/bin:$PATH` to the top of the script:
```bash
#!/bin/bash
export PATH="/usr/local/bin:$PATH"
echo 2 | jq '.'
```
This time, SwiftBar could show number 2 on the menubar.

**Comment by yanzhang0219** [comment]
Thank you. 
> SwiftBar launches bash and inherits whatever you have setup there, I assume that you've defined your path in .zshrc, it will not be there.

Where does SwiftBar get the `PATH`? It just has 4 entires, much less than the `PATH` in the terminal.
Do you think it will be better if SwfitBar can pull the complete `PATH` from the shell?

Thanks.

**Comment by melonamin** [comment]
Check this build, tell me what you see [SwiftBar.zip](https://github.com/swiftbar/SwiftBar/files/5691697/SwiftBar.zip)

**Comment by yanzhang0219** [comment]
Okay. Thanks. 
The plugin script to test this is (print each entry in `PATH` on each line)
```bash
#!/usr/bin/env bash
echo $PATH | tr ':' '\n'
```
Attached a screenshot below
![image](https://user-images.githubusercontent.com/11582667/102139056-2c63bf00-3e12-11eb-8f55-dc1c6abf3150.png)

It's better, more entries in it (9 entries, before it just has 4 entries).

But, it is still incomplete. If I run the script from the terminal:
![image](https://user-images.githubusercontent.com/11582667/102139468-bad84080-3e12-11eb-85dc-6553b23372db.png)
You can see there are totally 28 entries, so there are still some entries in `PATH` that SwiftBar cannot see. 

Thank you very much.

**Comment by melonamin** [comment]
Ok, in this build there two new things:
- default system shell used instead of `/bin/bash`, so if you use ZSH it will run there.
- shell launches with `-l`, which should start it as "login shell"

Not sure what to do beyond that at this point, I suggest you just to run your `.zshrc` script in the beginning to setup the shell the way you like

**Comment by yanzhang0219** [comment]
Thanks a lot for your efforts ❤️

So far, I think the build you sent me just now is enough. At lease`/usr/local/bin` is in the `PATH` which SwfitBar uses, so all commands installed by `brew` cannot be found successfully without having to do `export PATH="/usr/local/bin:$PATH" manually in the top of the plugin script. It is already feasible enough. 

Will you release this in 1.1.1?

**Comment by yanzhang0219** [comment]
One more point (guess):
I guess `/bin/bash -l -c command` should be fine, i.e., still use the `/bin/bash` but launches with login shell. I am not sure though. I am just afraid using the default system shell instead of `/bin/bash` will have some said effect in the future. If not, the build above is totally great. 

Thank you.

**Comment by yanzhang0219** [comment]
FYI, I also stumbled across a similar question on StackOverflow, not sure whether it is helpful more or less. 
https://stackoverflow.com/a/41540786/4752729

Thanks.

**Comment by jcheshire** [comment]
> Check this build, tell me what you see [SwiftBar.zip](https://github.com/swiftbar/SwiftBar/files/5691697/SwiftBar.zip)

The $PATH is still missing some elements, but it captured $HOME and $USER correctly. This version solves my particular issue.
