### ISSUE TITLE
Add support for 10.14 Mojave?

### ISSUE THREAD

**Issue by gingerbeardman** [swiftbar/SwiftBar#78]
Please consider adding support for 10.14 Mojave.

Thanks!

**Comment by melonamin** [comment]
Unfortunately I don't think it would be possible, these are things missing on Mojave

* SwiftUI - affects preferences and Plugin Repository. Not a dealbreaker.
* Xcode 12 and probably whatever version of Swift I'm using now
* Combine framework

So It is doable, but personally I would rather commit my time to improving product as a whole. I'm OK if someone else would try to do this.

**Comment by tjluoma** [comment]
I have a Mac that I can't upgrade past Mojave, and I agree with dropping 10.14. There are only going to be fewer and fewer users of Mojave as time goes on, and there's plenty of other work to do

**Comment by gingerbeardman** [comment]
If I understand 10.14 has never been supported by this project, so it's not like it was there to drop?

**Comment by melonamin** [comment]
I think @tjluoma means "dropped support" in comparison to BitBar.

**Comment by tjluoma** [comment]
“Drop” was a poor choice of words. I just meant “not supporting 20.14” without meaning to suggest it had supported it previously.
