### ISSUE TITLE
Python user environment variables missing

### ISSUE THREAD

**Issue by jcheshire** [swiftbar/SwiftBar#79]
When running python3 scripts, I'm not getting any user environment variables. I tested this with a super simple script:

```
#!/usr/bin/env LC_ALL=en_US.UTF-8 /usr/local/bin/python3

import os

homedir = os.getenv('HOME')
print(homedir)
```

The output is `None`.

**Comment by melonamin** [comment]
Could you share logs, screenshots or more context? Works as expected on my end:

```
#!/usr/bin/env LC_ALL=en_US.UTF-8 /usr/bin/python
import os
homedir = os.getenv('HOME')
print(homedir)
user = os.getenv('USER')
print(user)
```

<img width="271" alt="Screen Shot 2020-12-14 at 12 42 46 PM" src="https://user-images.githubusercontent.com/222100/102115793-089c7b00-3e0a-11eb-8f36-c57e72792492.png">

**Comment by jcheshire** [comment]
I actually wonder if this is related to [Issue 77](https://github.com/swiftbar/SwiftBar/issues/77). For me, both ZSH and Python are not getting the expected variables when run in SwiftBar.

I show the file, the SwiftBar output, and the same commands when run in a terminal session.

<img width="676" alt="Screen Shot 2020-12-14 at 14 16 05" src="https://user-images.githubusercontent.com/377095/102125824-3f798d80-3e18-11eb-8440-67040045f7d1.png">
<img width="769" alt="Screen Shot 2020-12-14 at 14 20 06" src="https://user-images.githubusercontent.com/377095/102125846-43a5ab00-3e18-11eb-9bd2-694d1ab34cd9.png">

I had a thought: I'm running Oh-My-Zsh. I wonder if my environment variables are being declared through that rather than directly in `.zshrc`?

**Comment by yanzhang0219** [comment]
Hi, 
Issue 77 is posted by me. We have the same concern. SwiftBar only sees a few, incomplete env variables compared to the shell running in a terminal. For example, only 4 entries in `PATH` in SwiftBar compared to `PATH` in a shell of a terminal which has much more entries. 

> I had a thought: I'm running Oh-My-Zsh. I wonder if my environment variables are being declared through that rather than directly in .zshrc?

`.zshrc` will source the oh-my-zsh config script, so setting env variables through oh-my-zsh is identical to setting them directly in `.zshrc`. This is not the reason causing this issue.

I guess SwiftBar launches a shell process to execute our plugin scripts by `/bin/bash -c xxx` directly in Swift code. This shell process is not a login shell (a shell in a terminal is a login shell), so it does not pull the environment variables that our terminals use. I am not sure. Waiting for an official answer. :)

**Comment by melonamin** [comment]
Closing this a duplicate, let's continue in #77. Check the [test build](https://github.com/swiftbar/SwiftBar/issues/77#issuecomment-744723716)
