### ISSUE TITLE
sfimage retention

### ISSUE THREAD

**Issue by jasonsnell** [swiftbar/SwiftBar#8]
I have a script with a conditional - in low pollution circumstances it displays an sfimage (smoke), but in high pollution circumstances it displays text with more pollution information.

In SwiftBar, when the pollution level reaches the threshold to display text, the text is displayed--but the sfimage remains, rather than being replaced. 

I _think_ this is a mistake because I'm no longer echoing `| sfimage=smoke` but I'm not 100% on this behavior.

plugin attached

[epaaq.5m.php.zip](https://github.com/swiftbar/SwiftBar/files/5586870/epaaq.5m.php.zip)

**Comment by melonamin** [comment]
Yes, seems to be a bug. I don't have PurpleAir device and can't run the script, instead I've used a simple test:

```
#!/bin/bash
echo "| sfimage=smoke"
echo "Test"
echo "---"
```

Do you mind testing the test build attached [here](https://github.com/swiftbar/SwiftBar/pull/9#issue-526156963)?

**Comment by jasonsnell** [comment]
No Purpleair device required, actually! Anyway, I will check the test build out.
