### ISSUE TITLE
"Get Plugins" sidebar is far too narrow by default

### ISSUE THREAD

**Issue by kemayo** [swiftbar/SwiftBar#81]
The default size of the sidebar in the "get plugins" window is so narrow that several of the categories are wrapped onto multiple lines.

It seems to be 100px by default. I had to increase the width to ~128px before things stopped wrapping. That also seems to be the _max_ width defined for the toolbar, so maybe the answer here is just to automatically set it to the max available width?

<img width="1012" alt="Screen Shot 2020-12-14 at 2 11 50 PM" src="https://user-images.githubusercontent.com/2187/102130382-69ca4b80-3e16-11eb-9562-a508ab83f13c.png">

**Comment by melonamin** [comment]
AFAIK the proper split view and sidebar is available only in Big Sur, at this moment we are using HSplitView and explicit minWidth. I don't know much about SwiftUI, but if I set idealWidth or maxWidth it starts to behave weirdly. So the best I can do now is to bump 100 to 128.

I think ideally it should be GeometryReader and dynamic width or something like that.
