### ISSUE TITLE
Extra space with image menus

### ISSUE THREAD

**Issue by gilbarbara** [swiftbar/SwiftBar#84]
Hello!

I'm trying some plugins with SwiftBar and I've noticed that it adds extra space when the menu only has an image. At least with Big Sur.
Is this expected?

![bitbar-vs-swiftbar](https://user-images.githubusercontent.com/31954/102162865-c5bdc000-3e68-11eb-86e7-97e246d04836.png)

Thanks

**Comment by melonamin** [comment]
I think this was introduced in #37, @alexp2ad wanna take a look?
