### ISSUE TITLE
SF Symbols aren't affected by color

### ISSUE THREAD

**Issue by lksoft** [swiftbar/SwiftBar#86]
Even though the SFSymbols are created as templates, they do not seem to be impacted by the color setting of the StringAttributes. This would be a very nice addition.

**Comment by melonamin** [comment]
I've spend a bunch on time on that and couldn't figure out how to do it.

In UIKit-land there is a known bug, [workaround includes adding a zero length string before image](https://stackoverflow.com/a/36319475). This doesn't help on macOS

**Comment by melonamin** [comment]
Added new `sfcolor=` option to control SF Symbols tint, works same as `color=`

**Comment by lksoft** [comment]
Cool! Thanks.

**Comment by jasonsnell** [comment]
Forgive me @melonamin but what is the proper syntax to color both a symbol and text in the menu bar at the same time?

**Comment by melonamin** [comment]
Just like that @jasonsnell:

<img width="575" alt="Screen Shot 2021-01-12 at 3 32 32 PM" src="https://user-images.githubusercontent.com/222100/104369416-6c8a9000-54eb-11eb-804e-52190375ef3a.png">

**Comment by jasonsnell** [comment]
Ah! Space in between! Thanks.
