### ISSUE TITLE
SwiftBar sometimes hangs when opening a URL

### ISSUE THREAD

**Issue by fenhl** [swiftbar/SwiftBar#88]
SwiftBar sometimes becomes unresponsive after clicking on a menu item with a `href=` in [the GitHub notifications plugin](https://github.com/matryer/bitbar-plugins/blob/master/Dev/GitHub/notifications.30s.py) or [the BitBar version plugin](https://github.com/fenhl/bitbar-version), and needs to be quit using Activity Monitor. So far, I have not been able to consistently reproduce the issue, as opening the same link usually works fine after restarting SwiftBar.

**Comment by href** [comment]
I see the same issue.

**Comment by melonamin** [comment]
> I see the same issue.

Same plugins and when opening URL or different context?

**Comment by href** [comment]
When using an URL defined by `href=` in a custom plugin as part of a menu (so not when clicking the icon).

**Comment by melonamin** [comment]
So far nothing in code gives me a hint what to could be and I can't reproduce it.

I guess I'll build an automated test to try to catch it.

**Comment by bjinse** [comment]
I guess I am seeing the same. All plugins are beach balling now. I created a sample and spindump from within Activity monitor. Would it help if I send it to you?

**Comment by melonamin** [comment]
> Would it help if I send it to you?
Update: Maybe this is another hang, can't remember clicking on a href. Menu is not dropped down.

Yes, please share it with me anyway

**Comment by bjinse** [comment]
I had this several times over the last days. This morning after I woke up my laptop, SB was running fine. (I have an alert monitor that turned "red" that I interacted with.) After this I choose a simple menu item with an href and SB was stuck again. These are the dumps I created last time.
[Sample of SwiftBar.txt](https://github.com/swiftbar/SwiftBar/files/5756755/Sample.of.SwiftBar.txt)
[Spindump Swiftbar.txt](https://github.com/swiftbar/SwiftBar/files/5756757/Spindump.Swiftbar.txt)

**Comment by melonamin** [comment]
Thanks, this helps. I've suspected thread pool exhaustion and now I have a proof.
I'm still looking for a reliable way of reproducing it, meanwhile I've change a few things which may help. 

Here is a beta build, you can give it a try if you'd like: [SwiftBar.zip](https://github.com/swiftbar/SwiftBar/files/5757673/SwiftBar.zip)

**Comment by bjinse** [comment]
I will try the new build. I am not sure, but I think I see the bug every morning, after waking my laptop from sleep.

**Comment by fenhl** [comment]
Pretty sure this is fixed now, haven't had it happen since 1.2.1 while before it was pretty much a daily occurrence.
