### ISSUE TITLE
ANSI issue - default foreground color (\033[39m)

### ISSUE THREAD

**Issue by yanzhang0219** [swiftbar/SwiftBar#93]
Hi,

Thank you for your hardworking on bug fixes and new feature implements. 

I just updated to 1.1.1 and I noticed that the ANSI support is still not perfect. 
I run `echo -e "\033[48;5;248m\033[38;5;40m 1 \033[39m 2 \033[38;5;196m 3"` in the terminal, the output is shown below:
![image](https://user-images.githubusercontent.com/11582667/102443083-c4140980-3fda-11eb-95e2-a1b4a48c6703.png)
However, when I put it in a plugin script, the output is:
![image](https://user-images.githubusercontent.com/11582667/102443160-ec9c0380-3fda-11eb-8d17-d01db1400746.png)

It seems that `\033[39m`, reset the foreground color to default, doesn't work well. 

Similarly, `\033[49m`, reset the background color to default, doesn't work as well. Shown below:
Run in terminal: 
![image](https://user-images.githubusercontent.com/11582667/102443510-c4f96b00-3fdb-11eb-8446-93ca4cce0312.png)
Plugin:
![image](https://user-images.githubusercontent.com/11582667/102443492-ba3ed600-3fdb-11eb-88c9-a6c4c146744b.png)

Thank you very much. ❤️
Sorry that I keep reporting issues related to ANSI, Lol. On one hand, I really need this complex combination to implement my little plugin, and on the other hand, I wish SwiftBar to be as perfect as possible. Thanks for your patience!

**Comment by melonamin** [comment]
> Sorry that I keep reporting issues related to ANSI, Lol

Nothing to be sorry about, this feedback is very valuable.

Speaking to the issue itself - I know what is going wrong here and how to fix it, stay tuned.

**Comment by yanzhang0219** [comment]
Thank you for your kind words and quick fix. 👍🏻

**Comment by melonamin** [comment]
Please check this build when you have a chance
[SwiftBar.zip](https://github.com/swiftbar/SwiftBar/files/5718240/SwiftBar.zip)

**Comment by yanzhang0219** [comment]
Hi, 
I have finished a quick test on the build and it worked perfectly (screenshot attatched below). 👍
![image](https://user-images.githubusercontent.com/11582667/102666477-e2dde180-413b-11eb-822c-6884943e98b4.png)

Thank you.
