### ISSUE TITLE
(B[M prepended to all plugin titles

### ISSUE THREAD

**Issue by jmjordan** [swiftbar/SwiftBar#94]
After updating to v1.1.1 all of my plugins have the text `(B[M` prepended to the titles.

<img width="239" alt="Screen Shot 2020-12-16 at 9 39 08 PM" src="https://user-images.githubusercontent.com/210460/102448621-6508c180-3fe7-11eb-8a04-31ccf014013a.png">

**Comment by jmjordan** [comment]
Seems to have something to do with the output of the script from ShellOut. Maybe its something in my environment variables?
<img width="695" alt="Screen Shot 2020-12-16 at 10 26 51 PM" src="https://user-images.githubusercontent.com/210460/102451766-03982100-3fee-11eb-9a88-37ac2b3b4e54.png">

**Comment by jmjordan** [comment]
Looks like its this change to ShellOut https://github.com/swiftbar/ShellOut/commit/edafbbfdee398cdafaa8de818542212875bac379 made by @melonamin

**Comment by melonamin** [comment]
@jmjordan can you give me one of your plugins as an example? I tried a bunch and don't see it.

> Looks like its this change to ShellOut swiftbar/ShellOut@4b61afa made by @melonamin 

And this is the last change https://github.com/swiftbar/ShellOut/commit/edafbbfdee398cdafaa8de818542212875bac379 which went into release

**Comment by jmjordan** [comment]
It was happening with every script as simple as `echo "hello"`. However, it seems that it was something weird in my .bash_profile. I removed it (I don't use bash anymore anyways) and that fixed the problem. I can send you my .bash_profile if that might help.

**Comment by indeyets** [comment]
it actually looks like `ansi` is not `true` by default. while documentation tells otherwise. Is there some autodetection in SwiftBar which fails here?

**Comment by melonamin** [comment]
@indeyets `ansi` defaults to `false`. Documentation is a little misleading, I guess, it lists **accepted values**, not a default value. For `ansi` the only accepted value is `true`, which means it false by default... and as example `emojize` is `true` by default and accepts only `false` as a value.
