### ISSUE TITLE
"Run in Terminal" Doesn't Appear to Set Environment Variables

### ISSUE THREAD

**Issue by cliss** [swiftbar/SwiftBar#96]
So I was futzing with `OS_APPEARANCE`, as added by #87, and it appears that it is *not* being set when I run a script using `Run in Terminal…`. It **does** work as expected when running in the context of SwiftBar though.

Not sure if it matters, but I consider this a very minor issue.

```
casey@imacpro ~> /Users/casey/Drive/Applications/BitBar/Dark.sh
☀️
---
Activate Dark Mode| bash='/Users/casey/Drive/Applications/BitBar/Dark.sh' param0=toggle terminal=false refresh=true
```

<img width="194" alt="Screen Shot 2020-12-18 at 9 27 29 AM" src="https://user-images.githubusercontent.com/282460/102625293-40aa0380-4113-11eb-93c1-92887fcc9b81.png">

**Comment by cliss** [comment]
PS: #87 is extremely useful; thank you!!

**Comment by melonamin** [comment]
This how "Run in Terminal" works, `script` in this context is a full path to plugin file:
```
tell application "Terminal"
    activate
    tell application "System Events" to keystroke "t" using {command down}
    delay 0.2
    do script "\(script)" in front window
    activate
end tell
```

To add SwiftBar's env variables we have to have an explicit `export VAR=...` command, I can see two ways of doing this:
* Set `script` to `export var1=.. var2=  var3 =...;<path to plugin file>`
* Create a TMP file containing needed exports and original plugin file

I like the first approach better, but it will not look pretty in the Terminal.

Thoughts?

**Comment by cliss** [comment]
Personally I concur: the first option is the winner. Though perhaps less visually appealing, it's functionally a cleaner way to pull it off, IMHO.

Benefits I see off-hand:

* Not spewing needless files all over the filesystem
* Making repeated runs using ↑↩ is predictable and easily performed

Just my $0.02. Again, I consider this a **very** minor issue.

**Comment by jasonsnell** [comment]
I don't think there's any shame in writing a file to /tmp and opening it in Terminal, TBH. But if the AppleScript method is more reliable, I guess that would counterbalance its sheer lack of elegance. 😉

**Comment by melonamin** [comment]
> Making repeated runs using ↑↩ is predictable and easily performed

That's a good point, first option then
