### ISSUE TITLE
Display metadata in Preferences: Plugins

### ISSUE THREAD

**Issue by jasonsnell** [swiftbar/SwiftBar#97]
Here's an enhancement suggestion.

The plugins manager in Preferences is one of my favorite features. I used to manage enabling and disabling plugins via the filesystem in BitBar. This is better.

But... since plugins can contain metadata like Title, Version, Author, it might be nice if some of that appeared in the preferences. Right now a simplified version of the filename is displayed in larger text above the filename itself. Perhaps at some point that can be replaced with the title from within the script. 

This is probably obvious but I thought I'd mention it just in case.

**Comment by melonamin** [comment]
Better?
<img width="635" alt="Screen Shot 2020-12-18 at 11 11 46 PM" src="https://user-images.githubusercontent.com/222100/102680464-6fad8d00-4186-11eb-8432-a06913902ff0.png">

**Comment by jasonsnell** [comment]
Gorgeous!

**Comment by melonamin** [comment]
Or maybe something like this... 
<img width="812" alt="Screen Shot 2020-12-29 at 10 36 47 PM" src="https://user-images.githubusercontent.com/222100/103328308-6514b280-4a26-11eb-9460-ce17c9b1f992.png">

**Comment by bilal-fazlani** [comment]
Love this. 
Would users be able edit the schedule? 

I think they should have control over this.

**Comment by melonamin** [comment]
>Would users be able edit the schedule?

Everything should be editable, may be not in the next release thou.

**Comment by bilal-fazlani** [comment]
Other things such as author, github, version, dependencies and description ... I am not sure if user should be able to edit them. Whats the use case?

I can think there is use case for schedule to be updated by user as user might want more frequent updates than plugin developer anticipated.

**Comment by melonamin** [comment]
> Other things such as author, github, version, dependencies and description ... I am not sure if user should be able to edit them. Whats the use case?

IDK, just playing with ideas. In my mind it would be easier to edit this information from this screen than copy-paste required formatting from the README.

**Comment by melonamin** [comment]
I'm continue working on it later in #119, for now the first version released
